### PR TITLE
[Fix #7708] Support EOL disable comments on comment lines

### LINKED ISSUE #7708: End-of-line disable comments can't be used to disable an offense in a comment
Per @jonas054 in #1625:
```
End-of-line disable comments can't be used to disable an offense in a comment, currently. It will work like the other kind of disable comment, the one that needs an enable. It's an edge case, but it seems like a bug to me.

@jeffkowalski Please open a new issue. If you mention me in it, I will try to fix the problem.
```
--------

## Expected behavior

Disable an offense for a single-line comment, returning the enable state afterward

## Actual behavior

Disable comment has no effect on code comment

## Steps to reproduce the problem
```
$ cat test.rb 
# coding: utf-8     # rubocop:disable Style/Encoding
# frozen_string_literal: true

$ rubocop test.rb
Inspecting 1 file
W

Offenses:

test.rb:1:1: W: Lint/MissingCopEnableDirective: Re-enable Style/Encoding cop with # rubocop:enable after disabling it.
# coding: utf-8     # rubocop:disable Style/Encoding
^

1 file inspected, 1 offense detected
```
## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ rubocop --version
0.78.0
```

### PR DESCRIPTION
**Pull request by jonas054**
A hash mark `#` on a comment line doesn't start a new comment, so we have to pretend that it does in order to support disabling of cops on a single comment line.

### CODE REVIEW

File: lib/rubocop/comment_config.rb [hunk 1]
```diff
@@ -122,6 +123,10 @@ def each_mentioned_cop
       end
     end
 
+    def comment_on_comment_line?(comment)
```
Comment (Drenmi) [inline lib/rubocop/comment_config.rb]: What do you think about making this `#directive_on_comment_line?`, since we match the directive regexp inside? 🙂

Comment (jonas054) [reply lib/rubocop/comment_config.rb]: That's much better! I'll fix it.

**Comment by Drenmi** [comment]
Great catch! 🚀

**Comment by koic** [comment]
Thanks!
