### PR TITLE
[Fix #6962] Limit `Layout/ClassStructure` constant order offense to literal constants

### LINKED ISSUE #6962: Layout/ClassStructure bad autocorrection
I'm expecting RuboCop to always produce equivalent code when autocorrecting.

Layout/ClassStructure cop autocorrects badly

```ruby
class Foo
  def initialize; end

  local = 42
  EXAMPLE = local * 2
end

# gets autocorrected to:
class Foo
  EXAMPLE = local * 2
  def initialize; end

  local = 42
end
```

I believe that autocorrection should be disabled unless the constant is set to an independent literal (e.g. `CONSTANT = 42`). Even then, the way the code is currently moved around is wrong, like this HEREDOC case shows:

```ruby
class Foo
  def initialize; end

  TEXT = <<-EXAMPLE.freeze
  Hi!
  EXAMPLE
end

# autocorrected to:

class Foo
  TEXT = <<-EXAMPLE.freeze
  def initialize; end

  Hi!
  EXAMPLE
end
```

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.2.10 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #6962

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/class_structure_spec.rb [hunk 1]
```diff
@@ -204,6 +204,19 @@ def some_private_method
     it { expect_offense(code) }
   end
 
+  context 'constant is not a literal' do
+    specify do
+      expect_no_offenses <<~RUBY
+        class Person
+          def name; end
+
+          let foo = 5
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/class_structure_spec.rb]: let? :-)

File: lib/rubocop/cop/layout/class_structure.rb [hunk 2]
```diff
@@ -234,10 +239,11 @@ def class_elements(class_node)
           end
         end
 
-        def ignore?(classification)
+        def ignore?(classification, node)
           classification.nil? ||
             classification.to_s.end_with?('=') ||
-            expected_order.index(classification).nil?
+            expected_order.index(classification).nil? ||
+            classification == 'constants' && dynamic_constant?(node)
```
Comment (koic) [inline lib/rubocop/cop/layout/class_structure.rb]: Is `classification == 'constants'` condition necessary? I think that this node type can be specified by `dynamic_constant?`.

```
def_node_matcher :dynamic_constant?, <<~PATTERN
  (casgn nil? _ (send ...))
   ^^^^^
```

Comment (tejasbubane) [reply lib/rubocop/cop/layout/class_structure.rb]: Right, `casgn` takes care of that.

**Comment by bbatsov** [comment]
Btw, after thinking about this a bit more I'm not sure we won't to suppress the offense, as the problem we want to solve is only with the autocorrect, right? The auto-correct is not smart enough to see a constant refers to something else and changing the order messes things up, but still ideally someone has to move the constant and the related code where they belong.

File: lib/rubocop/cop/layout/class_structure.rb [hunk 3]
```diff
@@ -146,6 +146,10 @@ class ClassStructure < Cop
           (send nil? { :private :protected :public })
         PATTERN
 
+        def_node_matcher :dynamic_constant?, <<~PATTERN
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/class_structure.rb:149]: Probably it'd be better to just skip such nodes in the auto-correct instead of avoiding the offense for them.

**Comment by tejasbubane** [comment]
@bbatsov Changed implementation to allow registering offense but no autocorrect.

**Comment by tejasbubane** [comment]
@bbatsov This is ready for review.

**Comment by bbatsov** [comment]
The changes look good, but your branch has to be rebased on top of the current `master` branch due to merge conflicts.

**Review by bbatsov — APPROVED** [review]

**Comment by tejasbubane** [comment]
@bbatsov I have rebased this on top of `master`.

**Comment by marcandre** [comment]
> @bbatsov I have rebased this branch on top of `master`.

Thanks!
But the Changelog entry is not at the right place. BTW, the new task `rake changelog:fix` avoids these conflicts and entries being misplaced

**Comment by bbatsov** [comment]
I'll fix it manually, so it'd be part of today's release.

**Comment by tejasbubane** [comment]
> I'll fix it manually, so it'd be part of today's release.

Thanks! :+1:
