### PR TITLE
[Fix #6903] Handle variables with `_` for `Naming/RescuedExceptionsVariableName`

### LINKED ISSUE #6903: `Naming/RescuedExceptionsVariableName` does not handle variables with underscore
After upgrading to Rubocop `v0.67.2`, if we use a variable name with a leading `_`, the offense message ask to rename it without the underscore which flag a new `Lint/UselessAssignment` offense.

--------

## Expected behavior

The cop should deal with underscored variable name and ask to rename it keeping the `_`.

## Actual behavior

Rubocop ask me to rename my variable `e` whereas it should be `_e`.

## Steps to reproduce the problem

```ruby
class MyController < ApplicationController
  def create
    # some code here
  rescue MyException => _exception
    render_my_exception
  end
end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by anthony-robin**
Currently, this cop do not play nicely with variables that are prefixed by an `_`.

The message should take into consideration if the variable is going to be
used or not when showing the error.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb [hunk 1]
```diff
@@ -56,7 +56,11 @@ def on_resbody(node)
         private
 
         def preferred_name
-          @preferred_name ||= cop_config.fetch('PreferredName', 'e')
+          @preferred_name ||= begin
+            name = cop_config.fetch('PreferredName', 'e')
+            name = "_#{name}" if variable_name.to_s.start_with?('_')
```
Comment (anthony-robin) [inline lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb]: I'm not sure how I could use [this existing method][1] to avoid repeating code here 🤔 

[1]: https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/variable_force/variable.rb#L78-L80

**Comment by bbatsov** [comment]
@anthony-robin The changes look good, but you'll need to rebase on top of `master`.

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb (hunk 1 above)
Comment (bbatsov) [reply lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb]: The small amount of repetition is fine here.

**Comment by anthony-robin** [comment]
- Rebased with master ✅ 
- Added more specs with auto-correct now that is has been merged ✅ 

Thanks !

**Comment by bbatsov** [comment]
Thanks!
