### PR TITLE
[Fix #5181] Change the path pattern to match the hidden file

### LINKED ISSUE #4832: Exclude glob don't exclude hidden files (unexpected)
The exclude option doesn't exclude hidden files [as noticed in simplecov](https://travis-ci.org/colszowka/simplecov/jobs/281971949), where our Exclude looks like this:

```yml
AllCops:
  Exclude:
    - 'spec/fixtures/iso-8859.rb'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
```

The report is:

```
vendor/bundle/ruby/2.3.0/gems/backports-3.8.0/.irbrc:1:1: C: Prefer $LOAD_PATH over $:.

$:.unshift "./lib"
```

So, imo it should be caught by: `vendor/bundle/**/*` but the problem is the implementation of `match_path?` that is used somewhere along the line of figuring out if a file should be included or not, for a string it ends up with:

```ruby
File.fnmatch?(pattern, path, File::FNM_PATHNAME)
```

The fix would be simple (tm) because `fnmatch?` can be adjusted to match against dot/hidden files:

```ruby
File.fnmatch?(pattern, path, File::FNM_PATHNAME | File::FNM_DOTMATCH)
```

However, the tests positively assert that `match_path?` shall not match against dotfiles:

```ruby
      expect(described_class.match_path?('**/*',
                                         'dir/.hidden_file')).to be_falsey
```

So, the correct solution might be slightly more involved so I thought opening an issue first might be nicer :)

--------

## Expected behavior

The file should be excluded so my damn vendor directory isn't checked :D 

## Actual behavior

The file was checked with this configuration.

## Steps to reproduce the problem

I think above should give a good enough inside. Otherwise in a `/**/*` ignored directory just create a file named `.whatever` with ruby code that violates style guides.

## RuboCop version

I checked 0.49.1, 0.50.0 and both had the problem, from the code master as of a couple minutes ago should also have the problem.

### LINKED ISSUE #5181: AllCops "Exclude" directory is not excluding .irbrc or .pryrc files
## Expected behavior

Excluding directory like this:

```
AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
```

I expect it to exclude all files in this directory.

## Actual behavior

I have errors on two files within this directory: `.irbrc` and `.pryrc`

```
vendor/bundle/ruby/2.4.0/gems/backports-3.6.8/.irbrc:1:1: C: Style/SpecialGlobalVars: Prefer $LOAD_PATH over $:.
$:.unshift "./lib"
^^
vendor/bundle/ruby/2.4.0/gems/backports-3.6.8/.irbrc:1:12: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
$:.unshift "./lib"
           ^^^^^^^
vendor/bundle/ruby/2.4.0/gems/sidekiq-throttler-0.5.1/.pryrc:1:1: W: Lint/ScriptPermission: Script file .pryrc doesn't have execute permission.
#!/usr/bin/env ruby
^^^^^^^^^^^^^^^^^^^
```

All other files are correctly excluded.

## RuboCop version

```
$ rubocop -V
0.51.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #5181.
Fixes #4832.

This PR changes the path pattern (`*`) to match the hidden file.

This PR resolves the following problem.

```console
AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
```

The above .rubocop.yml setting is expected to cover hidden files as well. However, there is a problem that offenses occur with hidden files.

```console
vendor/bundle/ruby/2.4.0/gems/backports-3.6.8/.irbrc:1:1: C:
Style/SpecialGlobalVars: Prefer $LOAD_PATH over $:.
$:.unshift "./lib"
^^

(snip)
```

This PR solves this problem by including hidden files in the path match target.

And This PR only changes behavior to hidden files.

As resolved in #1401, #1656, hidden directories keep their previous behavior.
So hidden files in the hidden directory don't match.

Probably it will be an intuitive path match to users.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/path_util.rb [hunk 1]
```diff
@@ -59,5 +60,18 @@ def self.pwd
...
     end
+
+    def hidden_file_and_not_hidden_dir?(pattern, path)
+      File.fnmatch?(
+        pattern, path,
+        File::FNM_PATHNAME | File::FNM_EXTGLOB | File::FNM_DOTMATCH
+      ) && File.basename(path).start_with?('.') && not_hidden_dir?(path)
+    end
+
+    def not_hidden_dir?(path)
```
Comment (bbatsov) [inline lib/rubocop/path_util.rb]: Negative predicates are always odd-looking. I think we should just name this `hidden_dir?` and invert the check in it.

File: lib/rubocop/path_util.rb [hunk 2]
```diff
@@ -59,5 +60,18 @@ def self.pwd
     def self.reset_pwd
       @pwd = nil
     end
+
+    def hidden_file_and_not_hidden_dir?(pattern, path)
```
Comment (bbatsov) [inline lib/rubocop/path_util.rb]: Maybe `and` should be `in` here?

File: lib/rubocop/path_util.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/path_util.rb]: Sure, I totally agree! Thanks for the review.
