### PR TITLE
[Fix #6316] Fix auto-correct for `Style/For` cop

### LINKED ISSUE #6316: Error with 'Style/For' cop: undefined method `end' for #<Parser::Source::Map::Operator:...>
When running rubocop on loops like:

```ruby
for a in 1...some_var
    do_something(a)
end
```

## Expected behavior

It should autocorrect to `each` like this:

```ruby
(1...some_var).each do |a|
    do_something(a)
end
```
## Actual behavior

I get the following exception:

```
An error occurred while Style/For cop was inspecting /home/user/src/test.rb:3:0.
undefined method `end' for #<Parser::Source::Map::Operator:0x00000000024446c8>
Did you mean?  send
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/style/for.rb:103:in `autocorrect_to_each'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/style/for.rb:86:in `autocorrect'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/cop.rb:153:in `correct'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/cop.rb:131:in `add_offense'
/home/user/.rvm/gems/ruby-2.4.4@default/bundler/gems/rubocop-b835bc6c5781/lib/rubocop/cop/style/for.rb:63:in `on_for'
```

## Steps to reproduce the problem

Just run `rubocop -a` on any file with the provided example using the default configuration.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.59.1 (using Parser 2.5.1.2, running on ruby 2.4.4 x86_64-linux)
```

Running directly from github code, git commit: b835bc6c5781

### PR DESCRIPTION
**Pull request by lukasz-wojcik**
Fixes #6316 

It also makes sure that when the range is provided with or  without an enclosing parenthesis the resulting auto correction to `each` will generate a valid code. 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/for_spec.rb [hunk 1]
```diff
@@ -50,6 +50,68 @@ def func
...
       end
 
+      context 'with range' do
+        let(:expected_each_with_range) do
+          <<-RUBY.strip_indent
+          def func
+            (1...value).each do |n|
+              puts n
+            end
+          end
```
Comment (koic) [inline spec/rubocop/cop/style/for_spec.rb]: Please indent the heredoc contents.

```diff
  <<-RUBY.strip_indent
- def func
-   (1...value).each do |n|
-     puts n
-   end
- end
+   def func
+     (1...value).each do |n|
+       puts n
+     end
+   end
  end
```

File: spec/rubocop/cop/style/for_spec.rb [hunk 2]
```diff
@@ -50,6 +50,68 @@ def func
...
+          RUBY
+        end
+
+        it 'changes for to each' do
+          new_source = autocorrect_source(<<-RUBY.strip_indent)
+          def func
+            for n in (1...value) do
+              puts n
+            end
+          end
```
Comment (koic) [inline spec/rubocop/cop/style/for_spec.rb]: Ditto.
The same applies to other heredoc contents in this PR.

File: spec/rubocop/cop/style/for_spec.rb [hunk 3]
```diff
@@ -68,7 +130,7 @@ def func
         RUBY
       end
 
-      it 'changes for that dose not have do or semicolon to each' do
+      it 'changes for that does not have do or semicolon to each' do
```
Comment (koic) [inline spec/rubocop/cop/style/for_spec.rb]: 👍

File: CHANGELOG.md [hunk 4]
```diff
@@ -13,6 +13,7 @@
 * [#6305](https://github.com/rubocop-hq/rubocop/pull/6305): Fix infinite loop for `Layout/EmptyLinesAroundAccessModifier` and `Layout/EmptyLinesAroundAccessModifier` when specifying a superclass that breaks the line. ([@koic][])
 * [#6007](https://github.com/rubocop-hq/rubocop/pull/6007): Fix false positive in `Style/IfUnlessModifier` when using named capture. ([@drenmi][])
 * [#6315](https://github.com/rubocop-hq/rubocop/pull/6315): Fix an error for `Rails/HasManyOrHasOneDependent` when an Active Record model does not have any relations. ([@koic][])
+* [#6320](https://github.com/rubocop-hq/rubocop/pull/6320): Fix an auto-correct error for `Style/For` when setting `EnforcedStyle: each` with range provided to the `for` loop without a `do` keyword or semicolon and without enclosing parenthesis. ([@lukasz-wojcik][])
```
Comment (koic) [inline CHANGELOG.md]: It is better to show the corresponding issue `#6316`.

```diff
- [#6320](https://github.com/rubocop-hq/rubocop/pull/6320): Fix an auto-correct error for `Style/For` when setting `EnforcedStyle: each` with range provided to the `for` loop without a `do` keyword or semicolon and without enclosing parenthesis. ([@lukasz-wojcik][])
+ [#6316](https://github.com/rubocop-hq/rubocop/issues/6316): Fix an auto-correct error for `Style/For` when setting `EnforcedStyle: each` with range provided to the `for` loop without a `do` keyword or semicolon and without enclosing parenthesis. ([@lukasz-wojcik][])
```

File: lib/rubocop/cop/style/for.rb [hunk 5]
```diff
@@ -99,14 +99,39 @@ def incorrect_style_detected(node)
...
+        end
+
+        def enumerable_source(enumerable)
+          return "(#{enumerable.source})" if wrap_into_parentheses?(enumerable)
+
+          enumerable.source
+        end
+
+        def wrap_into_parentheses?(enumerable)
+          !enumerable.begin_type? &&
```
[the remark this answers is not in the document]
Comment (lukasz-wojcik) [reply lib/rubocop/cop/style/for.rb]: This is needed for the case:
```
for n in 1...value
....
```

when range is not enclosed in parenthesis the `begin_type?`  check returns false. Then we know that autocorrect must wrap the enumerable.source into `( ... )`. Otherwise it would generate invalid code:
`1...value.each`

[the remark this answers is not in the document]
Comment (koic) [reply lib/rubocop/cop/style/for.rb]: Thanks for the explanation. I have one concern.
Even without this condition all test cases will succeed.

```diff
% g diff
diff --git a/lib/rubocop/cop/style/for.rb b/lib/rubocop/cop/style/for.rb
index 2c4a5e197..a14bf21c3 100644
--- a/lib/rubocop/cop/style/for.rb
+++ b/lib/rubocop/cop/style/for.rb
@@ -127,7 +127,6 @@ module RuboCop
         end

         def wrap_into_parentheses?(enumerable)
-          !enumerable.begin_type? &&
-            (enumerable.irange_type? ||
-             enumerable.erange_type?)
+          enumerable.irange_type? ||
+            enumerable.erange_type?
         end
```

```console
% bundle exec rspec spec/rubocop/cop/style/for_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 12381
.....................

Finished in 0.12819 seconds (files took 1.32 seconds to load)
21 examples, 0 failures

Randomized with seed 12381
```

Could you add a new test case that requires that condition?

[the remark this answers is not in the document]
Comment (koic) [reply lib/rubocop/cop/style/for.rb]: I think that's enough because there are written test cases with and without parentheses.
Thank you!
