### PR TITLE
[Fix #7675] Fix a false negative for `Layout/SpaceBeforeFirstArg`

### LINKED ISSUE #7675: Layout/SpaceBeforeFirstArg doesn't alert when randomly aligning with previous line
Ran in to a situation in our codebase where `Layout/SpaceBeforeFirstArg` wasn't reporting a line that should have been reported. After some debugging this seems to be a problem with the `aligned_with_something?` method thinking that 2 unrelated lines are aligned.

--------

## Expected behavior

Expected to receive an offense.

## Actual behavior

Received no offense.

## Steps to reproduce the problem

```
$ cat foo.rb
foo = Foo.new(arg, option: true)
foo.long_method_123'asdf'
$ rubocop --only Layout/SpaceBeforeFirstArg foo.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```
Changing the file so that `'asdf'` does not align with `option: true` causes the offense to then be reported.
```
$ cat foo.rb
foo = Foo.new(arg, option: true)
foo.long_method_12'asdf'
$ rubocop --only Layout/SpaceBeforeFirstArg foo.rb
Inspecting 1 file
C

Offenses:

foo.rb:2:19: C: Layout/SpaceBeforeFirstArg: Put one space between the method name and the first argument.
foo.long_method_12'asdf'


1 file inspected, 1 offense detected
```

## RuboCop version
```
$ rubocop -V
0.79.0 (using Parser 2.7.0.2, running on ruby 2.4.5 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7675.

This PR fixes a false negative for `Layout/SpaceBeforeFirstArg` when a vertical argument positions are aligned.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
CI failure will be resolved by #7679.

File: lib/rubocop/cop/layout/space_before_first_arg.rb [hunk 1]
```diff
@@ -54,13 +54,21 @@ def regular_method_call_with_arguments?(node)
...
+          return true if touch_between_method_name_and_first_argument?(node)
 
           first_arg = node.first_argument
 
           same_line?(first_arg, node) &&
             !(allow_for_alignment? &&
               aligned_with_something?(first_arg.source_range))
         end
+
+        def touch_between_method_name_and_first_argument?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/space_before_first_arg.rb]: I'm not sure I understand the name of this method. What is touch between supposed to mean?

Comment (koic) [reply lib/rubocop/cop/layout/space_before_first_arg.rb]: Ah, I did a confusing naming 💦 
I'd like to change the name to `def no_space_between_method_name_and_first_argument?`

```ruby
# no space (bad)
do_something'arg' 

# with space (good)
do_something 'arg' 
```

Comment (bbatsov) [reply lib/rubocop/cop/layout/space_before_first_arg.rb]: 👍

Comment (koic) [reply lib/rubocop/cop/layout/space_before_first_arg.rb]: Thank you for your review. I updated the method name.

**Comment by bbatsov** [comment]
Thanks!
