### PR TITLE
[Fix #6603] - Testing RescueEnsureAlignment

### LINKED ISSUE #6603: Layout/RescueEnsureAlignment issue with nested begin
Looks similar to #6433 

## Expected behavior

No error emitted

## Actual behavior

Cop expects `rescue` to be aligned with `begin`

## Steps to reproduce the problem

```ruby
def some_method
  @ivar ||= begin
     1
  rescue
    2
  end
end
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.61.1 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by jaredbeck**
Add a test to demonstrate the correct styles of a begin-rescue as the
RHS of an assignment.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb [hunk 1]
```diff
@@ -36,6 +36,30 @@
         end
       RUBY
     end
+
+    context 'as RHS of assignment' do
+      it 'accepts multi-line assignment' do
+        expect_no_offenses(<<-RUBY.strip_indent)
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb]: I think we also need a similar example when the `begin` is on the same line as the assignment op.

**Comment by jaredbeck** [comment]
> I think we also need a similar example when the begin is on the same line as the assignment op.

Example added.

**Comment by bbatsov** [comment]
Thanks!
