### PR TITLE
[Fix #6633] Fix `Lint/SafeNavigation` complaining about use of `to_d`

### LINKED ISSUE #6633: Lint/SafeNavigationChain shouldn't complain about chaining `to_d`
## Expected behavior

`nil.to_d` returns `0.0`, so Rubocop should **not** complain about this case in particular.

## Actual behavior

It complains:
```
# Lint/SafeNavigationChain: Do not chain ordinary method call after safe navigation operator.
```

**Note:** Rubocop doesn't complain about the  same code with `to_f`.

## Steps to reproduce the problem

Just write the following code and run Rubocop:

```ruby
amount&.slice.to_d
```

## RuboCop version

```
0.62.0 (using Parser 2.5.3.0, running on ruby 2.6.0 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Fixes: https://github.com/rubocop-hq/rubocop/issues/6633

`to_d` is defined in `bigdecimal/util` in stdlib and hence should be handled like other default methods on `nil`. Refer https://github.com/rubocop-hq/rubocop/issues/6633#issuecomment-452189702

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

### CODE REVIEW

File: lib/rubocop/cop/mixin/nil_methods.rb [hunk 1]
```diff
@@ -8,12 +8,16 @@ module NilMethods
...
-        nil.methods + whitelist
+        nil.methods + other_stdlib_methods + whitelist
       end
 
       def whitelist
         cop_config['Whitelist'].map(&:to_sym)
       end
+
+      def other_stdlib_methods
+        [:to_d]
```
Comment (bbatsov) [inline lib/rubocop/cop/mixin/nil_methods.rb]: Why just not add this to the default whitelist?

Comment (bbatsov) [reply lib/rubocop/cop/mixin/nil_methods.rb]: (if we keep the current approach we'll also need to update the description of the class)

Comment (tejasbubane) [reply lib/rubocop/cop/mixin/nil_methods.rb]: I find keeping the three separate slightly cleaner. Updated class description accordingly. Also rebased the PR.

**Comment by bbatsov** [comment]
Can you rebase again?

**Comment by tejasbubane** [comment]
@bbatsov Rebased.

**Comment by bbatsov** [comment]
Thanks!
