### PR TITLE
[Fix #6699] Fix a false negative for `Layout/IndentationWidth`

### LINKED ISSUE #6699: IndentationConsistency+IndentationWidth infinite loop
With the following file:
```
class Example
      private

  def my_method; end
    end
```

When running the following command:
```
$ rubocop --auto-correct --only Layout/IndentationConsistency,Layout/IndentationWidth myfile.rb

Offenses:

myfile.rb:4:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 6) spaces for indentation.
      def my_method; end
^^^^^^
myfile.rb:4:3: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
  def my_method; end
  ^^^^^^^^^^^^^^^^^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /tmp/myfile.rb.
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:270:in `check_for_infinite_loop'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:253:in `block in iterate_until_no_changes'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `loop'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `iterate_until_no_changes'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:223:in `do_inspection_loop'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:126:in `block in file_offenses'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:144:in `file_offense_cache'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:124:in `file_offenses'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:112:in `process_file'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:89:in `block in each_inspected_file'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `reduce'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:76:in `inspect_files'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:48:in `run'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:174:in `execute_runner'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:75:in `execute_runners'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:47:in `run'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/exe/rubocop:13:in `block in <top (required)>'
/home/shai/.rbenv/versions/2.6.0/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/shai/.gem/ruby/2.6.0/gems/rubocop-0.63.1/exe/rubocop:12:in `<top (required)>'
/home/shai/.rbenv/versions/2.6.0/bin/rubocop:23:in `load'
/home/shai/.rbenv/versions/2.6.0/bin/rubocop:23:in `<main>'
```

## RuboCop version
0.63.1 (using Parser 2.5.3.0, running on ruby 2.6.0 x86_64-linux)

Might be related to #6520

### PR DESCRIPTION
**Pull request by koic**
Fixes #6699.

This PR fixes infinite loop for `Layout/IndentationWidth` and `Layout/IndentationConsistency` when bad modifier indentation before good method definition.

```ruby
# exmaple.rb
class Foo
      private

  def foo
  end
end
```

First, auto-corrected by `Layout/IndentationConsistency`.

```console
% rubocop -v
0.65.0
% rubocop -a --only Layout/IndentationConsistency example.rb
Inspecting 1 file
C

Offenses:

example.rb:4:3: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
  def foo ...
  ^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

```diff
% g diff
diff --git a/example.rb b/example.rb
index 23d3556..974f101 100644
--- a/example.rb
+++ b/example.rb
@@ -1,6 +1,6 @@
 class Foo
       private

-  def foo
-  end
+      def foo
+      end
 end
```

Next, auto-corrected by `Layout/IndentationWidth`.

```console
% rubocop -a --only Layout/IndentationWidth example.rb
Inspecting 1 file
C

Offenses:

example.rb:4:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 6)
spaces for indentation.
      def foo
^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

This will return to the original code.

```diff
% g diff
diff --git a/example.rb b/example.rb
index 974f101..23d3556 100644
--- a/example.rb
+++ b/example.rb
@@ -1,6 +1,6 @@
 class Foo
       private

-      def foo
-      end
+  def foo
+  end
 end
```

That caused the infinite loop in `Layout/IndentationConsistency` and `Layout/IndentationWidth`.

With this PR, `Layout/indentationWidth` cop makes aware of the bad modifier indentation before good method definition.

```console
% rubocop -a --only Layout/IndentationWidth example.rb
Inspecting 1 file
C

Offenses:

example.rb:2:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 6)
spaces for indentation.
      private
^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

```diff
diff --git a/example.rb b/example.rb
index 23d3556..07525ec 100644
--- a/example.rb
+++ b/example.rb
@@ -1,5 +1,5 @@
 class Foo
-      private
+  private

   def foo
   end
```

This PR fixes the above false negative. That would be an auto-correct expected.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/indentation_width.rb [hunk 1]
```diff
@@ -161,15 +161,12 @@ def autocorrect(node)
...
+          check_indentation(base, select_check_member(members.first))
 
           return unless members.any? && members.first.begin_type?
 
           if indentation_consistency_style == 'rails'
-            each_member(members) do |member, previous_modifier|
-              check_indentation(previous_modifier, member,
-                                indentation_consistency_style)
-            end
+            check_members_for_rails_style(members)
```
Comment (koic) [inline lib/rubocop/cop/layout/indentation_width.rb]: 📝I extracted to the method because it was warned by `Metrics/AbcSize` cop.

File: lib/rubocop/cop/layout/indentation_width.rb [hunk 2]
```diff
@@ -179,6 +176,24 @@ def check_members(base, members)
           end
         end
 
+        def select_check_member(member)
+          if member &&
+             member.children[0].is_a?(RuboCop::AST::Node) &&
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/indentation_width.rb]: What are some cases where the first child would not be `nil` or `Node`? If there are such cases, we should add unit tests. If we can't think of any, this might be a bit defensive. 🙂

File: lib/rubocop/cop/layout/indentation_width.rb [hunk 3]
```diff
@@ -179,6 +176,24 @@ def check_members(base, members)
           end
         end
 
+        def select_check_member(member)
+          if member &&
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/indentation_width.rb]: Perhaps we can use a node pattern to clean this up, e.g.:

```ruby
def_node_matcher :access_modifier?, <<-PATTERN
  [(send ...) access_modifier?]
PATTERN

def select_check_member(member)
  return unless member

  if access_modifier?(member.children.first)
    member.children.first
  else
    member
  end
end
```

Comment (koic) [reply lib/rubocop/cop/layout/indentation_width.rb]: Oh, I could not think of this method. Thank you for telling me a fine approach!

File: lib/rubocop/cop/layout/indentation_width.rb (hunk 2 above)
Comment (koic) [reply lib/rubocop/cop/layout/indentation_width.rb]: I updated to the following fine approach.
https://github.com/rubocop-hq/rubocop/pull/6792#discussion_r260104653
