### PR TITLE
[Fix #6196] Fix incorrect autocorrect for `Style/EmptyCaseCondition`

### LINKED ISSUE #6196: Style/EmptyCaseCondition autofix breaks code when returning from branches
## Expected behavior

Given the smallest example

```ruby
def a
  c = case
      when x.a
        1
      when x.b
        return 2
      end
  c + c
end
```

Run rubocop with autofix mode. Expected to leave it as is (at least working) or format.

## Actual behavior

The result is

```ruby
def a
  c = if x.a
        1
      elsif x.b
        return 2
      end
  c + c
end
```

That's broken program, fails with "void value expression"

## RuboCop version

0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)

### PR DESCRIPTION
**Pull request by koic**
Fixes #6196.

This PR fixes an incorrect autocorrect for `Style/EmptyCaseCondition` when using `return` in `when` clause and assigning the return value of `case`.

The following code returns `2`.

```ruby
def foo
  v = case
      when true
        return 2
      end
end

p foo # => 2
```

The following code raises "void value expression" error.

```ruby
def bar
  v = if true
        return 2
      end
end

bar # => hoge.rb:4: void value expression
```

I think that it is difficult to keep compatibility with auto-correct.
Therefore this PR changes the above case to false negative.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/empty_case_condition.rb [hunk 1]
```diff
@@ -80,6 +83,18 @@ def correct_when_conditions(corrector, when_nodes)
             corrector.replace(range, conditions.map(&:source).join(' || '))
           end
         end
+
+        def exist_return_node?(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/style/empty_case_condition.rb]: This entire method can be replaced by:

```ruby
node.each_descendant.any?(&:return_type?)
```

and inlined. 🙂 

🙂

File: spec/rubocop/cop/style/empty_case_condition_spec.rb [hunk 2]
```diff
@@ -194,5 +194,19 @@
 
       it_behaves_like 'detect/correct empty case, accept non-empty case'
     end
+
+    context 'When using `return` in `when` clause and ' \
```
Comment (Drenmi) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb]: Let's lowercase the leading "when" in the context description. 🙂

File: spec/rubocop/cop/style/empty_case_condition_spec.rb [hunk 3]
```diff
@@ -194,5 +194,19 @@
...
+            'assigning the return value of `case`' do
+      it 'does not register an offense' do
+        expect_no_offenses(<<-RUBY.strip_indent)
+          v = case
+              when x.a
+                1
+              when x.b
+                return 2 if foo
```
Comment (Drenmi) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb]: What if the `return` is in the `else` clause? 🤔

File: lib/rubocop/cop/style/empty_case_condition.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/style/empty_case_condition.rb]: Sure! I did not notice this. It will be a simple code 😃 Thanks for your advise.

File: spec/rubocop/cop/style/empty_case_condition_spec.rb (hunk 3 above)
Comment (koic) [reply spec/rubocop/cop/style/empty_case_condition_spec.rb]: I overlooked it 💦  I added test code and implementation for `else` clause.
