### PR TITLE
[Fix #7620] Fix a false positive for `Migration/DepartmentName`

### LINKED ISSUE #7620: The Migration/DepartmentName cop doesn't handle comments with double comments
# Expected behavior

The `Migration/DepartmentName` cop shouldn't trigger on a comment like this:

```
# rubocop:disable Style/SafeNavigation # support Ruby < 2.3.0
```

I understand this might not be considered an appropriate RuboCop comment. It's not code within my codebase so I don't really control how the user here decided to write their comments. Regardless of the syntax it seems incorrect to alert the `Migration/DepartmentName` cop for this comment line and worse that the cop claims it autocorrect it every time RuboCop runs.

## Actual behavior

```
foo/libraries/bar/string_utils.rb:46:54: C: [Corrected] Migration/DepartmentName: Department name is missing.
    # rubocop:disable Style/SafeNavigation # support Ruby < 2.3.0
                                                     ^^^^
```

## Steps to reproduce the problem

Run `rubocop -a --only Migration/DepartmentName` against a file with the above comment.

## RuboCop version

```
0.78.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7620.

This PR fixes the following false positive for `Migration/DepartmentName` when a disable comment contains a plain comment.

```console
% cat example.rb
# rubocop:disable Style/SafeNavigation # support Ruby < 2.3.0

% rubocop --only Migration/DepartmentName
Inspecting 1 file
C

Offenses:

example.rb:1:50: C: Migration/DepartmentName: Department name is missing.
# rubocop:disable Style/SafeNavigation # support Ruby < 2.3.0
                                                 ^^^^

1 file inspected, 1 offense detected
```

The following is an example disable comment.

```ruby
# rubocop:disable Style/FrozenStringLiteralComment, Style/StringLiterals
```

The token used after `# rubocop: disable` are `A-z`, `/`, `,`.
And `A-z` includes `all`.

```ruby
# rubocop:disable all
```

This PR will change the processing of `Migration/DepartmentName` cop to finish when an invalid token is used.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/migration/department_name.rb [hunk 1]
```diff
@@ -10,13 +10,18 @@ class DepartmentName < Cop
 
         MSG = 'Department name is missing.'
 
+        DISABLING_COPS_CONTENT_TOKEN = /[A-z,]+/.freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/migration/department_name.rb]: What exactly is the content token? Perhaps some comment would be useful here.

Comment (koic) [reply lib/rubocop/cop/migration/department_name.rb]: Sure! I added a comment about the content token.

**Comment by bbatsov** [comment]
Thanks!
