### PR TITLE
[Fix #7091] Extract FormatString parser

### LINKED ISSUE #7091: Style/FormatStringToken with flags/modifiers
PoC code:

```ruby
def foo
  puts format('%s %s', 'foo', 'bar')
  puts format('%-20s %s', 'foo', 'bar')
  puts format('%-20s %-30s', 'foo', 'bar')
end
```

--------

## Expected behavior

6 warnings of `Style/FormatStringToken` to prefer annotated tokens

## Actual behavior

Only the `%s` items are detected. Any flag or modifier to the format string makes them unrecognized.

## Steps to reproduce the problem

See PoC

## RuboCop version

```
0.70.0 (using Parser 2.6.3.0, running on ruby 2.3.3 i386-linux-gnu)
```

### PR DESCRIPTION
**Pull request by buehmann**
This extracts and unifies the format string parsing from two different cops. As a consequence, `Style/FormatStringToken` is now able to inspect more variants of format sequences.

I didn't really know where to best put the `FormatString` class, so I am open for suggestions. Maybe there is a place for such auxiliary classes that I overlooked.

### CODE REVIEW

File: spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb [hunk 1]
```diff
@@ -197,10 +197,6 @@
     expect_no_offenses('format("%0*x", max_width, id)')
   end
 
-  it 'accepts an extra arg for dynamic width with other following flags' do
-    expect_no_offenses('format("%*0x", max_width, id)')
```
Comment (buehmann) [inline spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb]: It turned out that `%*0x` is not a valid format sequence. MRI does not accept it.

**Comment by bbatsov** [comment]
> I didn't really know where to best put the FormatString class, so I am open for suggestions. Maybe there is a place for such auxiliary classes that I overlooked.

All of them live under `rubocop/` now, but I agree it's better to have an `Util` folder/namespace for them. I wonder how many of the existing ones can be moved without breaking something so we can clean up a bit the file structure.
