### PR TITLE
[Fix #5968] Don't consider << heredocs for Layout/ClosingHeredocIndentation

### LINKED ISSUE #5968: Layout/ClosingHeredocIndentation and <<
## Expected behavior

```rb
def foo
  <<STR
bar
STR
end
```

No offense should be detected here, since `<<` heredocs *must* end with an *unindented* identifier (here `STR`). Only `<<-` or `<<~` heredocs allow indentation of the closing indentifier.

## Actual behavior

One offense is found:
```
C: Layout/ClosingHeredocIndentation: STR is not aligned with <<STR.
STR
^^^
```

## Steps to reproduce the problem

Run `rubocop --only Layout/ClosingHeredocIndentation` on a file with the above contents.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.57.1 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Detects `<<` heredocs (as opposed to `<<-` or `<<~`) and doesn't add an offense for those, as they require the closing identifier to be unindented.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/closing_heredoc_indentation.rb [hunk 1]
```diff
@@ -49,18 +49,18 @@ module Layout
...
+          return if heredoc_type(node) == SIMPLE_HEREDOC
+
           if empty_heredoc?(node) ||
              contents_indentation(node) >= closing_indentation(node)
             return if opening_indentation(node) == closing_indentation(node)
-            return if node.argument? &&
-                      opening_indentation(
-                        find_node_used_heredoc_argument(node.parent)
-                      ) == closing_indentation(node)
+            return if argument_indentation_correct?(node)
```
Comment (dvandersluis) [inline lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: I needed to extract this to pass CyclomaticComplexity

Comment (bquorning) [reply lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: Good call.

File: spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb [hunk 2]
```diff
@@ -140,5 +150,19 @@ def foo
...
+          def foo
+            <<SQL
+              bar
+        SQL
+          end
+        end
+      RUBY
+
+      expect(autocorrect_source(source)).to eq source
+    end
```
Comment (koic) [inline spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb]: Probably this test case is unnecessary. Previously, I was pointed out as follows 😃 

> `expect_no_offenses` is enough to check this cop does not auto-correct.

https://github.com/rubocop-hq/rubocop/pull/4764#discussion_r140652557

File: lib/rubocop/cop/layout/closing_heredoc_indentation.rb [hunk 3]
```diff
@@ -49,18 +49,18 @@ module Layout
       class ClosingHeredocIndentation < Cop
         include Heredoc
 
+        SIMPLE_HEREDOC = '<<'.freeze
         MSG = '`%<closing>s` is not aligned with `%<opening>s`.'.freeze
         MSG_ARG = '`%<closing>s` is not aligned with `%<opening>s` or ' \
                   'beginning of method definition.'.freeze
 
         def on_heredoc(node)
+          return if heredoc_type(node) == SIMPLE_HEREDOC
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: I find this a bit odd. Probably we should be returning some symbol for this method instead of the delimiter and probably we should also have this as a node extension instead. Not a big deal, but certainly an opportunity for improvement.

File: spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb (hunk 2 above)
Comment (bbatsov) [reply spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb]: Indeed. If something doesn't generate an offense it's certainly not going to do auto-correct.

Comment (dvandersluis) [reply spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb]: Ok will make the change.

File: lib/rubocop/cop/layout/closing_heredoc_indentation.rb (hunk 3 above)
Comment (dvandersluis) [reply lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: @bbatsov I'm not exactly sure what you mean but if you provide more detail I can try to do it?

Comment (bbatsov) [reply lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: See the `str_node.rb` file, where the `heredoc?` method is defined. Seems to me the type should also go there, although as I said it's not a big thing. I was thinking of some method `heredoc_type` that returns the type as a symbol.
