### PR TITLE
[Fix #6300] Fix a false positive for `Layout/EmptyLineAfterGuardClause`

### LINKED ISSUE #6300: `Layout/EmptyLineAfterGuardClause` flags heredoc inside multi-line `if`.
## Expected behavior

No offense should occur and auto-correct should not add a newline inside the `if` statement.

## Actual behavior

An offense occurs and auto-correct adds two newlines inside the `if` statement.

## Steps to reproduce the problem

Running `rubocop` on

```ruby
def method
  if truthy
    raise <<-MSG
      This is an error.
    MSG
  end

  value
end
```

shows 

```
Inspecting 1 file
C

Offenses:

file.rb:5:1: C: Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
    MSG
^^^^^^^

1 file inspected, 1 offense detected
```

and running `rubocop --auto-correct` produces

```ruby
def method
  if truthy
    raise <<-MSG
      This is an error.
    MSG


  end

  value
end
```

and shows

```
Inspecting 1 file
C

Offenses:

file.rb:5:1: C: [Corrected] Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
    MSG
^^^^^^^
file.rb:7:1: C: [Corrected] Layout/EmptyLines: Extra blank line detected.

1 file inspected, 2 offenses detected, 2 offenses corrected
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.59.1 (using Parser 2.5.1.2, running on ruby 2.3.7 universal.x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6300.

This PR fixes a false positive for `Layout/EmptyLineAfterGuardClause` when guard clause including heredoc.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by diachini** [comment]
Confirmed this solves the issue I was experiencing on #6300 when setting my Gemfile to use:

```
  gem 'rubocop', github: 'koic/rubocop', branch: 'fix_a_false_positive_for_empty_line_after_guard_clause'
```

(No false-positive - no auto-correct adding extra lines.)

**Comment by koic** [comment]
@diachini Thanks for your quick confirmation and feedback!

File: spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb [hunk 1]
```diff
@@ -106,6 +106,36 @@ def foo
...
+  it 'registers an offense for guard clause not followed by empty line' \
+     'when guard clause including heredoc' do
+    expect_offense(<<-RUBY.strip_indent)
+      def method
+        if truthy
+          raise <<-MSG
+            This is an error.
+          MSG
+        end
+        ^^^ Add empty line after guard clause.
```
Comment (Drenmi) [inline spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb]: We're stretching the definition of *guard clause* a bit, but I would also want a space here, so I don't mind. 😬

Comment (bbatsov) [reply spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb]: I can live with this. Let's see how the users will respond to the change.
