### PR TITLE
[Fix #8205] Avoid false positive in Style/RedundantRegexpCharacterClass

### LINKED ISSUE #8205: False positive for Style/RedundantRegexpCharacterClass
When using an escaped square bracket in a character class, rubocop suggests incorrect fix.

--------

## Expected behavior

`[(\[]TM[\])]` passes the RedundantRegexpCharacterClass check.

## Actual behavior

```
C: Style/RedundantRegexpCharacterClass: Redundant single-element character class, [\] can be replaced with \.
```

## Steps to reproduce the problem

Run the check on a line with:
```
/\b ?[(\[]TM[\])]/i
```

## RuboCop version

```
0.86.0 (using Parser 2.7.1.4, rubocop-ast 0.0.3, running on ruby 2.6.6 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by owst**
If the first element of a character class was an escaped-] our pattern
was treating it as a single element classs containing a single backslash
(which is invalid, and incorrect).

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb [hunk 1]
```diff
@@ -43,6 +43,19 @@
     end
   end
 
+  context 'with a character class containing an escaped [' do
```
Comment (owst) [inline spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb:46]: This test wasn't strictly related to this PR, but I noticed we were missing it despite having the equivalent one for an escaped `]`

**Comment by koic** [comment]
Thank you for fixing!
