### PR TITLE
[Fixes #8077] Restore compatibility for Team.new

### LINKED ISSUE #8077: Undefined method `reject` for Rubocop::Cop::Registry in Rubocop::Cop::Team#roundup_relevant_cops
## Expected behavior
I am getting an exception (see below) after updating to rubocop 0.85.0 when running the [pronto-rubocop](https://github.com/prontolabs/pronto-rubocop) gem. I suspect this is due to changes in: https://github.com/rubocop-hq/rubocop/pull/8030

rubocop 0.84.0 didn't fail in this way.

## Actual behavior

```ruby
$ pronto run -c=development

# ...

Running Pronto::Rubocop
Traceback (most recent call last):
	21: from /Users/pauld/.gem/ruby/2.6.6/bin/pronto:23:in `<main>'
	20: from /Users/pauld/.gem/ruby/2.6.6/bin/pronto:23:in `load'
	19: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/bin/pronto:6:in `<top (required)>'
	18: from /Users/pauld/.gem/ruby/2.6.6/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	17: from /Users/pauld/.gem/ruby/2.6.6/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /Users/pauld/.gem/ruby/2.6.6/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /Users/pauld/.gem/ruby/2.6.6/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `run'
	13: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `chdir'
	12: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto/cli.rb:66:in `block in run'
	11: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto.rb:64:in `run'
	10: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto/runners.rb:13:in `run'
	 9: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto/runners.rb:13:in `each'
	 8: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-0.10.0/lib/pronto/runners.rb:20:in `block in run'
	 7: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-rubocop-0.10.0/lib/pronto/rubocop.rb:10:in `run'
	 6: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-rubocop-0.10.0/lib/pronto/rubocop.rb:10:in `map'
	 5: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-rubocop-0.10.0/lib/pronto/rubocop.rb:10:in `block in run'
	 4: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-rubocop-0.10.0/lib/pronto/rubocop/patch_cop.rb:12:in `messages'
	 3: from /Users/pauld/.gem/ruby/2.6.6/gems/pronto-rubocop-0.10.0/lib/pronto/rubocop/patch_cop.rb:44:in `offences'
	 2: from /Users/pauld/.gem/ruby/2.6.6/gems/rubocop-0.85.0/lib/rubocop/cop/team.rb:67:in `inspect_file'
	 1: from /Users/pauld/.gem/ruby/2.6.6/gems/rubocop-0.85.0/lib/rubocop/cop/team.rb:116:in `offenses'
/Users/pauld/.gem/ruby/2.6.6/gems/rubocop-0.85.0/lib/rubocop/cop/team.rb:148:in `roundup_relevant_cops': undefined method `reject' for #<RuboCop::Cop::Registry:0x00007fae6d7629b0> (NoMethodError)
```

## Steps to reproduce the problem

From what I can tell, any pronto run that includes pronto-rubocop will cause this failure... will update if i can find other ways to reproduce.

## RuboCop version
```
0.85.0 (using Parser 2.7.1.3, rubocop-ast 0.0.3, running on ruby 2.6.6 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by marcandre**

### CODE REVIEW

File: lib/rubocop/cop/team.rb [hunk 1]
```diff
@@ -31,6 +31,14 @@ def initialize(cops, config = nil, options = nil)
         validate_config
       end
 
+      # @return [Team]
+      def self.new(cop_or_classes, config, options = nil)
+        # Support v0 api:
+        return mobilize(cop_or_classes, config, options) if cop_or_classes.first.is_a?(Class)
```
Comment (darrenterhune) [inline lib/rubocop/cop/team.rb:37]: @marcandre thanks for ripping this out so quickly. However after upgrading to `0.85.0` and trying your changes, I locally I'm getting:

```
NoMethodError: undefined method `first' for <RuboCop::Cop::Registry:0x00007f939c949dc8>
```

This is with `erb_lint` which started out here https://github.com/rubocop-hq/rubocop/issues/8077

```
---
linters:
  ErbSafety:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
```

If I remove `Rubocop` from the above it runs fine.

Here's what I get from the arg `cop_or_classes` https://gist.github.com/darrenterhune/aa0b9b3a4886d4708b6c41e76cad4d4f

Comment (marcandre) [reply lib/rubocop/cop/team.rb:37]: Indeed, my patch relies on my previous patch #8079: `include Enumerable` will define `first` for `Registry`.
