### PR TITLE
DidYouMean::SpellChecker may not be available

### LINKED ISSUE #7979: uninitialized constant DidYouMean::SpellChecker
TLDR: In c92a591, the name similarity module started using `DidYouMean::SpellChecker` but this gem is not explicitly listed as a dependency.

--------

## Expected behavior

Rubocop does not crash. We get an offense such as:
`Unnecessary disabling of Lint/SuperCoolCop (did you mean Layout/SuperCoolCop?)`

## Actual behavior

We see the following error when running Rubocop:
```
Uninitialized constant DidYouMean::SpellChecker
--
  | /var/www/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:18:in `find_similar_names'
  | /var/www/vendor/bundle/ruby/2.6.0/gems/rubocop-0.83.0/lib/rubocop/name_similarity.rb:9:in `find_similar_name'
```

## Steps to reproduce the problem

Add a magic comment to disable a cop that does not actually exist. E.g. `# rubocop:disable Lint/SuperCoolCop`

## RuboCop version

```
$ bundle exec rubocop -V
0.83.0 (using Parser 2.7.1.2, running on ruby 2.6.6 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by bquorning**
Fixes #7979 

In #7979 it was reported that `DidYouMean::SpellChecker` may not always be available. We can work around that by doing a feature check before using the `SpellChecker` class.

I did not add any tests.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/name_similarity.rb [hunk 1]
```diff
@@ -12,6 +12,8 @@ def find_similar_name(target_name, names)
     end
 
     def find_similar_names(target_name, names)
+      return [] unless defined?(DidYouMean::SpellChecker)
```
Comment (koic) [inline lib/rubocop/name_similarity.rb:15]: It would be helpful to link a reference (#8143) to the reason for the workaround :-)

Comment (bquorning) [reply lib/rubocop/name_similarity.rb:15]: Good point. I will add a commit.

**Comment by bbatsov** [comment]
Thanks!
