### PR TITLE
[Fix #9083] Fix `Style/RedundantArgument` cop raising offense for more than one argument

### LINKED ISSUE #9083: `Style/RedundantArgument` report for cases like `foo.split(' ', 2)`
Seems `Style/RedundantArgument` didn't know about second argument [`limit`](https://ruby-doc.org/core-2.7.0/String.html#method-i-split) for `split` method

--------

## Steps to reproduce the problem

1. Create simple `test.rb` script with content:
```
foo = 'a b c d e'
bar = foo.split(' ', 2)
puts(bar[0] == 'a')
puts(bar[1] == 'b c d e')
```
2. Run rubocop on it and get:
```
rubocop -A test.rb 
Inspecting 1 file
C

Offenses:

test.rb:2:7: C: Style/RedundantArgument: Argument ' ' is redundant because it is implied by default.
bar = foo.split(' ', 2)
      ^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

Seems in that case this cop should just ignore it, if limit is set

## RuboCop version
```
rubocop -V
1.4.0 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.7.2 x86_64-linux)
  - rubocop-performance 1.9.0
  - rubocop-rspec 2.0.0

```

### PR DESCRIPTION
**Pull request by tejasbubane**
Also
* Add check for explicit receiver must be present.
* Refactor tests for the cop.

Closes #9083

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_argument.rb [hunk 1]
```diff
@@ -40,6 +40,7 @@ class RedundantArgument < Cop
         MSG = 'Argument %<arg>s is redundant because it is implied by default.'
 
         def on_send(node)
+          return if node.arguments.count != 1
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_argument.rb:43]: I think you should also return directly if there's no explicit receiver. I don't see a check for this currently.

Comment (tejasbubane) [reply lib/rubocop/cop/style/redundant_argument.rb:44]: added

**Comment by bbatsov** [comment]
Thanks!
