### PR TITLE
[Fix #6751] Prevent Style/OneLineConditional from breaking on retry and break keywords

### LINKED ISSUE #6751: Style/OneLineConditional auto-correct crashes when conditional body contains certain keywords
## Expected behavior

Running `Style/OneLineConditional` on code that contains a conditional with a keyword such as `retry`, `raise`, or `break` in one of its branches with auto-correct enabled doesn't cause Rubocop to crash.

## Actual behavior

Running `Style/OneLineConditional` on code that contains a conditional with a keyword such as `retry`, `raise`, or `break` in one of its branches with auto-correct enabled causes Rubocop to crash.

## Steps to reproduce the problem

This is a problem regardless of whether the keyword occurs in the `if` or `else` branch.

```
[21:16:34] ~/Documents  ➜ cat foo.rb
if true then retry else 7 end
[21:17:24] ~/Documents  ➜ rubocop -a --only Style/OneLineConditional
Inspecting 2 files


0 files inspected, no offenses detected
undefined method `prefix_not?' for s(:retry):RuboCop::AST::Node
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/style/one_line_conditional.rb:90:in `keyword_with_changed_precedence?'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/style/one_line_conditional.rb:78:in `requires_parentheses?'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/style/one_line_conditional.rb:70:in `expr_replacement'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/style/one_line_conditional.rb:65:in `to_ternary'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/style/one_line_conditional.rb:50:in `replacement'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/style/one_line_conditional.rb:39:in `block in autocorrect'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/corrector.rb:64:in `block (2 levels) in rewrite'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/parser-2.5.3.0/lib/parser/source/tree_rewriter.rb:220:in `transaction'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/corrector.rb:63:in `block in rewrite'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/corrector.rb:61:in `each'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/corrector.rb:61:in `rewrite'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:128:in `autocorrect_all_cops'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:72:in `autocorrect'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:100:in `block in offenses'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:117:in `investigate'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:96:in `offenses'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:280:in `inspect_file'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:227:in `block in do_inspection_loop'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:259:in `block in iterate_until_no_changes'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `loop'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `iterate_until_no_changes'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:223:in `do_inspection_loop'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:126:in `block in file_offenses'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:144:in `file_offense_cache'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:124:in `file_offenses'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:112:in `process_file'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:89:in `block in each_inspected_file'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `reduce'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:76:in `inspect_files'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:48:in `run'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:174:in `execute_runner'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:75:in `execute_runners'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:47:in `run'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/exe/rubocop:13:in `block in <top (required)>'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/pat/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rubocop-0.63.1/exe/rubocop:12:in `<top (required)>'
/Users/pat/.rbenv/versions/2.6.0/bin/rubocop:23:in `load'
/Users/pat/.rbenv/versions/2.6.0/bin/rubocop:23:in `<main>'
```

## RuboCop version

```
[21:17:29] ~/Documents  ➜ rubocop -V
0.63.1 (using Parser 2.5.3.0, running on ruby 2.6.0 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by Drenmi**
This cop would break on code like:

```ruby
if true then retry else 7 end
if true then break else 7 end
```

This was happening because the `retry` node was expected to be decorated with a decorator that includes the `MethodDispatchNode` extension.

This change adds a `RetryNode`- and a `BreakNode` decorator.

It also fixes an issue where superfluous parentheses were added when the keyword has no arguments:

**Before:**

```ruby
true ? (retry) : 7
```

**After:**

```ruby
true ? retry : 7
```

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [X] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/ast/node/retry_node.rb [hunk 1]
```diff
@@ -0,0 +1,12 @@
+# frozen_string_literal: true
+
+module RuboCop
+  module AST
+    # A node extension for `retry` nodes. This will be used in place of a
+    # plain node when the builder constructs the AST, making its methods
+    # available to all `retry` nodes within RuboCop.
+    class RetryNode < Node
+      include MethodDispatchNode
+    end
```
Comment (koic) [inline lib/rubocop/ast/node/retry_node.rb]: This looks like a wonderful approach 🌟 

However issue #6751 also reports on `raise` and `break`.  `raise` seems to work without errors, but `break` seems to be an error. 

## `raise` (no offenses)

```console
% cat raise.rb
if true then raise else 7 end
% rubocop -a --only Style/OneLineConditional raise.rb
Inspecting 1 file
C

Offenses:

raise.rb:1:1: C: [Corrected] Style/OneLineConditional: Favor the ternary operator (?:) over if/then/else/end constructs.
if true then raise else 7 end
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
% g diff raise.rb
diff --git a/raise.rb b/raise.rb
index 519c3b0..69ac23b 100644
--- a/raise.rb
+++ b/raise.rb
@@ -1 +1 @@
-if true then raise else 7 end
+true ? raise : 7
```

## `break` (offense detected)

```console
% cat break.rb
if true then break else 7 end
% rubocop -a --only Style/OneLineConditional break.rb
Inspecting 1 file


0 files inspected, no offenses detected
undefined method `prefix_not?' for s(:break):RuboCop::AST::Node
/Users/koic/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rubocop-0.64.0/lib/rubocop/cop/style/one_line_conditional.rb:92:in `keyword_with_cha
nged_precedence?'
/Users/koic/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rubocop-0.64.0/lib/rubocop/cop/style/one_line_conditional.rb:80:in `requires_parenth
eses?'
```

So I think that it would be better to also make `BreakNode`. WDYT?

File: spec/rubocop/cop/style/one_line_conditional_spec.rb [hunk 2]
```diff
@@ -108,4 +108,11 @@
     corrected = autocorrect_source('if 0 + 0 then 1 + 1 else 2 + 2 end')
     expect(corrected).to eq('0 + 0 ? 1 + 1 : 2 + 2')
   end
+
+  it 'does not break when one of the branches contains a retry keyword' do
+    expect_offense(<<-RUBY.strip_indent)
+      if true then retry else 7 end
+      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Favor the ternary operator (`?:`) over `if/then/else/end` constructs.
+    RUBY
```
Comment (koic) [inline spec/rubocop/cop/style/one_line_conditional_spec.rb]: It seems that `retry` is surrounded by parentheses when using auto-correct.

```diff
-if true then retry else 7 end
+true ? (retry) : 7
```

I think that parentheses are unnecessary if possible :-)

File: lib/rubocop/ast/node/retry_node.rb (hunk 1 above)
Comment (Drenmi) [reply lib/rubocop/ast/node/retry_node.rb]: > So I think that it would be better to also make `BreakNode`. WDYT?

👍

File: spec/rubocop/cop/style/one_line_conditional_spec.rb (hunk 2 above)
Comment (Drenmi) [reply spec/rubocop/cop/style/one_line_conditional_spec.rb]: > I think that parentheses are unnecessary if possible :-)

Thanks for a great review! I will have a look. 🙂

**Comment by Drenmi** [comment]
@koic Thanks for a stellar review! ⭐️ I have addressed all your comments in the PR. I will be on holiday from today until Sunday, so feel free to merge if you're okay with the additions. 🙇

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,7 @@
 ### Bug fixes
 
 * [#6748](https://github.com/rubocop-hq/rubocop/issues/6748): Fix `Style/RaiseArgs` auto-correction breaking in contexts that require parentheses. ([@drenmi][])
+* [#6751](https://github.com/rubocop-hq/rubocop/issues/6751): Prevent `Style/OneLineConditional` from breaking on `retry` keyword. ([@drenmi][])
```
Comment (koic) [inline CHANGELOG.md]: I think it would be good to have a mention about `break` keyword too :-)
