### PR TITLE
[Fix #6956] Prevent auto-correct confliction of `Lint/Lambda` and `Lint/UnusedBlockArgument`

### LINKED ISSUE #6956: Style/Lambda with unused argument bug
### Context

When using `--auto-correct` with a "stabby lambda" function where arguments are unused results in syntactically incorrect code:

```ruby
c = -> event do
  puts 'Hello world'
end
```

Is autocorrected to the following:

```ruby
c = lambda(_) do |_event|
  puts 'Hello world'
end
```

Which returns the following error when executed:

```
test.rb:3:in `<main>': undefined local variable or method `_' for main:Object (NameError)
```

--------

## Expected behavior

Should not inject `_` arguments into lambda e.g. `lambda(_)` this is not allowed in Ruby. The result should be the following code:

```ruby
c = lambda do |_event|
  puts 'Hello world'
end
```

## Actual behavior

Inserts `_` as an argument to lambda function e.g. `lambda(_)`

## Steps to reproduce the problem

1. Insert the example code in the above context into a file.
2. Run `rubocop --auto-correct` on the file.
3. Try executing the formatted code, it will not work.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.4.5 x86_64-darwin18)
```

## Ruby version

```
$ ruby -v
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6956.

This PR prevents auto-correct confliction of `Lint/Lambda` and `Lint/UnusedBlockArgument`.

The following is the reproduction procedure.

```ruby
# example.rb
c = -> event do
  puts 'Hello world'
end
```

```console
% rubocop example.rb -a --only Style/Lambda,Lint/UnusedBlockArgument
```

## Before

A reserved word `lambda` is broken.

```diff
% git diff
diff --git a/example.rb b/example.rb
index 3445c6f..b8e24f4 100644
--- a/example.rb
+++ b/example.rb
@@ -1,3 +1,3 @@
-c = -> event do
+c = lambda_ do |_event|
   puts 'Hello world'
 end
```

## After

It will be a valid code.

```diff
% git diff
diff --git a/example.rb b/example.rb
index 3445c6f..9c22b37 100644
--- a/example.rb
+++ b/example.rb
@@ -1,3 +1,3 @@
-c = -> event do
+c = lambda do |_event|
   puts 'Hello world'
 end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/correctors/unused_arg_corrector.rb [hunk 1]
```diff
@@ -15,14 +15,26 @@ def correct(processed_source, node)
...
+                                node.source.gsub(/\A\*+/, '')
+                              end
+              corrector.replace(node.loc.name, "_#{variable_name}")
             end
-          else
-            ->(corrector) { corrector.insert_before(node.loc.name, '_') }
+          end
+        end
+
+        def correct_for_blockarg_type(node)
```
Comment (koic) [inline lib/rubocop/cop/correctors/unused_arg_corrector.rb]: :memo: I extracted to the method because it was warned by `Metrics` cops.

**Comment by bbatsov** [comment]
Thanks!
