### PR TITLE
[Fix #9304] Do not register offense for `Style/ExplicitBlockArgument` when the `yield` arguments are not an exact match with the block arguments.

### LINKED ISSUE #9304: Style/ExplicitBlockArgument autocorrect doesn't take into if it's yielding the same args
Given

```ruby
def each
  each_row do |row, index|
    yield row
  end
end
```

## Expected behaviour

`rubocop -A` should at worst do nothing.

## Actual behavior

```ruby
def each(&block)
  each_row(&block)
end
```

This now populates the 2nd argument of `each`, so it's not equivalent.

## Steps to reproduce the problem

Run `rubocop -A` on:

```ruby
def each_row
  9.times.each_with_index do |row, index|
    yield row, index
  end
end

def each
  each_row do |row, index|
    yield row
  end
end
```

## RuboCop version

```
$ bundle exec rubocop -V
0.89.1 (using Parser 2.7.2.0, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
When the block arguments and yield arguments are not an exact match, no offense is raised. Fixes #9304.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/explicit_block_argument.rb [hunk 1]
```diff
@@ -6,6 +6,9 @@ module Style
       # This cop enforces the use of explicit block argument to avoid writing
       # block literal that just passes its arguments to another block.
       #
+      # NOTE: This cop only registers an offense if the block args match the
```
Comment (bbatsov) [inline lib/rubocop/cop/style/explicit_block_argument.rb:9]: Does this change make the cop safe?

Comment (dvandersluis) [reply lib/rubocop/cop/style/explicit_block_argument.rb:9]: I think so! There might be a case I'm not thinking about though.

Comment (bbatsov) [reply lib/rubocop/cop/style/explicit_block_argument.rb:9]: Well, I guess you can change `Safe` to `true` and we'll see if we're lucky. :-)

Comment (dvandersluis) [reply lib/rubocop/cop/style/explicit_block_argument.rb:9]: Updated!

File: config/default.yml [hunk 2]
```diff
@@ -3219,9 +3219,9 @@ Style/ExplicitBlockArgument:
                   that just passes its arguments to another block.
   StyleGuide: '#block-argument'
   Enabled: true
-  # May change the yielding arity.
-  Safe: false
+  Safe: true
```
Comment (koic) [inline config/default.yml:3222]: Safe is true by default, so it can be omitted.

```suggestion
```

Comment (dvandersluis) [reply config/default.yml]: 🤦 Fixed now, thanks.

**Comment by dvandersluis** [comment]
@bbatsov @koic any other changes needed here?

**Comment by dvandersluis** [comment]
@bbatsov I think we can include this in the bug fix release, what do you think?

**Comment by bbatsov** [comment]
Consider it included! 😄
