### PR TITLE
[Fix #7586] Fix infinite loop in Style/FrozenStringLiteralComment

### LINKED ISSUE #7586: Infinite loop in Style/FrozenStringLiteralComment
I just tried applying Rubocop autocorrect rules on one of old applications and I got infinite loop in ` Style/FrozenStringLiteralComment` rule in a script. The problematic code is below. I know it's a bit incorrect usage of `coding` magic comment but the script wasn't written by me. On the other hand I consider this error as a bug in this case though. 
 
## Expected behavior

Autocorrect is without infinite loop

## Actual behavior

Infinite loop detected in the code below

## Steps to reproduce the problem

```
#! bin/rails runner

# coding: utf-8

puts 'DEPRECATED!'
exit
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.78.0 (using Parser 2.6.5.0, running on ruby 2.6.5 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by pirj**
Fixes #7586

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb [hunk 1]
```diff
@@ -164,120 +249,21 @@
...
-          #!/usr/bin/env ruby
-        RUBY
-
-        expect(new_source).to eq(<<~RUBY)
-          #!/usr/bin/env ruby
-          # frozen_string_literal: true
-        RUBY
-      end
+    it 'registers an offence for an extra first empty line' do
+      pending 'There is a flaw that skips adding caret symbol in this case' \
```
Comment (pirj) [inline spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb]: Couldn't find a quick way around it. What's even stranger, can't find a difference in `loc` being added in case when caret is added or not.

**Comment by bbatsov** [comment]
Excellent work! I guess we can handle the pending spec down the road.
