### PR TITLE
[Fix-7777-7776]: Generate valid code if comment exists before closing brace

### LINKED ISSUE #7777: Rubocop places commas into comments, generating invalid ruby code
When formatting the following code, rubocop will generate invalid ruby:

```ruby
class Bar
  def initialize(*args)
  end
end

class Foo < Bar
  def initialize
    super(
      'firstKey' => [ 'value a', #description1
                      'value b' #description2
      ],
      'secondKey' => 'Bar'
    )
  end
end
```

## Expected behavior

Not to generate invalid ruby code

## Actual behavior

Invalid ruby code is created due to incorrectly handling the comment and placing a comma on the comment line:

```ruby
class Bar
  def initialize(*args)
  end
end

class Foo < Bar
  def initialize
    super(
      'firstKey' => ['value a', # description1
                      'value b'] # description2,
      'secondKey' => 'Bar'
    )
  end
end
```

## Steps to reproduce the problem

1. Create new ruby file
2. add original code snippet
3. bundle exec rubocop  -x --safe-auto-correct new_file.rb
4. Run again, verify invalid ruby code has been generated

## RuboCop version

```
$ [bundle exec] rubocop -V
0.80.0 (using Parser 2.7.0.2, running on ruby 2.6.5 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by shekhar-patil**
closes #7777 and #7776 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb [hunk 1]
```diff
@@ -42,8 +42,30 @@ def correct_next_line_brace(corrector)
...
+        end
+      end
+
+      def select_content_to_be_inserted_after_last_element(corrector, node)
+        range = range_between(
+          node.loc.end.begin_pos,
+          range_by_whole_lines(node.loc.expression).end.end_pos
         )
+
+        corrector.remove(range)
```
Comment (jonas054) [inline lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb:67]: If I remove this line, all tests still pass. I suspect that this is because the call to `remove` is not needed, rather that being related to poor test coverage. But I don't see why it's not needed. :confused: 

Anyway, it's better if the method only selects a certain source range, like its name says, and not does anything else (single responsibility principle).

Comment (shekhar-patil) [reply lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb]: @jonas054 , Thanks for reviewing, Yes, The mentioned line is needed. I wrote the wrong test case which I have corrected now. Please review now.

**Comment by bbatsov** [comment]
Thanks!
