### PR TITLE
[Fix #8118] fix autocorrect for redundant cop enable directive

### LINKED ISSUE #8118: Redundant enable/disable autocorrection
```
# rubocop:enable NotActually/Needed,IAm/Needed

# gets corrected to

# rubocop:enableIAm/Needed
```
(Note: no space after "," => no space after "enable")

### PR DESCRIPTION
**Pull request by lxxxvi**
If the redundant cop enable directive contains a list of cops, and that list is comma separated without a white-space after the commas, the autocorrection returned a wrong output.

Before

```ruby
# rubocop:enable NotActually/Needed,IAm/Needed

# gets corrected to

# rubocop:enableIAm/Needed
```

This commit fixes that behaviour and adds a corresponding test.

After

```ruby
# rubocop:enable NotActually/Needed,IAm/Needed

# gets corrected to

# rubocop:enable IAm/Needed
```

---

Hello RuboCop Team 👋 

This is the simplest way I could come up with to fix that issue (#8118) without breaking other tests. I'm open to suggestions and/or changes.

### CODE REVIEW

File: lib/rubocop/cop/lint/redundant_cop_enable_directive.rb [hunk 1]
```diff
@@ -82,14 +92,11 @@ def range_with_comma(comment, name)
...
-            elsif source[end_pos] == ','
-              :after
-            else
-              :none
-            end
+          comma_pos = find_comma_position(source, begin_pos, end_pos)
+
+          # If the list of cops is comma-separated, but without a white-space after the comma,
+          # we should **not** remove the prepending white-space, thus begin_pos += 1
+          begin_pos += 1 if comma_pos == :after && source[end_pos + 1] != ' '
```
Comment (marcandre) [inline lib/rubocop/cop/lint/redundant_cop_enable_directive.rb:99]: I think this logic should be moved into `range_to_remove`, no?

Comment (lxxxvi) [reply lib/rubocop/cop/lint/redundant_cop_enable_directive.rb:99]: @marcandre Thanks for reviewing. 
I think it doesn't matter much if the logic is here or in `range_to_remove`. We'd have to pass the variable `source` as an additional argument though, that's what made me put it here.
`source` is used to check if the character after the comma is a white space or not.

Comment (marcandre) [reply lib/rubocop/cop/lint/redundant_cop_enable_directive.rb:99]: The source is always available to cops, I'm not sure why it is being passed around. Actually I feel the cop is not particularly well written, using indices instead of `::Parser::Source::Range` (that also holds the source). If you are up for it, this cop would benefit from some refactoring, with `cop_name_indention => cop_name_range` for example. But at the least, please put that logic in `range_to_remove` as it is the responsibility of that method to calculate the range to be removed...

Comment (lxxxvi) [reply lib/rubocop/cop/lint/redundant_cop_enable_directive.rb]: @marcandre 👍 Fine for me, I've put the logic to `range_to_remove` as you indicated.
Also, I can give it a try to refactor the cop in the next days.

Comment (lxxxvi) [reply lib/rubocop/cop/lint/redundant_cop_enable_directive.rb]: @marcandre After moving the logic to `range_to_remove` it started to complain, of course, that the `Metrics/AbcSize` was too high. 🙈 Had to extract some logic once more.

Comment (marcandre) [reply lib/rubocop/cop/lint/redundant_cop_enable_directive.rb]: I'm wondering if combining `find_comma_position` and `range_to_remove` into one wouldn't make the whole thing simpler? Instead of `:after`, call a method `range_with_comma_after`, etc.? Otherwise put the code back in `range_to_remove` and add a `todo` for `AbcSize`; that metric will change anyways...

**Comment by lxxxvi** [comment]
@marcandre Thanks for the feedback again. 
I tried to apply the changes you pointed out, I think the result is bit cleaner now. We got rid of `find_comma_position`, instead we have 2 new methods `range_with_comma_before` and `range_with_comma_after` that handle the corresponding cases.
What do you think?

**Comment by lxxxvi** [comment]
Btw, I was looking into refactoring some stuff, and discovered some odd behaviours if the commas are "improperly" surrounded with whitespace, example:

```ruby
# rubocop:disable Layout/LineLength  , Lint/UselessAssignment ,  Lint/Debugger
x = 1
# rubocop:enable Layout/LineLength ,   Lint/Debugger  , Lint/UselessAssignment
```

In this example only `Lint/UselessAssignment` is valid to be disabled/enabled again, the other two are _redundant_.
Here's what we get.

```
example.rb:1:1: C: Style/FrozenStringLiteralComment: Missing frozen string literal comment.
# rubocop:disable Layout/LineLength  , Lint/UselessAssignment ,  Lint/Debugger
^
example.rb:1:19: W: Lint/RedundantCopDisableDirective: Unnecessary disabling of Layout/LineLength.
# rubocop:disable Layout/LineLength  , Lint/UselessAssignment ,  Lint/Debugger
                  ^^^^^^^^^^^^^^^^^
example.rb:1:66: W: Lint/RedundantCopDisableDirective: Unnecessary disabling of Lint/Debugger.
# rubocop:disable Layout/LineLength  , Lint/UselessAssignment ,  Lint/Debugger
                                                                 ^^^^^^^^^^^^^
example.rb:3:18: W: Lint/RedundantCopEnableDirective: Unnecessary enabling of Layout/LineLength .
# rubocop:enable Layout/LineLength ,   Lint/Debugger  , Lint/UselessAssignment
                 ^^^^^^^^^^^^^^^^^^
example.rb:3:40: W: Lint/RedundantCopEnableDirective: Unnecessary enabling of Lint/Debugger  .
# rubocop:enable Layout/LineLength ,   Lint/Debugger  , Lint/UselessAssignment
                                       ^^^^^^^^^^^^^^^
example.rb:3:57: W: Lint/RedundantCopEnableDirective: Unnecessary enabling of Lint/UselessAssignment.
# rubocop:enable Layout/LineLength ,   Lint/Debugger  , Lint/UselessAssignment
                                                        ^^^^^^^^^^^^^^^^^^^^^^
```

I think the first three offenses (`Style/FrozenStringLiteralComment` and `Lint/RedundantCopDisableDirective`) are perfectly fine.
However, the last three look odd:
Number 4 and 5 somehow include the blanks after the cops' names (?).
Number 6 is a wrong offense, no?

Should I open a new issue for this?

**Comment by marcandre** [comment]
> Number 4 and 5 somehow include the blanks after the cops' names (?).

Agreed, that would ideally be fixed

> Number 6 is a wrong offense, no?

Looks like it. Is it related to the extra spacing? If not, probably belongs in a different issue.

**Comment by bbatsov** [comment]
I'm closing this PR due to no recent activity. Feel free to re-open it if you ever come back to it.

**Comment by marcandre** [comment]
I'm merging this. RuboCop is better with it than without.

**Comment by marcandre** [comment]
Sorry, I should have squashed merge though.
