### PR TITLE
[Fix #6808] Prevent false positive in Naming/ConstantName when assigning frozen range

### LINKED ISSUE #6808: Naming/ConstantName ignores constants with frozen ranges
The issue is with the `Naming/ConstantName` cop and it's the same as this ticket:
https://github.com/rubocop-hq/rubocop/issues/5155

The issue was reportedly fixed in https://github.com/rubocop-hq/rubocop/pull/5157, but it seems like it's still affecting frozen Range constants.

**NOTE: this only applies when the constant value is a range (see example below).**

--------

## Expected behavior

Rubocop should detect `Naming/ConstantName` offences when a constant Range is frozen.

## Actual behavior

Rubocop doesn't detect `Naming/ConstantName` offences when a constant Range is frozen.

## Steps to reproduce the problem

Run latest version of Rubocop on code having the following line:

```ruby
MyInvalidConstantName = (400...500).freeze
```

## RuboCop version

This was tested with all rubocop version from 0.58.0 to 0.65 on macOS Mojave.
ALL versions had the same issue.
Below is only the latest version.

```
$ [bundle exec] rubocop -V
0.65.0 (using Parser 2.6.0.0, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by Drenmi**
This cop would fail to report offenses on code like:

```
FooBar = (1..5).freeze
```

This change fixes that.

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [X] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/constant_name.rb [hunk 1]
```diff
@@ -60,9 +60,14 @@ def allowed_assignment?(value)
 
         def allowed_method_call_on_rhs?(node)
           node && node.send_type? &&
-            (node.receiver.nil? || !node.receiver.literal?)
+            (node.receiver.nil? || !literal_receiver?(node))
         end
 
+        def_node_matcher :literal_receiver?, <<-PATTERN
```
Comment (Drenmi) [inline lib/rubocop/cop/naming/constant_name.rb]: I tried to make this pattern include all logic in `#allowed_method_call_on_rhs?`, but got some weird non-matches on the new case that will require me to debug the node pattern a bit.

File: spec/rubocop/cop/naming/constant_name_spec.rb [hunk 2]
```diff
@@ -12,6 +12,14 @@
 
   it 'registers an offense for camel case in const name' \
      'when using frozen object assignment' do
```
Comment (bquorning) [inline spec/rubocop/cop/naming/constant_name_spec.rb]: It looks like the `object` and `range` descriptions got switched around.

Comment (Drenmi) [reply spec/rubocop/cop/naming/constant_name_spec.rb]: Good catch! 🙂

**Comment by Drenmi** [comment]
Could you help review this please, @koic? 🙇

File: CHANGELOG.md [hunk 3]
```diff
@@ -13,6 +13,8 @@
 * [#6801](https://github.com/rubocop-hq/rubocop/pull/6801): Fix auto-correction for `Style/Lambda` with no-space argument. ([@pocke][])
 * [#6804](https://github.com/rubocop-hq/rubocop/pull/6804): Fix auto-correction of `Style/NumericLiterals` on numeric literal with exponent. ([@pocke][])
 * [#6800](https://github.com/rubocop-hq/rubocop/issues/6800): Fix an incorrect auto-correct for `Rails/Validation` when method arguments are enclosed in parentheses. ([@koic][])
+* [#6808](https://github.com/rubocop-hq/rubocop/issues/6808): Prevent false positive in `Naming/ConstantName` when assigning a frozen range. ([@drenmi][])
+
```
Comment (koic) [inline CHANGELOG.md]: This has unnecessary blank line :-) The change to the codes looks good. Thanks!

Comment (Drenmi) [reply CHANGELOG.md]: Ugh. Git auto-merge ... 😂

**Comment by koic** [comment]
Thank you!
