### PR TITLE
[Fix #5973] Add Style/IpAddresses cop

### LINKED ISSUE #5973: Proposed Cop: No hardcoded IP Addresses
I'd like to propose an IP address cop. I don't care if it's disabled by default. If people like the idea, I'm totally up for writing the code for it myself. Should work for IPv4 and IPv6 addresses. Perhaps if we get fancy with it there could be some way to allow one type of IP address, but not the other (although I can't think of a real use case). 

IP addresses being fixed in your code is generally a quick way to make something that's non-reusable, brittle, requires a new commit/deploy when the IP changes instead of ENV configuration/relaunch, and to have a failed deploy because something changed. 

This cop would raise a Rubocop failure if it finds any valid IPv4 or IPv6 address in the code.

### PR DESCRIPTION
**Pull request by dvandersluis**
Added a cop for #5973. It registers an offense if a string is found that is a valid IP address. It allows for strings to be whitelisted if desired (it only includes `::` by default, which is found a whole bunch of times in the rubocop code). It does not match strings that contain an IP address as a substring.

I tried to implement this in a way that made sense to me, but please let me know if there are any suggestions, particularly re naming or namespace I chose.

I also have this set to disabled by default, but am happy to change it if desired.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/ip_addresses.rb [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        MSG = 'Do not hardcode IP addresses.'.freeze
+
+        def offense?(node)
+          contents = node.source[1...-1]
+
+          return false if whitelist.include?(contents.downcase)
+
+          # To try to avoid doing two regex checks on every string,
+          # shortcut out if the string does not look like an IP address
+          return false unless could_be_ip?(contents)
```
Comment (dvandersluis) [inline lib/rubocop/cop/style/ip_addresses.rb]: I am assuming that a codebase would have a lot of strings, which means that rubocop would end up doing a lot of regex matching. In order to try to prevent that, I am doing some basic checks that the string kind of looks like an IP and short-circuiting if not.

I'm not 100% sure this is necessary or the right way to go about this, so I'd love feedback here.

File: lib/rubocop/cop/style/ip_addresses.rb [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+          starts_with_hex_or_colon?(str)
+        end
+
+        def too_long?(str)
+          str.size > IPV6_MAX_SIZE
+        end
+
+        def starts_with_hex_or_colon?(str)
+          first_char = str[0].ord
+          (48..58).cover?(first_char) || (65..70).cover?(first_char) || (97..102).cover?(first_char)
```
Comment (dvandersluis) [inline lib/rubocop/cop/style/ip_addresses.rb]: A valid IP address can only possibly start with a hexadecimal character or a colon (if IPv6).

I benchmarked a ton of potential methods for determining the quickest way to do this check, and this was the best way I could find to check for `/[a-fA-F0-9:]/`. Doing a regex match is actually slightly quicker if the character is not a match, but this was the best overall (for the best, average and worst case match).

File: lib/rubocop/cop/style/ip_addresses.rb [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+        end
+
+        def too_long?(str)
+          str.size > IPV6_MAX_SIZE
+        end
+
+        def starts_with_hex_or_colon?(str)
+          first_char = str[0].ord
+          (48..58).cover?(first_char) || (65..70).cover?(first_char) ||
+            (97..102).cover?(first_char)
```
Comment (dvandersluis) [inline lib/rubocop/cop/style/ip_addresses.rb]: A valid IP address can only possibly start with a hexadecimal character or a colon (if IPv6).

I benchmarked a ton of potential methods for determining the quickest way to do this check, and this was the best way I could find to check for `/[a-fA-F0-9:]/`. Doing a regex match is actually slightly quicker if the character is not a match, but this was the best overall (for the best, average and worst case match).

File: lib/rubocop/cop/style/ip_addresses.rb [hunk 4]
```diff
@@ -0,0 +1,63 @@
+# frozen_string_literal: true
+
+require 'resolv'
+
+module RuboCop
+  module Cop
+    module Style
+      # Checks for IP addresses in strings
```
Comment (mikegee) [inline lib/rubocop/cop/style/ip_addresses.rb]: Could you please justify this cop here for the manual? Your issue said:

> IP addresses being fixed in your code is generally a quick way to make something that's non-reusable, brittle, requires a new commit/deploy when the IP changes instead of ENV configuration/relaunch, and to have a failed deploy because something changed.

Comment (dvandersluis) [reply lib/rubocop/cop/style/ip_addresses.rb]: It's not actually my issue I just thought I could tackle it. Should I just put that into the comments?

Comment (mikegee) [reply lib/rubocop/cop/style/ip_addresses.rb]: Oops. I didn't compare usernames. Sorry about that.

I think it could be rephrased for simplicity. @tibbon, would you like to help rephrase this?

Comment (dvandersluis) [reply lib/rubocop/cop/style/ip_addresses.rb]: I edited it down and amended the comment.

File: lib/rubocop/cop/style/ip_addresses.rb [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+require 'resolv'
+
+module RuboCop
+  module Cop
+    module Style
+      # This cop checks for hardcoded IP addresses, which can make code
+      # brittle. IP addresses are likely to need to be changed when code
+      # is deployed to a different server or environment, which may break
+      # a deployment if forgotten. Prefer setting IP addresses in ENV or
+      # other configuration.
```
Comment (bbatsov) [inline lib/rubocop/cop/style/ip_addresses.rb]: This should have some good and bad code examples.

Comment (dvandersluis) [reply lib/rubocop/cop/style/ip_addresses.rb]: Sure - how do I show a good code example for the lack of something?

Comment (dvandersluis) [reply lib/rubocop/cop/style/ip_addresses.rb]: Actually I think I have an idea

Comment (bbatsov) [reply lib/rubocop/cop/style/ip_addresses.rb]: You can just use imaginary config API (e.g. some reference to a config module or env variables).

Comment (dvandersluis) [reply lib/rubocop/cop/style/ip_addresses.rb]: Updated to add examples.

**Comment by tibbon** [comment]
Thank you @dvandersluis !!! 🥇
