### PR TITLE
[Fix #6264] Fix an incorrect autocorrect for `Layout/EmptyLineAfterGuardClause`

### LINKED ISSUE #6264: Layout/EmptyLineAfterGuardClause wrongly inspects lines with heredocs
Rubocop `Layout/EmptyLineAfterGuardClause` auto-correct inserts a new line right after the guard clause line but for case of using heredoc it should insert an empty line after the end of heredoc

--------

## Expected behavior

auto-correct mode produces code like this:

```ruby
raise(<<-FAIL) if true
  boop
FAIL

1
```

## Actual behavior

auto-correct mode produces this code:

```ruby
raise(<<-FAIL) if true

  boop
FAIL
1
```

## Steps to reproduce the problem

Run this rubocop command:

```
bundle exec rubocop --auto-correct --debug --only Layout/EmptyLineAfterGuardClause rubocop_example.rb
```

agains this ruby code:

```ruby
raise(<<-FAIL) if true
  boop
FAIL
1
```

## RuboCop version

```
$ bundle exec rubocop -V
0.59.0 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6264.

This PR fixes an incorrect auto-correct for `Layout/EmptyLineAfterGuardClause` cop when `if` condition is after heredoc.

This problem included two problems of auto-correct related to heredoc and false positives of `if` condition.

So this PR fixes the following auto-correct.

```ruby
raise(<<-FAIL) if true
  boop
FAIL
1
```

The following is the result of auto-correct.

## Before

```ruby
raise(<<-FAIL) if true

  boop
FAIL
1
```

## After

```ruby
raise(<<-FAIL) if true
  boop
FAIL

1
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/empty_line_after_guard_clause.rb [hunk 1]
```diff
@@ -109,19 +114,23 @@ def next_sibling_empty_or_guard_clause?(node)
...
+          heredoc?(last_argument)
         end
 
         def last_argument(node)
-          node.children.last.last_argument
+          node.if_branch.children.last
+        end
+
+        def heredoc?(node)
+          ((node.respond_to?(:str_type?) && node.str_type?) ||
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/empty_line_after_guard_clause.rb]: What's the case where `#last_argument` is not a `Node`? 🤔

Comment (koic) [reply lib/rubocop/cop/layout/empty_line_after_guard_clause.rb]: The method name `#last_argument` may not be representation well.
This code uses `respond_to?(:heredoc?)` because it possible returns `SendNode` or` Symbol` instead of `StrNode`.
I have not yet had a reasonable solution, but I have refactored redundant codes.
