### PR TITLE
[Fix #8572] Fix a false positive for `Style/RedundantParentheses`

### LINKED ISSUE #8572: Bug: Invalid autocorrection interaction between Lint/ParenthesesAsGroupedExpression & Style/RedundantParentheses
In Standard @sethherr noticed an undesired interaction between the safe autocorrections of `Lint/ParenthesesAsGroupedExpression` and `Style/RedundantParentheses` (both enabled-by-default): https://github.com/testdouble/standard/issues/192

--------

## Expected behavior

Here's the starting code example:

```ruby
do_something (foo)
```

Here's what happens when I run only `Lint/ParenthesesAsGroupedExpression` and `Style/RedundantParentheses`:

```
$ rubocop --only "Lint/ParenthesesAsGroupedExpression,Style/RedundantParentheses" foo.rb 
Inspecting 1 file
W

Offenses:

foo.rb:1:13: W: Lint/ParenthesesAsGroupedExpression: (...) interpreted as grouped expression.
do_something (foo)
            ^
foo.rb:1:14: C: Style/RedundantParentheses: Don't use parentheses around a method call.
do_something (foo)
             ^^^^^

1 file inspected, 2 offenses detected
```

My expectation is the autocorrect would ultimately result in either `do_something foo` or `do_something(foo)`

## Actual behavior

When running the same command with autocorrect, this is what we get:

```
$ be rubocop --only "Lint/ParenthesesAsGroupedExpression,Style/RedundantParentheses" -a foo.rb
Inspecting 1 file
W

Offenses:

foo.rb:1:13: W: [Corrected] Lint/ParenthesesAsGroupedExpression: (...) interpreted as grouped expression.
do_something (foo)
            ^
foo.rb:1:14: C: [Corrected] Style/RedundantParentheses: Don't use parentheses around a method call.
do_something (foo)
             ^^^^^

1 file inspected, 2 offenses detected, 2 offenses corrected
```

And now the result is definitely wrong:

```
$ cat foo.rb 
do_somethingfoo

```

## Steps to reproduce the problem

I hope the instructions above are a clear enough minimal reproduction

## RuboCop version

```
$ rubocop -V
0.89.1 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #8572.

This PR fixes a false positive for `Style/RedundantParentheses` when like method argument parentheses.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_parentheses.rb [hunk 1]
```diff
@@ -27,8 +27,8 @@ class RedundantParentheses < Base
 
         def on_begin(node)
           return if !parentheses?(node) || parens_allowed?(node)
-          return if node.parent && (node.parent.while_post_type? ||
-                                    node.parent.until_post_type?)
+          return if node.parent && (node.parent.while_post_type? || node.parent.until_post_type? ||
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_parentheses.rb:30]: Probably that big condition can become a helper method as well.

Comment (koic) [reply lib/rubocop/cop/style/redundant_parentheses.rb]: I updated this PR, but I'm not sure due to there may be a better approach (or name) 💦

**Comment by bbatsov** [comment]
Looks good!
