### PR TITLE
[Fix #7515] Fix a false negative for `Style/RedundantParentheses`

### LINKED ISSUE #7515: Style/RedundantParentheses does not add offense when safe navigation is used.
Given the following example:
`(code&.upcase).to_s`
Rubocop will not mark the parentheses as redundant.

However, with this similar example:
`(code.upcase).to_s`
Rubocop will correctly mark the parentheses as redundant.

Happy to help with a PR if this is in fact a bug.

--------

## Expected behavior
As far as I can tell, there is no reason not to mark such parentheses as redundant:
```
Style/RedundantParentheses: Don't use parentheses around a method call.
  (code&.upcase).to_s,
  ^^^^^^^^^^^^^^
```
## Actual behavior

Rubocop does not mark any offenses
## Steps to reproduce the problem

1. Create a test file, e.g. `test.rb`
```
(code&.upcase).to_s
```
2. With default configuration run `rubocop --only Style/RedundantParentheses test.rb` and notice no offenses

3. Optionally, modify the contents of `test.rb` to:
```
(code.upcase).to_s
```
4. Rerun `rubocop --only Style/RedundantParentheses test.rb` and note that the parentheses are flagged

## RuboCop version

```
$ rubocop --version
0.76.0 (using Parser 2.6.5.0, running on ruby 2.3.8 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7515.

This PR fixes a false negative for `Style/RedundantParentheses` when calling a method with safe navigation operator.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_parentheses.rb [hunk 1]
```diff
@@ -102,7 +103,7 @@ def check(begin_node)
           return offense(begin_node, 'a variable') if node.variable?
           return offense(begin_node, 'a constant') if node.const_type?
 
-          check_send(begin_node, node) if node.send_type?
+          check_send(begin_node, node) if method_call_type?(node)
```
Comment (buehmann) [inline lib/rubocop/cop/style/redundant_parentheses.rb]: There is `node.call_type?`

File: lib/rubocop/cop/style/redundant_parentheses.rb [hunk 2]
```diff
@@ -19,7 +19,8 @@ class RedundantParentheses < Cop
         def_node_matcher :square_brackets?,
                          '(send {(send _recv _msg) str array hash} :[] ...)'
         def_node_matcher :range_end?, '^^{irange erange}'
-        def_node_matcher :method_node_and_args, '$(send _recv _msg $...)'
+        def_node_matcher :method_node_and_args,
+                         '$({send csend} _recv _msg $...)'
```
Comment (buehmann) [inline lib/rubocop/cop/style/redundant_parentheses.rb]: You could also use `$(call _recv` here.

File: lib/rubocop/cop/style/redundant_parentheses.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/style/redundant_parentheses.rb]: Thank you for the great suggestion! I updated this PR.
