### PR TITLE
[Fix #6777] Fix a false positive for `Style/TrivialAccessors`

### LINKED ISSUE #6777: Style/TrivialAccessors wrongly auto-corrects methods outside of classes
We have a method inside our `spec_helper.rb` file like this

```
def response
  @response
end
```
It's detected by `Style/TrivialAccessors` and replaced with `attr_reader` leading to error 

```
Failure/Error: attr_reader :response

NoMethodError:
  undefined method `attr_reader' for main:Object
```

## Expected behavior

`Style/TrivialAccessors` cop should not auto-correct methods outside classes.

## Actual behavior

It auto-corrects methods outside classes, e.g. in `spec/spec_helper.rb` to use `attr_reader` breaking the code.

## Steps to reproduce the problem

```
# frozen_string_literal: true

def foo
  @foo
end

puts foo
```

This gets auto-corrected to
```
# frozen_string_literal: true

attr_reader :foo

puts foo
```

`ruby foo.rb` then gives the error `undefined method attr_reader for main:Object (NoMethodError)`

## RuboCop version

```
0.64.0 (using Parser 2.6.0.0, running on ruby 2.6.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6777.

This PR fixes a false positive for `Style/TrivialAccessors` when using reader / writer at the top level.

The following is a reproduction code.

```ruby
# example.rb
def foo
  @foo
end
```

```console
% rubocop example.rb --only Style/TrivialAccessors -a
Inspecting 1 file
C

Offenses:

example.rb:1:1: C: [Corrected] Style/TrivialAccessors: Use attr_reader
to define trivial reader methods.
def response
^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

An error occurs in the auto-corrected code.

```diff
% git diff
diff --git a/example.rb b/example.rb
index b26fec0..1868b1d 100644
--- a/example.rb
+++ b/example.rb
@@ -1,5 +1,3 @@
-def response
-  @response
-end
+attr_reader :response
```

```console
% ruby example.rb
Traceback (most recent call last):
example.rb:1:in `<main>': undefined method `attr_reader' for main:Object (NoMethodError)
```

This also occurs with writer. This PR will allow these cases.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/trivial_accessors_spec.rb [hunk 1]
```diff
@@ -234,6 +284,22 @@ def bar
...
+    RUBY
+  end
+
+  it 'accepts writer using top level' do
+    expect_no_offenses(<<-RUBY.strip_indent)
+      def bar=(bar)
+        @bar = bar
+      end
+    RUBY
+  end
```
Comment (koic) [inline spec/rubocop/cop/style/trivial_accessors_spec.rb]: 📝 These two test cases are the main changes.
