### PR TITLE
[Fix #6746] Avoid offense on `$stderr.puts` with no arguments.

### LINKED ISSUE #6746: Style/StderrPuts isn't the same thing when there is no message
## Expected behavior

Not to replace `$stderr.puts` (with no argument) with `warn` (with no argument) because they don't do the same thing - the former prints a new line, the latter prints nothing.

## Actual behavior

`$stderr.puts` (with no argument) is replaced with `warn` (with no argument).

## Steps to reproduce the problem

A file with just `$stderr.puts` (with no argument) in, compared to a file with just `warn` (with no argument) in. They don't do the same thing, but Rubocop suggests I swap from the former to the latter, and does so automatically if asked to fix.

This breaks real specs I have.

## RuboCop version

```
$ rubocop -V
0.63.1 (using Parser 2.6.0.0, running on ruby 2.6.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by luciamo**
This PR closes issue #6746. The applied changes will avoid offense on `$stderr.puts` with no arguments.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/stderr_puts.rb [hunk 1]
```diff
@@ -29,6 +29,9 @@ class StderrPuts < Cop
         def on_send(node)
           return unless stderr_puts?(node)
 
+          arguments = node.arguments
```
Comment (bbatsov) [inline lib/rubocop/cop/style/stderr_puts.rb]: I'd update the pattern instead. It would make the code more compact.

Comment (luciamo) [reply lib/rubocop/cop/style/stderr_puts.rb]: Thanks for the reply @bbatsov! I changed the pattern like you suggested. Could you check again? 😉

**Comment by bbatsov** [comment]
Thanks!
