### PR TITLE
[Fix #6737] Fix an incorrect auto-correct for `Rails/LinkToBlank`

### LINKED ISSUE #6737: Autocorrect for Rails/LinkToBlank is wrong for link_to with parentheses
Auto-correction of `Rails/LinkToBlank` produces syntactically incorrect code when `link_to` is used with parentheses.

--------

## Expected behavior

`, rel: 'noopener'` is expected to be inserted before the closing parenthesis.

```ruby
link_to('name', 'http://example.com', target: '_blank', rel: 'noopener')
```

## Actual behavior

`, rel: 'noopener'` is inserted after the closing parenthesis.

```ruby
link_to('name', 'http://example.com', target: '_blank'), rel: 'noopener'
```

## Steps to reproduce the problem

Example file(`test.rb`)
```ruby
link_to('name', 'http://example.com', target: '_blank')
```
```shell
$ rubocop -R -a test.rb 
Inspecting 1 file
E

Offenses:

test.rb:1:39: C: [Corrected] Rails/LinkToBlank: Specify a :rel option containing noopener.
link_to('name', 'http://example.com', target: '_blank')
                                      ^^^^^^^^^^^^^^^^
test.rb:1:56: E: Lint/Syntax: unexpected token tCOMMA
(Using Ruby 2.2 parser; configure using TargetRubyVersion parameter, under AllCops)
link_to('name', 'http://example.com', target: '_blank'), rel: 'noopener'
                                                       ^

1 file inspected, 2 offenses detected, 1 offense corrected
```

## RuboCop version

```
$ rubocop -V
0.63.1 (using Parser 2.6.0.0, running on ruby 2.4.5 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6737.

This PR fixes an incorrect auto-correct for `Rails/LinkToBlank` when `link_to` method arguments are enclosed in parentheses.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/link_to_blank.rb [hunk 1]
```diff
@@ -74,7 +74,9 @@ def append_to_rel(rel_node, corrector)
         def add_rel(send_node, offence_node, corrector)
           quote_style = offence_node.children.last.source[0]
           new_rel_exp = ", rel: #{quote_style}noopener#{quote_style}"
-          corrector.insert_after(send_node.loc.expression, new_rel_exp)
+          range = send_node.children.last.source_range
```
Comment (pocke) [inline lib/rubocop/cop/rails/link_to_blank.rb]: [nitpick]
Personally I think `send_node.arguments.last.source_range` is more meaningful. What do you think?

```suggestion
          range = send_node.arguments.last.source_range
```

Comment (koic) [reply lib/rubocop/cop/rails/link_to_blank.rb]: Sure! I updated it.
