### PR TITLE
[#9526] Add `AllowSplatArgument` option to `Style/HashConversion`

### LINKED ISSUE #9526: Style/HashConversion splatted array should not error
## Expected behavior

It would be nice to enable `Style/HashConversion` but not flag `Hash[*values]` usage as invalid.

## Actual behavior

Getting the following error when using splatting an array to a hash:

``` 
snippet.rb:4:16: C: Style/HashConversion: Prefer array_of_pairs.to_h to Hash[*array].
  def to_env = Hash[*values]
```

## Steps to reproduce the problem

Create the following files locally to reproduce:

``` ruby
# File: .rubocop.yml
Style/HashConversion:
  Enabled: true
```

``` ruby
# frozen_string_literal: true

# File: snippet.rb
Pair = Struct.new :key, :value do
  def to_env = Hash[*values]
end
```

Now run the following:

`rubocop snippet.rb`

Notice you'll get the following error:

``` 
snippet.rb:4:16: C: Style/HashConversion: Prefer array_of_pairs.to_h to Hash[*array].
  def to_env = Hash[*values]
```

## RuboCop version

```
# rubocop -V
1.10.0 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-darwin20)
```

### PR DESCRIPTION
**Pull request by koic**
Resolves #9526.

This PR add `AllowSplatArgument` option to `Style/HashConversion` and the option is true by default.
This is because `Hash[*ary]` is not allowed because it is strict.

As discussed in https://github.com/rubocop-hq/rubocop/pull/9478#discussion_r567259779, the correction code from `Hash[*arg]` is not simply determined. So, I think it's better to allow it by default as a simple notation.

On the other hand, there may be case where some users want to use the existing behavior, so this PR have made it optional.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/hash_conversion.rb [hunk 1]
```diff
@@ -18,6 +18,15 @@ module Style
       #
       #   # good
       #   {key1 => value1, key2 => value2}
+      #
+      # @example AllowSplatArgument: true (default)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/hash_conversion.rb:22]: Might be a good idea to add some explanation for the need for some such configuration option, as without the context from the ticket I don't think that'd be obvious.

Comment (koic) [reply lib/rubocop/cop/style/hash_conversion.rb:26]: Sure! I added an explanation for the configuration option.
