### PR TITLE
[Fix #6132] Fix a false negative for `Naming/FileName`

### LINKED ISSUE #6132: Naming/FileName Cop not working
## Expected behavior

I created  ` lib/layoutManager.rb` (not a script) but when I run rubocop it doesn't tell me it should be snake case.

## Actual behavior

rubocop returns with "no offenses detected"

## Steps to reproduce the problem

1. create file lib/layoutManager.rb
2. run `rubocop lib/layoutManager.rb`

## RuboCop version

```
$ rubocop -V
0.58.2 (using Parser 2.5.1.2, running on ruby 2.3.3 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6132.

### Summary

This PR fixes a false negative for `Naming/FileName` when `Include` of `AllCops` is the default setting.

The important change in this PR is below.

```diff
diff --git a/lib/rubocop/cop/naming/file_name.rb
b/lib/rubocop/cop/naming/file_name.rb
index a025a73b7..be3f1c5aa 100644
--- a/lib/rubocop/cop/naming/file_name.rb
+++ b/lib/rubocop/cop/naming/file_name.rb
@@ -32,7 +32,7 @@ module RuboCop

         def investigate(processed_source)
           file_path = processed_source.file_path
-          return if config.file_to_include?(file_path)
+          return if config.file_to_exclude?(file_path)
```

The problem is that the target to be excluded was `Include` instead of `Exclude`.

Also this PR adds the `RuboCop::Config#allowed_camel_case_file?` method to judge ignoring `Gemfile`, `Rakefile`, etc described in` Include`.

### Other Information

This false negative was noticed by adding `**/*.rb` to config/default.yml at rubocop-hq/rubocop#5882.

https://github.com/rubocop-hq/rubocop/pull/5882/files#diff-e93280b3b31a6438c533a5f3232340d8R18

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config.rb [hunk 1]
```diff
@@ -373,8 +373,23 @@ def file_to_include?(file)
...
+        else
+          match_path?(pattern, relative_file_path) ||
+            match_path?(pattern, absolute_file_path)
+        end
+      end
+    end
+
+    def allowed_camel_case_file?(file)
+      file_to_include?(file) do |pattern, relative_path, absolute_path|
+        if pattern.to_s =~ /[A-Z]/
```
Comment (rrosenblum) [inline lib/rubocop/config.rb]: I think this if statement can be converted to

```ruby
pattern.to_s =~ /[A-Z]/ &&
  (match_path?(pattern, relative_path) ||
   match_path?(pattern, absolute_path))
```
That way the else can be eliminated entirely. 

Also, what kind of object is `pattern`? Assuming that `pattern` is a symbol, `to_s` is unnecessary because `=~` works with symbols.

Comment (koic) [reply lib/rubocop/config.rb]: > That way the else can be eliminated entirely.

Oh, I see! I fixed the conditional expression simple.

> Also, what kind of object is `pattern`?

If `!ruby/regexp /regexp$/` is written in `Include` of .rubocop.yml, a `Regexp` instance is returned.
https://github.com/rubocop-hq/rubocop/blob/1bff66b2b8bafd215c106ee06411277d5554581d/spec/rubocop/cli_spec.rb#L996

In that case this code need `to_s` to prevent `TypeError`.

Comment (rrosenblum) [reply lib/rubocop/config.rb]: > If !ruby/regexp /regexp$/ is written in Include of .rubocop.yml, a Regexp instance is returned.

That makes more sense. I wasn't even thinking about `pattern` being regex. I'm so used to the paradigm of `to_s =~ //` being used unnecessarily with symbols.
