### PR TITLE
[Fix #6489] Fix an error for `Style/UnneededCondition`

### LINKED ISSUE #6489: rubocop --auto-correct crashes on the Rufo codebase
## Expected behavior

`rubocop --auto-correct` should not crash when used on the [`rufo`](https://github.com/ruby-formatter/rufo) codebase.

## Actual behavior

`rubocop --auto-correct` crashes with the following error:

```

13 files inspected, 350 offenses detected, 282 offenses corrected
undefined method `basic_conditional?' for nil:NilClass
.../lib/rubocop/cop/style/unneeded_condition.rb:94:in `else_source'
.../lib/rubocop/cop/style/unneeded_condition.rb:100:in `make_ternary_form'
.../lib/rubocop/cop/style/unneeded_condition.rb:53:in `block in autocorrect'
```

## Steps to reproduce the problem

```
cd /tmp
git clone https://github.com/ruby-formatter/rufo.git
cd rufo
rubocop -a
```

## RuboCop version

```
$ rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.5.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6489.

This PR fixes an error for `Style/UnneededCondition` when `if` condition and `then` branch are the same and it has no `else` branch. The following is an error case.

```ruby
# example.rb
if 1
  1
end
```

The following is a reproduction step.

```console
% rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17)

% rubocop example.rb --only Style/UnneededCondition -a
Inspecting 1 file

0 files inspected, no offenses detected
undefined method `basic_conditional?' for nil:NilClass
/Users/koic/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubocop-0.60.0/lib/rubocop/cop/style/unneeded_condition.rb:94:in
`else_source'
/Users/koic/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubocop-0.60.0/lib/rubocop/cop/style/unneeded_condition.rb:100:in
`make_ternary_form'
/Users/koic/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubocop-0.60.0/lib/rubocop/cop/style/unneeded_condition.rb:53:in
`block in autocorrect'

(snip)
```

And this PR will change the following offense message.

## Before

```console
% rubocop example.rb --only Style/UnneededCondition
Inspecting 1 file
C

Offenses:

example.rb:1:1: C: Style/UnneededCondition: Use double pipes || instead.
if 1 ...
^^^^

1 file inspected, 1 offense detected
```

## After

```console
% rubocop example.rb --only Style/UnneededCondition
Inspecting 1 file
C

Offenses:

example.rb:1:1: C: Style/UnneededCondition: This condition is not needed.
if 1 ...
^^^^

1 file inspected, 1 offense detected
```

The auto-correct behaves as follows.

```console
% rubocop example.rb --only Style/UnneededCondition -a
Inspecting 1 file
C

Offenses:

example.rb:1:1: C: [Corrected] Style/UnneededCondition: This condition is not needed.
if 1 ...
^^^^

1 file inspected, 1 offense detected, 1 offense corrected

% cat example.rb
1
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
💯

File: spec/rubocop/cop/style/unneeded_condition_spec.rb [hunk 1]
```diff
@@ -161,6 +173,19 @@
...
+      it 'when `if` condition and `then` branch are the same ' \
+         'and it has no `else` branch' do
+        new_source = autocorrect_source(<<-RUBY.strip_indent)
+          if do_something
+            do_something
+          end
+        RUBY
+
+        expect(new_source).to eq(<<-RUBY.strip_indent)
+          do_something
```
Comment (jonas054) [inline spec/rubocop/cop/style/unneeded_condition_spec.rb]: If `do_something` returns a truthy value, it will now be called once instead of twice. If it has side effects, that means changed semantics.
