### PR TITLE
Register BlockDelimiters offense with attribute assignment

### LINKED ISSUE #7305: Style/BlockDelimiters not triggered with attribute assignment
Using Style/BlockDelimiters with the default configuration, the following code triggers no offenses:

```
foo.bar = baz.map { |it|
  qux(it)
}
```

## Expected behavior

RuboCop should report "Style/BlockDelimiters: Avoid using {...} for multi-line blocks."

## Actual behavior

RuboCop reports nothing.

## Steps to reproduce the problem

Create a file with the following contents and run RuboCop on it:

```
# frozen_string_literal: true

foo.bar = baz.map { |it|
  qux(it)
}

puts foo
```

RuboCop will report no offenses.

## RuboCop version

```
$ rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by mvz**
Update Style/BlockDelimiters to handle attribute assignment.

Fixes #7305 by recognizing that blocks as arguments of assignment methods can safely be mutated from one block delimiter style to the other.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by mvz** [comment]
(I'm working on the checkboxes.)

**Comment by mvz** [comment]
All done. Ready for review.

File: spec/rubocop/cop/style/block_delimiters_spec.rb [hunk 1]
```diff
@@ -351,6 +351,14 @@
         RUBY
       end
 
+      it 'registers an offense when combined with attribute assignment' do
+        expect_offense(<<~RUBY)
+          foo.bar = baz.map { |x|
+                            ^ Avoid using `{...}` for multi-line blocks.
+          }
+        RUBY
+      end
```
Comment (koic) [inline spec/rubocop/cop/style/block_delimiters_spec.rb]: This test case is good. OTOH, `EnforcedStyle: 'semantic'`, `EnforcedStyle: 'always_braces'` and  method chained `EnforcedStyle: braces_for_chaining` should not be warned. Could you add these test cases and pass them?

Comment (mvz) [reply spec/rubocop/cop/style/block_delimiters_spec.rb]: Done!

**Comment by bbatsov** [comment]
Thanks!
