### PR TITLE
[Fix #4321] Allow `self` to receive methods also defined on `Kernel`

### LINKED ISSUE #4321: Style/RedundantSelf confused when `extending` a scope
## Expected behavior

```ruby
module MyClassQuery
  def initialize(scope: MyClass.all)
    @scope = scope.extending(Scopes)
  end

  module Scopes
    def active
      self.open.where(active: true)
    end
  end
end

class MyClass  < ActiveRecord::Base
  scope :open, -> { where(open: true) }
end
```

The `self.open` should not trigger the redundant self cop.  Without the `self` ruby calls https://ruby-doc.org/core-2.1.4/File.html#method-c-open, with the `self` it calls `MyClass.instance_method(:open)` which is the intended behavior.

## Actual behavior

The cop is triggered

## Steps to reproduce the problem

See Expected behavior

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by mikegee**
Method calls with an explicit receiver of `self` are ok when a method with the same name is also defined on `Kernel`. Rubocop can't know if the explicit `self` is disambiguating a method call or not.

Fixes #4321 

(Perhaps there should be another cop warning about defining methods that are also defined on `Kernel`? 🤔 )

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_self.rb [hunk 1]
```diff
@@ -43,6 +43,7 @@ module Style
       #   end
       class RedundantSelf < Cop
         MSG = 'Redundant `self` detected.'.freeze
+        KERNEL_METHODS = Kernel.methods(false)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_self.rb]: The problem with this approach is that the methods you'll get might not match the target Ruby version (e.g. if you're running RuboCop with a different version of Ruby).

**Comment by bbatsov** [comment]
Apart from my small remark, I think that's a good improvement. 

> (Perhaps there should be another cop warning about defining methods that are also defined on Kernel? 🤔 )

Yeah, I totally agree. No idea why we haven't implemented this yet. Should be super simple.

File: lib/rubocop/cop/style/redundant_self.rb (hunk 1 above)
Comment (mikegee) [reply lib/rubocop/cop/style/redundant_self.rb]: Good point. Do we need to maintain a list for each version? I’ll try to think of something simpler.

Comment (bbatsov) [reply lib/rubocop/cop/style/redundant_self.rb]: I'd rather avoid that. I was just pointing out that this solution is not completely reliable.

**Comment by bbatsov** [comment]
I just realized it would have also been nice to update the docs/examples.

**Comment by mikegee** [comment]
I figured this was an edge case that didn’t need the visibility but I didn’t think about it much.

**Comment by bbatsov** [comment]
Well, that's not that different from having local variables named the same way as a method. :-)
