### PR TITLE
[Fix #7170] Fix a false positive in `Layout/RescueEnsureAlignment` cop

### LINKED ISSUE #7170: Layout/RescueEnsureAlignment doesn't behave as expected with inline private_class_method
Rubocop reports a warning, when I think it shouldn't.

--------

## Expected behavior
I expect no warnings for this example. Also, autocorrection should align this method as it is:
```ruby
private_class_method def self.parse(_foo)
  puts 'hi'
rescue StandardError
  puts 'do nothing'
end
```

## Actual behavior

This is the warning I get:
```
Inspecting 1 file
C

Offenses:

tests.rb:5:1: C: Layout/RescueEnsureAlignment: rescue at 5, 0 is not aligned with def self.parse at 3, 21.
rescue StandardError
^^^^^^

1 file inspected, 1 offense detected
```
And this the autocorrection:
```ruby
# frozen_string_literal: true

private_class_method def self.parse(_foo)
  puts 'hi'
                     rescue StandardError
                       puts 'do nothing'
end
```

## Steps to reproduce the problem

Already described

## RuboCop version

```
0.71.0 (using Parser 2.6.3.0, running on ruby 2.5.3 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by tatsuyafw**
Fixes #7170.

The `Layout/RescueEnsureAlignment` would register an offense when `private_class_method` and def are on the same line as below:

```console
$ cat foo.rb
private_class_method def self.foo
  puts 'foo'
rescue StandardError
  puts 'bar'
end
$
```

```console
$ rubocop --only 'Layout/RescueEnsureAlignment' foo.rb
Inspecting 1 file
C

Offenses:

foo.rb:3:1: C: Layout/RescueEnsureAlignment: rescue at 3, 0 is not aligned with def self.foo at 1, 21.
rescue StandardError
^^^^^^

1 file inspected, 1 offense detected
$
```

This change makes sure the cop recognizes def lines preceded with private_class_method.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb [hunk 1]
```diff
@@ -460,128 +460,138 @@ def foo
...
-          end
-        RUBY
-      end
+    context 'with private modifier' do
+      include_examples 'access modifier', 'private'
+    end
+
+    context 'with private_class_method modifier' do
+      include_examples 'access modifier', 'private_class_method'
     end
```
Comment (koic) [inline spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb]: This expected behavior may be more clearer by writing a spec of `public_class_method`.

**Comment by tatsuyafw** [comment]
@koic 

Thank you for your review!
I've resolved conflicts and also added a spec for `public_class_method`.

**Comment by tatsuyafw** [comment]
I failed to fix `CHANGELOG`. I've moved the `Bug fixes` section above `CHANGELOG`.

**Comment by koic** [comment]
Looks good to me. Could you resolve the conflict?

**Comment by tatsuyafw** [comment]
@koic 

Thanks!
I've resolved the conflict.

**Comment by koic** [comment]
Thanks!
