### PR TITLE
[Fix #8475] Fix a false positive for Style/HashAsLastArrayItem when t…

### LINKED ISSUE #8475: Style/HashAsLastArrayItem copy with style "no_braces" can result in invalid code
## Expected behavior

Using Style/HashAsLastArrayItem with EnforcedStyle: no_braces should yield valid Ruby code when there are duplicate Hashes in the array.  This is similar to https://github.com/rubocop-hq/rubocop/issues/8323, but has not been fully resolved when there are identical hashes in the array. 

## Actual behavior

The cop is not safe and results in invalid Ruby code.

## Steps to reproduce the problem
```yaml
# .rubocop.yml
AllCops:
  NewCops: enable

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
```

```ruby
# hash_as_last_array_item.rb before
# frozen-string-literal: true

# Note that the hashes are identical
a = [
  {
    foo: :bar,
  },
  {
    foo: :bar
  }
]

pp a
```

```console
$ ruby hash_as_last_array_item.rb
[{:foo=>:bar}, {:foo=>:bar}]
```

```console
$ rubocop -a hash_as_last_array_item.rb
Inspecting 1 file
E

Offenses:

hash_as_last_array_item.rb:5:3: C: [Corrected] Style/HashAsLastArrayItem: Omit the braces around the hash.
  { ...
  ^
hash_as_last_array_item.rb:6:14: C: [Corrected] Style/TrailingCommaInHashLiteral: Avoid comma after the last item of a hash.
    foo: :bar,
             ^
hash_as_last_array_item.rb:7:3: E: Lint/Syntax: unexpected token tCOMMA
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
  ,
  ^
hash_as_last_array_item.rb:8:3: C: [Corrected] Style/HashAsLastArrayItem: Omit the braces around the hash.
  { ...
  ^

1 file inspected, 4 offenses detected, 3 offenses corrected
```

```ruby
# hash_as_last_array_item.rb after
# frozen-string-literal: true

a = [

    foo: :bar
  ,

    foo: :bar

]

pp a
```

```console
$ ruby hash_as_last_array_item.rb
hash_as_last_array_item.rb:7: syntax error, unexpected ',', expecting ']'
hash_as_last_array_item.rb:11: syntax error, unexpected ']', expecting end-of-input
```

## RuboCop version

```
$ rubocop -v
0.89.0
```

### PR DESCRIPTION
**Pull request by wcmonty**
Closes #8475

The issue is that we were previously comparing values to the last node.  If a node equals the last node it will be marked with an offense, when it should not be.

### CODE REVIEW

File: lib/rubocop/cop/style/hash_as_last_array_item.rb [hunk 1]
```diff
@@ -40,7 +40,7 @@ def last_array_item?(node)
           parent = node.parent
           return false unless parent
 
-          parent.array_type? && parent.values.last == node
+          parent.array_type? && parent.children.last.object_id == node.object_id
```
Comment (koic) [inline lib/rubocop/cop/style/hash_as_last_array_item.rb:43]: I think using `equal?` can be a bit simpler :-)

```suggestion
          parent.array_type? && parent.children.last.equal?(node)
```

Comment (wcmonty) [reply lib/rubocop/cop/style/hash_as_last_array_item.rb]: Agreed your suggestion is simpler.  I went ahead and committed.  Happy to squash if necessary.

**Comment by koic** [comment]
This looks good to me. Can you add changelog entry and squash your commits into one?
The following is the changelog entry format.
https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format

**Comment by wcmonty** [comment]
@koic This is rebased/squashed with the changelog entry added.  One set of specs is failing (https://github.com/rubocop-hq/rubocop/pull/8477/checks?check_run_id=959581086), but it doesn't look related to this PR.

**Comment by koic** [comment]
It was a false alarm of CI. I re-ran it again and passed it. Thank you!
