### PR TITLE
[Fix #8673] Fix the JSON parse error when specifying `--format=json` and `--stdin`

### LINKED ISSUE #8673: Using the `--fix` option with `--stdin` appends file content to the json result
When I run `rubocop` using `--fix` and `--stdin` flags, I can see that the content of the file is appended to the JSON result.
This prevent tools (like RubyMine) to parse the response (https://youtrack.jetbrains.com/issue/RUBY-27006)

## Expected behavior

I would expect to have only the JSON result.

## Actual behavior

Example:
```
❯ rubocop --format json --force-exclusion --fix --stdin application_controller.rb < app/controllers/application_controller.rb 
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.0","ruby_patchlevel":"0","ruby_platform":"x86_64-darwin19"},"files":[{"path":"application_controller.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}====================
class ApplicationController < ActionController::API
end
```

## Steps to reproduce the problem

Just run the following in a Rails project:

`rubocop --format json --force-exclusion --fix --stdin application_controller.rb < app/controllers/application_controller.rb `

## RuboCop version

```
❯ bundle exec rubocop -V              
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.0 x86_64-darwin19)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #8673.

This PR returns only JSON result when specifying `--format=json` and `--stdin` to fix the JSON parse error.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cli/command/execute_runner.rb [hunk 1]
```diff
@@ -61,6 +61,11 @@ def display_error_summary(errors)
         end
 
         def maybe_print_corrected_source
+          # Integration tools (like RubyMine) expect to have only the JSON result
+          # when specifying JSON format.
+          # See: https://github.com/rubocop-hq/rubocop/issues/8673
+          return if @options[:format] == 'json'
```
Comment (bbatsov) [inline lib/rubocop/cli/command/execute_runner.rb:67]: Btw, shouldn't we do the same for the HTML formatter as well? Might be weird to append plain text to it.

Comment (koic) [reply lib/rubocop/cli/command/execute_runner.rb]: Sure! I think also JUnit formatter is similar, so I added HTML and JUnit formatters.

**Comment by bbatsov** [comment]
Thanks!
