### PR TITLE
[Fix #5987] Suppress errors when using ERB template

### LINKED ISSUE #5987: Rails/BulkChangeTable fails due to ERB in database.yml
If there is ERB in database.yml that causes it to not be syntactically valid YAML without pre-processing, the Rails/BulkChangeTable cop fails.

For example, we have a ternary in one of our keys, which is not valid yaml because the colon is a special character:
```yaml
  pool: <%= Sidekiq.server? ? 10 : 5 %>
```

--------

## Expected behavior

Rubocop not to throw an error, and to suggest setting the `Database` config for this cop.

## Actual behavior

Rubocop throws an error:

```
(config/database.yml): mapping values are not allowed in this context at line 44 column 34
psych.rb:377:in `parse'
# ...
$GEM_HOME/gems/rubocop-0.57.1/lib/rubocop/cop/rails/bulk_change_table.rb:194:in `database_yaml'
```

## Steps to reproduce the problem

Add a ternary inside an ERB expression in database.yml, then run the Rails/BulkChangeTable cop.

## RuboCop version

```
$ rubocop -V
0.57.1 (using Parser 2.5.1.0, running on ruby 2.3.0 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by wata727**
Fixes #5987

Rails/BulkChangeTable cop raise an error when `database.yml` contains the syntax of ERB.

In this case, catches the error and treats `database.yml` as empty.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/bulk_change_table.rb [hunk 1]
```diff
@@ -191,7 +191,11 @@ def database_from_yaml
 
         def database_yaml
           return nil unless File.exist?('config/database.yml')
-          yaml = YAML.load_file('config/database.yml')
+          begin
+            yaml = YAML.load_file('config/database.yml')
+          rescue Psych::SyntaxError
```
Comment (bbatsov) [inline lib/rubocop/cop/rails/bulk_change_table.rb]: I'd probably use a method level `rescue` here, so the related code is grouped more closely together.

**Comment by bbatsov** [comment]
👍
