### PR TITLE
[Fix #6127] Fix an error for `Layout/ClosingParenthesisIndentation` cop

### LINKED ISSUE #6127: Layout/ClosingParenthesisIndentation error with newlines on 0.58.2
## Information

When refactoring some code, Rubocop threw an error for the Layout/ClosingParenthesisIndentation cop.

Offending code is: 

```ruby
  def foo
    JSON.parse(
      
    )
  end
```

Error is not thrown if parens are on the same line.

```ruby
  def foo
    JSON.parse()
  end
```

## Expected behavior

Standard Rubocop alerting without error.

## Actual behavior

Error:

> An error occurred while Layout/ClosingParenthesisIndentation cop was inspecting /Users/jsmith/code/go/src/github.com/brightcove/bolt-playback-automation/lib/bolt_video.rb:10:4. To see the complete backtrace run rubocop -d. 1 error occurred: An error occurred while Layout/ClosingParenthesisIndentation cop was inspecting /Users/jsmith/code/go/src/github.com/brightcove/bolt-playback-automation/lib/bolt_video.rb:10:4. Errors are usually caused by RuboCop bugs. Please, report your problems to RuboCop's issue tracker. https://github.com/rubocop-hq/rubocop/issues Mention the following information in the issue report: 0.58.2 (using Parser 2.5.1.2, running on ruby 2.4.1 x86_64-darwin16)

## Steps to reproduce the problem

Run Rubocop against:

```ruby
  def foo
    JSON.parse(
      
    )
  end
```

## RuboCop version

0.58.2 (using Parser 2.5.1.2, running on ruby 2.4.1 x86_64-darwin16)

### PR DESCRIPTION
**Pull request by tatsuyafw**
Fixes #6127

`Layout/ClosingParenthesisIndentation` cop threw an error when method arguments are empty and a right paren started in newlines like the following code:

```ruby
# foo.rb
def foo
  something(
  )
end
```

```console
$ rubocop --only 'Layout/ClosingParenthesisIndentation' foo.rb
Inspecting 1 file
An error occurred while Layout/ClosingParenthesisIndentation cop was inspecting /Users/hoshino/src/github.com/tatsuyafw/rubocop/foo.rb:2:2.
To see the complete backtrace run rubocop -d.
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Layout/ClosingParenthesisIndentation cop was inspecting /Users/hoshino/src/github.com/tatsuyafw/rubocop/foo.rb:2:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)
$
```

This change fixes the above error.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb [hunk 1]
```diff
@@ -67,6 +67,13 @@
         expect_no_offenses('some_method()')
       end
 
+      it 'accepts empty () with newlines' do
+        expect_no_offenses(<<-RUBY.strip_indent)
+          some_method(
+          )
+        RUBY
+      end
```
Comment (koic) [inline spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: Thank you for fixing the error 👍 

It seems better to pass the tests on the following cases as well.

```ruby
# bad
foo = some_method(
)

# good
some_method(
           )

foo = some_method(
      )

foo = some_method(
                 )
```

Comment (tatsuyafw) [reply spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: @koic

Thank you for your reviews!
I have a question about the following bad case you mentioned.

```
# bad
foo = some_method(
)
```

I thought that the code was a good case, and added a test as a good case: [here](https://github.com/tatsuyafw/rubocop/blob/813170b5c247d4ce7f873ae28a81aceda0a93528/spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb#L212-L217)

Is it better that tests pass the cases you wrote?

Comment (koic) [reply spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: Oops, this is my mistake.

I thought of the following comparison. It was a bad case to align the variable and the indentation of `(`. So I thought was bad.

## bad

```console
% cat bad.rb
def foo
  foo = JSON.parse(a
  )
end

% rubocop bad.rb --only Layout/ClosingParenthesisIndentation
Inspecting 1 file
C

Offenses:

bad.rb:3:3: C: Layout/ClosingParenthesisIndentation: Align ) with (.
  )
  ^

1 file inspected, 1 offense detected
```

## good

```console

% cat good.rb
def foo
  foo = JSON.parse(a
                  )
end

% rubocop good.rb --only Layout/ClosingParenthesisIndentation
Inspecting 1 file
.

1 file inspected, no offenses detected
```

However, considering the following case, it is good to align the variable and the indentation of `(`, which is not a problem.

## good

```
% cat good2.rb
def foo
  foo = JSON.parse(
    a
  )
end

% rubocop good2.rb --only Layout/ClosingParenthesisIndentation
Inspecting 1 file
.

1 file inspected, no offenses detected
```

Therefore, the following case is good.

```ruby
foo = some_method(
)
```

Comment (tatsuyafw) [reply spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: Thank you for your kind explanations. I understand. I try to fix codes to pass the following tests.

```
# bad
some_method(
  )

foo = some_method(
  )

# good
some_method(
)

some_method(
           )

foo = some_method(
)

foo = some_method(
      )

foo = some_method(
                 )
```

Comment (koic) [reply spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: This looks great. Thank you for explaining with an easy to understand examples! Please go ahead with it.

Comment (tatsuyafw) [reply spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: @koic I'm sorry for my late reply :bow:

I've fixed codes to pass the tests described in the above. I kindly ask your confirmation.

File: lib/rubocop/cop/layout/closing_parenthesis_indentation.rb [hunk 2]
```diff
@@ -113,6 +121,26 @@ def check(node, elements)
                                         right_paren))
         end
 
+        def check_for_no_elements(node)
+          left_paren = node.loc.begin
+          right_paren = node.loc.end
+          return unless left_paren
```
Comment (koic) [inline lib/rubocop/cop/layout/closing_parenthesis_indentation.rb]: Is this guard condition necessary? The tests will pass even without this.

File: spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb (hunk 1 above)
Comment (koic) [reply spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb]: Don't worry. Thank you very much for your great work! I have written a review comment.
https://github.com/rubocop-hq/rubocop/pull/6130/files#r207432492

File: lib/rubocop/cop/layout/closing_parenthesis_indentation.rb (hunk 2 above)
Comment (tatsuyafw) [reply lib/rubocop/cop/layout/closing_parenthesis_indentation.rb]: Oh, the guard was unnecessary... I've fixed.

File: CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,10 @@
 
 * [#6137](https://github.com/rubocop-hq/rubocop/pull/6137): Allow `db` to allowed names of `Naming/UncommunicativeMethodParamName` cop in default config. ([@mkenyon][])
 
+### Bug fixes
+
+* [#6127](https://github.com/rubocop-hq/rubocop/issues/6127): Fix an error for `Layout/ClosingParenthesisIndentation` when method arguments are empty with newlines. ([@tatsuyafw][])
```
Comment (koic) [inline CHANGELOG.md]: Would you please move the `### Bug fixes` section before the `### Changes` section?

Others looks good 👍

Comment (tatsuyafw) [reply CHANGELOG.md]: Thanks!

I've moved the `Bug fixes` section to before the `Changes` section, and rebased master to resolve conflicts

**Comment by koic** [comment]
Merged. Thanks again for your great work.
