### PR TITLE
[Fix #7326] Fix a false positive for `Style/AccessModifierDeclarations`

### LINKED ISSUE #7326: `Style/AccessModifierDeclarations` wrong offense detected
## Expected behavior

No offense detected.

## Actual behavior

Offence detected.

## Steps to reproduce the problem

code

```
class Hoge
  attr_reader :size
  attr_reader :density
  attr_reader :public

  def initialize(size:, density:, public:)
    @size = size
    @density = density
    @public = public
  end

  def perform(users)
    ::ActiveRecord::Associations::Preloader.new.preload(users, :avatar_photo, Attachment.all)

    users.each do |user|
      fulfill(user, user.decorate.avatar_image(size: size, density: density, public: public))

    end
  end
end
```

rubocop log

```
> bundle exec rubocop
hoge.rb:18:86: C: Style/AccessModifierDeclarations: public should be inlined in method definitions.
      fulfill(user, user.decorate.avatar_image(size: size, density: density, public: public))
                                                                                     ^^^^^^
```

rubocop setting

```
〜
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
```

## RuboCop version

```
> bundle exec rubocop -V
0.74.0 (using Parser 2.6.4.0, running on ruby 2.5.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7326.

This PR fixes a false positive for `Style/AccessModifierDeclarations` when access modifier name is used for hash literal value.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/access_modifier_declarations.rb [hunk 1]
```diff
@@ -63,6 +63,7 @@ class AccessModifierDeclarations < Cop
 
         def on_send(node)
           return unless node.access_modifier?
+          return if node.parent.pair_type?
```
Comment (bbatsov) [inline lib/rubocop/cop/style/access_modifier_declarations.rb]: Seems to me the real problem here is that the cop is inspecting all `send` node instead of just going over whatever is in a `class/module` body. Your fix will do, but I think the cop's design cop be improved in general.

Comment (koic) [reply lib/rubocop/cop/style/access_modifier_declarations.rb]: Sure! I think it ’s a good improvement idea.
`block` may also need to be considered in addition to `class` and `module` (#7298). Since redesign may take some time, I'd like to proceed with another PR. What do you think?

Comment (bbatsov) [reply lib/rubocop/cop/style/access_modifier_declarations.rb]: > block may also need to be considered in addition to class and module

You're right.

> Since redesign may take some time, I'd like to proceed with another PR. What do you think?

Yeah, that's fine by me. We can merge this one in the mean time.
