### PR TITLE
[Fix #9415] Change `Layout/ClassStructure` to detect inline modifiers

### LINKED ISSUE #9415: False negatives in Layout/ClassStructure with inline access modifiers
The `Layout/ClassStructure` cop fails to surface private/public method ordering violations when inline access modifiers are used. Given the file `ab.rb` with:

```
class A
  private def foo
  end

  public def bar
  end
end

class B
  private
  def foo
  end

  public
  def bar
  end
end
```
--------

## Expected behavior

`Layout/ClassStructure` should be agnostic to visibility modifier and flag both definitions of `bar` (`A#bar` and `B#bar`).

## Actual behavior
Only `B#bar` is flagged:
```
rubocop ab.rb --only Layout/ClassStructure
Inspecting 1 file
C

Offenses:

ab.rb:15:3: C: [Correctable] Layout/ClassStructure: public_methods is supposed to appear before private_methods.
  def bar ...
  ^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

## Steps to reproduce the problem

☝️ 

## RuboCop version

```
1.8.1 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-darwin20)
  - rubocop-performance 1.9.2
  - rubocop-rake 0.5.1
  - rubocop-rspec 2.1.0
  - rubocop-sorbet 0.5.1
```

### PR DESCRIPTION
**Pull request by AndreiEres**
Fix https://github.com/rubocop-hq/rubocop/issues/9415

* Added check for inline def modifiers. Now they can be handle as `public_methods`, `protected_methods`, and `private methods` respectively.
* Fixed autocorrection range for methods with modifier.
* Fixed test that now throws new offence for inline modifier but was created for another reason.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/class_structure_spec.rb [hunk 1]
```diff
@@ -321,4 +318,27 @@ def do_something
...
     RUBY
   end
+
+  it 'registers an offense and corrects when private method with inline modifier is declared before public' do
+    expect_offense(<<~RUBY)
+      class A
+        private def foo
+        end
+
+        public def bar
```
Comment (dduugg) [inline spec/rubocop/cop/layout/class_structure_spec.rb:328]: Does this still flag and autocorrect the offense if the explicit `public` isn't there? Is that captured in a test?

Comment (AndreiEres) [reply spec/rubocop/cop/layout/class_structure_spec.rb]: Thanks, I've added the test

**Comment by bbatsov** [comment]
The changes look good. Probably we should add some doc examples of a class using inline modifiers, but that's orthogonal to the current PR. Thanks!
