### PR TITLE
[Fix #8347] Fix an incorrect auto-correct for `Style/HashSyntax`

### LINKED ISSUE #8347: HashSyntax plus HashAlignment breaks the page
When mixing `Style/HashSyntax` with a setting of `hash_rockets` and the default `Layout/HashAlignment` cop, auto-correction can break the page and render a syntax error.

## Expected behavior

Original code:
```ruby
some_method(a: 'abc', b: 'abc',
        c: 'abc', d: 'abc'
        )
```

Expected output:
```ruby
some_method(:a => 'abc', :b => 'abc',
            :c => 'abc', :d => 'abc'
        )
  end
```

## Actual behavior

Actual output:

```ruby
some_method(:a => 'abc', :b => 'abc',
        :    c => 'abc', :d => 'abc'
        )
```

## Steps to reproduce the problem

Running `rubocop -a` on the above code will replicate the problem.

## RuboCop version

```
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.7.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #8347.

This PR fixes an incorrect auto-correct for `EnforcedStyle: hash_rockets` of `Style/HashSyntax` with `Layout/HashAlignment`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cli/cli_autocorrect_spec.rb [hunk 1]
```diff
@@ -174,6 +174,28 @@ def batch
...
+                     '--auto-correct-all',
+                     '--only', 'Style/HashSyntax,Style/HashAlignment'
+                   ])).to eq(0)
+    expect(IO.read('example.rb')).to eq(<<~RUBY)
+      some_method(:a => 'abc', :b => 'abc',
+                  :c => 'abc', :d => 'abc'
+              )
+    RUBY
+  end
+
```
Comment (dorner) [inline spec/rubocop/cli/cli_autocorrect_spec.rb:198]: Amazing - I just spent about four hours trying to get this to work via way overcomplicating the `expect_correction` method (basically by adding a `let(:run_first)` variable). This is a million times cleaner. :) Going to miss having a PR to Rubocop but I guess I'll have other opportunities!

Comment (marcandre) [reply spec/rubocop/cli/cli_autocorrect_spec.rb:198]: I'm curious: what was the difficulty with `expect_correction`? This test with the CLI is much slower...

Comment (dorner) [reply spec/rubocop/cli/cli_autocorrect_spec.rb:198]: The issue is that you can only run one cop at a time. There's no easy way to pass it multiple cops to run one after another. This bug only happens when one cop makes a change and the next one makes a second change - the two insertions end up in an invalid state.

Comment (marcandre) [reply spec/rubocop/cli/cli_autocorrect_spec.rb:198]: I was under the impression that `let(:other_cops) { { 'Other/Cop' => ... } }` was the way to go, but indeed looks like it's not the case. I opened #8352 as it should be easily doable to specify additional cops.

**Comment by bbatsov** [comment]
Thanks!
