### PR TITLE
[Fix #7616] Fix an incorrect autocorrect for `Style/MultilineWhenThen`

### LINKED ISSUE #7616: Style/MultilineWhenThen breaks case statements with {}
## Expected behavior

The Style/MultilineWhenThen cop should remove then statements from all mulitline case statements w/o creating invalid ruby code.

## Actual behavior

If RuboCop encounters a case statement that uses then and {}s it will just remove the then statements, which results in invalid ruby:

## Steps to reproduce the problem

Run `rubocop --only Style/MultilineWhenThen` on the following code:

```ruby
      case version.to_s # to_s to make sure someone didn't pass us an int
      when '9.0' then {
        'ActiveDirectory' => 'Veeam Explorer for Microsoft Active Directory',
        'SQL' => 'Veeam Explorer for Microsoft SQL Server',
        'Exchange' => 'Veeam Explorer for Microsoft Exchange',
        'SharePoint' => 'Veeam Explorer for Microsoft SharePoint',
        'Oracle' => 'Veeam Explorer for Oracle'
      }
     end
```

This will autocorrect to:

```ruby
      case version.to_s # to_s to make sure someone didn't pass us an int
      when '9.0' {
        'ActiveDirectory' => 'Veeam Explorer for Microsoft Active Directory',
        'SQL' => 'Veeam Explorer for Microsoft SQL Server',
        'Exchange' => 'Veeam Explorer for Microsoft Exchange',
        'SharePoint' => 'Veeam Explorer for Microsoft SharePoint',
        'Oracle' => 'Veeam Explorer for Oracle'
      }
     end
```

## RuboCop version

```
0.78.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7616.

This PR fixes an incorrect autocorrect for `Style/MultilineWhenThen` for when statement with then is an array or a hash.

The following is a reproduction procedure.

```console
% cat example.rb
case condition
when foo then {
    key: 'value'
  }
end

% ruby -c example.rb
Syntax OK
```

It is changed to the code with syntax error as follows.

```console
% bundle exec rubocop -a --only Style/MultilineWhenThen
(snip)

% cat example.rb
case condition
when foo {
    key: 'value'
  }
end

% ruby -c example.rb
example.rb:3: syntax error, unexpected ':', expecting '}'
    key: 'value'
example.rb:4: syntax error, unexpected '}', expecting end-of-input
```

The same is true when replacing a hash with an array.
The PR will accept these cases without offense.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/multiline_when_then.rb [hunk 1]
```diff
@@ -35,7 +35,7 @@ def on_when(node)
           return if !node.children.last.nil? && !node.multiline? && node.then?
 
           # With more than one statements after then, there's not offense
-          return if node.children.last&.begin_type?
+          return if accept_node_type?(node.children.last)
```
Comment (buehmann) [inline lib/rubocop/cop/style/multiline_when_then.rb]: How about `node.body` instead of `node.children.last`?

File: spec/rubocop/cop/style/multiline_when_then_spec.rb [hunk 2]
```diff
@@ -57,6 +57,26 @@
     RUBY
   end
 
+  it 'does not register an offense for hash when statement without then' do
```
Comment (buehmann) [inline spec/rubocop/cop/style/multiline_when_then_spec.rb]: Why `without then`?

File: spec/rubocop/cop/style/multiline_when_then_spec.rb [hunk 3]
```diff
@@ -57,6 +57,26 @@
...
+    expect_no_offenses(<<~RUBY)
+      case condition
+      when foo then {
+          key: 'value'
+        }
+      end
+    RUBY
+  end
+
+  it 'does not register an offense for array when statement without then' do
```
Comment (buehmann) [inline spec/rubocop/cop/style/multiline_when_then_spec.rb]: Same here.

File: lib/rubocop/cop/style/multiline_when_then.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/style/multiline_when_then.rb]: That is more readable. Thanks!

**Comment by Drenmi** [comment]
I was expecting the fix to be:

```ruby
case condition
when foo
  {
    key: 'value'
  }
end
```

bur I think the code for that might get a bit more gnarly. 🙂

**Comment by koic** [comment]
Thanks for the advice. I'd like to prioritize that broken Ruby code cannot be corrected by auto-correction. I think the next step (another PR) would be the auto-correction that matched this cop.

**Comment by tas50** [comment]
Thanks for the quick fix @koic
