### PR TITLE
[Fix #7253] Fix an error for `Lint/NumberConversion`

### LINKED ISSUE #7253: Lint/NumberConversion: Exception when `to_i` is called without a receiver
Lint/NumberConversion cop throws an exception (`undefined method `source' for nil:NilClass`) when `to_i` is called without an explicit receiver

--------

## Expected behavior

Rubocop should not throw an exception and should not find any offenses

## Actual behavior

```
$ rubocop -d --only Lint/NumberConversion time_ext.rb
Inspecting 1 file
Scanning ~/rubocop-number-conversion-bug/time_ext.rb
An error occurred while Lint/NumberConversion cop was inspecting ~/rubocop-number-conversion-bug/time_ext.rb:3:4.
undefined method `source' for nil:NilClass
~/.rvm/gems/ruby-2.4.0/gems/rubocop-0.74.0/lib/rubocop/cop/lint/number_conversion.rb:48:in `block in on_send'
~/.rvm/gems/ruby-2.4.0/gems/rubocop-0.74.0/lib/rubocop/cop/lint/number_conversion.rb:39:in `to_method'
~/.rvm/gems/ruby-2.4.0/gems/rubocop-0.74.0/lib/rubocop/cop/lint/number_conversion.rb:43:in `on_send'
~/.rvm/gems/ruby-2.4.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
[etc...]

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Lint/NumberConversion cop was inspecting ~/rubocop-number-conversion-bug/time_ext.rb:3:4.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.74.0 (using Parser 2.6.3.0, running on ruby 2.4.0 x86_64-linux)
Finished in 0.13494850002462044 seconds
```

## Steps to reproduce the problem

```
$ cat time_ext.rb 
class Time
  def mod(modulus)
    to_i % modulus
  end
end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.4.0 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7253.

This PR fixes an error for `Lint/NumberConversion` when `#to_i` called without a receiver.

```ruby
# example.rb
class Time
  def mod(modulus)
    to_i % modulus
  end
end
```

```console
% rubocop --only Lint/NumberConversion -d
For /Users/koic/src/github.com/koic/rubocop-issues/7253: configuration
from /Users/koic/src/github.com/koic/rubocop-issues/.rubocop.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.4.1/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.4.1/config/default.yml
Default configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-0.73.0/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.1.0/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-rails-2.1.0/config/default.yml
Inspecting 1 file
Scanning /Users/koic/src/github.com/koic/rubocop-issues/7253/example.rb
An error occurred while Lint/NumberConversion cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7253/example.rb:3:4.
undefined method `source' for nil:NilClass
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-0.73.0/lib/rubocop/cop/lint/number_conversion.rb:48:in
`block in on_send'
```

This PR accepts `to_i` when called without a receiver.

As an alternative, I thought about auto-correcting to `Integer (self, 10)`. However, type of `self` depends on the context. For example, the following error occurs when `self` is a `Time` object:

```ruby
class Time
  def do_something
    Integer(self, 10)
  end
end

Time.new.do_something # ArgumentError (base specified for non string value)
```

This has the same meaning as:

```ruby
Integer(Time.new, 10) # ArgumentError (base specified for non string value)
```

So I decided to leave it as `#to_i` when a receiver wasn't called.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/number_conversion.rb [hunk 1]
```diff
@@ -41,7 +41,7 @@ class NumberConversion < Cop
 
         def on_send(node)
           to_method(node) do |receiver, to_method|
-            next if date_time_object?(receiver)
+            next if receiver.nil? || date_time_object?(receiver)
```
Comment (mikegee) [inline lib/rubocop/cop/lint/number_conversion.rb]: Shouldn't `date_time_object?(nil)` be `false`? 🤔
