### PR TITLE
Remove `Lint/EndInMethod` cop

### LINKED ISSUE #7813: `Style/EndBlock` & `Lint/EndInMethod` are redundant
Both `Style/EndBlock` & `Lint/EndInMethod` do the same thing. `END` block being inside/outside method makes no difference.

Both were added long back in [0.9.0](https://github.com/rubocop-hq/rubocop/blob/v0.9.0/CHANGELOG.md). 

Commits don't tell the reasoning either: [[1]](https://github.com/rubocop-hq/rubocop/commit/080be429984a93c3d5b1033f8371a7d13f14043c) & [[2]](https://github.com/rubocop-hq/rubocop/commit/8466928ad6793532136ba58324f8a3a21e01cee8)

Also the documentation of `Lint/EndInMethod` suggests `END` outside method is `good` which contradicts `Style/EndBlock`.

--------

## Expected behavior

One cop to deal with `END` blocks.

## Actual behavior

Duplicate cops.

## Steps to reproduce the problem

NA

## RuboCop version

Current master branch.

### PR DESCRIPTION
**Pull request by tejasbubane**
In favor of `Style/EndBlock`.

Closes #7813

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
Can you add the cop to `RuboCop::ConfigObsoletion::REMOVED_COPS`?

```diff
     REMOVED_COPS = {
       'Layout/SpaceAfterControlKeyword' => 'Layout/SpaceAroundKeyword',
       'Layout/SpaceBeforeModifierKeyword' => 'Layout/SpaceAroundKeyword',
+      'Lint/EndInMethod' => nil,
       'Lint/RescueWithoutErrorClass' => 'Style/RescueStandardError',
       'Rails/DefaultScope' => nil,
       'Style/SpaceAfterControlKeyword' => 'Layout/SpaceAroundKeyword',
       'Style/SpaceBeforeModifierKeyword' => 'Layout/SpaceAroundKeyword',
      'Style/TrailingComma' => 'Style/TrailingCommaInArguments, ' \
                                'Style/TrailingCommaInArrayLiteral, and/or ' \
                                'Style/TrailingCommaInHashLiteral',
       'Style/TrailingCommaInLiteral' => 'Style/TrailingCommaInArrayLiteral ' \
                                         'and/or ' \
                                         'Style/TrailingCommaInHashLiteral',
       'Style/BracesAroundHashParameters' => nil
     }.map do |old_name, other_cops|
```

https://github.com/rubocop-hq/rubocop/blob/v0.80.1/lib/rubocop/config_obsoletion.rb#L60

File: lib/rubocop/config_obsoletion.rb [hunk 1]
```diff
@@ -19,6 +19,7 @@ class ConfigObsoletion
       'Layout/LeadingBlankLines' => 'Layout/LeadingEmptyLines',
       'Layout/TrailingBlankLines' => 'Layout/TrailingEmptyLines',
       'Lint/DuplicatedKey' => 'Lint/DuplicateHashKey',
+      'Lint/EndInMethod' => 'Style/EndBlock',
```
Comment (koic) [inline lib/rubocop/config_obsoletion.rb]: Can you arrange them in ASCII order?

```suggestion
      'Lint/EndInMethod' => 'Style/EndBlock',
      'Lint/DuplicatedKey' => 'Lint/DuplicateHashKey',
```

Comment (koic) [reply lib/rubocop/config_obsoletion.rb]: Oh, this is my mistake 💦

**Comment by koic** [comment]
Thanks!
