### PR TITLE
[Fix #7367] Fix an error for `Style/OrAssignment`

### LINKED ISSUE #7367: Style/OrAssignment :  undefined method `source' for nil:NilClass
## Steps to reproduce the problem

```
$ cat test.rb
kbv = 1
if kbv
  #dont do anything
else
  kbv = 2
end
```

```
$ rubocop --auto-correct --only Style/OrAssignment test.rb
Inspecting 1 file
An error occurred while Style/OrAssignment cop was inspecting test.rb:2:0.
To see the complete backtrace run rubocop -d.


0 files inspected, no offenses detected


undefined method `source' for nil:NilClass
/rubocop-0.74.0/lib/rubocop/cop/style/or_assignment.rb:72:in `block in autocorrect'
/rubocop-0.74.0/lib/rubocop/cop/cop.rb:36:in `call'
/rubocop-0.74.0/lib/rubocop/cop/corrector.rb:63:in `block (2 levels) in rewrite'
```

## RuboCop version

```
0.74.0 (using Parser 2.6.4.1, running on ruby 2.3.3 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7367.

This PR fixes an error for `Style/OrAssignment` cop when `then` branch body is empty.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/or_assignment.rb [hunk 1]
```diff
@@ -81,7 +81,12 @@ def take_variable_and_default_from_ternary(node)
         end
 
         def take_variable_and_default_from_unless(node)
-          variable, default = *node.if_branch
+          if node.if_branch
+            variable, default = *node.if_branch
```
Comment (Drenmi) [inline lib/rubocop/cop/style/or_assignment.rb]: Interesting. I thought this would trigger another cop, that would suggest:

```ruby
variable, default = if node.if_branch
                      *node.if_branch
                    else
                      *node.else_branch
                    end
```

Maybe a false negative in that other cop? 🙂

Comment (koic) [reply lib/rubocop/cop/style/or_assignment.rb]: This syntax is a syntax error. I learned at that time :-)

```console
% cat example.rb
variable, default = if node.if_branch
                      *node.if_branch
                    else
                      *node.else_branch
                    end

% ruby -c example.rb
example.rb:2: syntax error, unexpected '\n', expecting '='
example.rb:4: syntax error, unexpected '\n', expecting '='
```

Comment (Drenmi) [reply lib/rubocop/cop/style/or_assignment.rb]: Oh. Even more interesting. I only tested using this:

```ruby
a, b = if foo; c; else; d; end
```

which works. 😂

Comment (koic) [reply lib/rubocop/cop/style/or_assignment.rb]: I got a syntax error in my environment 🤔 

```console
% rbenv each ruby -e 'a, b = if foo; *c; else; *d; end'

(snip)

SyntaxError: -e:1: syntax error, unexpected ';'
a, b = if foo; *c; else; *d; end
                 ^
FAILED IN: 1.8.7-p375 1.9.3-p551 2.0.0-p648 2.1.10 2.2.10 2.2.2 2.3.5 2.3.7 2.4.1 2.4.6 2.4.7 2.5.0-dev 2.5.0-gcc4 2.5.6 2.6.0-dev 2.6.4 2.7.0-dev jruby-1.7.19 jruby-9.0.5.0 jruby-9.1.17.0 jruby-9.2.7.0 jruby-9.2.8.0
```

Comment (Drenmi) [reply lib/rubocop/cop/style/or_assignment.rb]: Strange. Now I'm getting the same thing. 🤔 Maybe need more coffee. ☕️

File: CHANGELOG.md [hunk 2]
```diff
@@ -34,6 +34,7 @@
 * [#7353](https://github.com/rubocop-hq/rubocop/issues/7353): Fix a false positive for `Style/RedundantSelf` when a self receiver is used as a method argument. ([@koic][])
 * [#7358](https://github.com/rubocop-hq/rubocop/issues/7358): Fix an incorrect autocorrect for `Style/NestedModifier` when parentheses are required in method arguments. ([@koic][])
 * [#7361](https://github.com/rubocop-hq/rubocop/issues/7361): Fix a false positive for `Style/TernaryParentheses` when only the closing parenthesis is used in the last line of condition. ([@koic][])
+* [#7367](https://github.com/rubocop-hq/rubocop/issues/7367): Fix an error for `Style/Assignment` cop when `then` branch body is empty. ([@koic][])
```
Comment (buehmann) [inline CHANGELOG.md]: The cop is called `OrAssignment`.

Comment (koic) [reply CHANGELOG.md]: Oops! Thanks!

File: lib/rubocop/cop/style/or_assignment.rb (hunk 1 above)
Comment (rrosenblum) [reply lib/rubocop/cop/style/or_assignment.rb]: > I thought this would trigger another cop

Ignoring that in this case a syntax error occurs, `Style/ConditionalAssignment` comes close to checking for this, but I think it only looks for a single variable. There is an explicit check that the assignment isn't mass assignment.


```ruby
        def allowed_statements?(branches)
          return false unless branches.all?

          statements = branches.map { |branch| tail(branch) }.compact

          lhs_all_match?(statements) && statements.none?(&:masgn_type?) &&
            assignment_types_match?(*statements)
        end
```

We certainly could add the functionality, but we'll need to remember to not flag splat expansion for correction.

Side note: There are some other "assignment" types that this cop could check for as well. The other "assignment" types are really operators such as `+` or `-`. I think I left them out because of potential confusion over the name of the cop and what it would be recommending. It would be similar to how the cop supports `=~`, `!~`, and `<=>`.

**Comment by bbatsov** [comment]
Thanks!
