### PR TITLE
[Fix #9349] Fix a false positive for `Lint/MultipleComparison`

### LINKED ISSUE #9349: Lint/MultipleComparison should not be marked safe
I am using a SQL query dsl with code like this:

```ruby
query.where { date >= range.begin & date < range.end }
```

rubocop autocorrects this to:

```ruby
query.where { date >= range.begin & date && range.begin & date < range.end }
```

which has different semantics.

(see follow-up comment for my original error here^^ 🤦)

--------

## Expected behavior

This cop seems to make wrong assumptions about the safety of operating on relational operators. Whatever the case may be, this should not change my code to something that could be semantically different (by default).

## Actual behavior

It autocorrects to semantically different code as outlined above.

## Steps to reproduce the problem

Run `rubocop -a` on source files with the snippets above.

## RuboCop version

```
1.7.0 (using Parser 3.0.0.0, rubocop-ast 1.3.0, running on ruby 2.6.6 x86_64-darwin19)
  - rubocop-performance 1.9.2
  - rubocop-rspec 2.1.0
  - rubocop-rspec 2.1.0
```

Side note: that duplicate `rubocop-rspec` is not a typo, that's what the command outputs. Not sure if there's something wrong there as well or some quirk to my config^

### PR DESCRIPTION
**Pull request by koic**
Fixes #9349.

This PR fixes a false positive for `Lint/MultipleComparison` when using `&`, `|`, and `^` (DSL) set operation operators.

e.g. `Arel::Match`'s DSL methods.
https://github.com/rails/rails/blob/v6.1.1/activerecord/lib/arel/math.rb#L21-L23

I think that the cop can probably allow using these operators by default.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
And I added a commit to this PR that marks `Lint/MultipleComparison` as unsafe auto-correction because comparison of `1 < 2 < 3` is an error of `true < 3` and is semantically behaviour different from `1 < 2 && 2 < 3`.
https://github.com/rubocop-hq/rubocop/issues/9349#issuecomment-756569781

File: lib/rubocop/cop/lint/multiple_comparison.rb [hunk 1]
```diff
@@ -7,25 +7,26 @@ module Lint
       # multiple value. However, we can't use the comparison in Ruby. However,
       # the comparison is not syntax error. This cop checks the bad usage of
       # comparison operators.
+      # It allows multiple comparison using `&`, `|`, and `^` set operation operators.
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/multiple_comparison.rb:10]: I'm a bit confused why this is a problem at all - looking at the defintion of the cop it shouldn't be looking at something like this at all. (unless I'm missing the point here)

File: lib/rubocop/cop/lint/multiple_comparison.rb [hunk 2]
```diff
@@ -7,25 +7,26 @@ module Lint
...
+      #
+      # The cop is marked as unsafe auto-correction because comparison of `1 < 2 < 3` is
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/multiple_comparison.rb:12]: I think this example is confusing - I get it, but I don't get how is it relevant to the cop and its safety. It'd be better to illustrate this with some case where it's more obvious that someone intentially wanted a chain a comparsion ops.

File: lib/rubocop/cop/lint/multiple_comparison.rb [hunk 3]
```diff
@@ -34,6 +35,7 @@ class MultipleComparison < Base
 
         def on_send(node)
           return unless (center = multiple_compare?(node))
+          return if center.send_type? && SET_OPERATION_OPERATORS.include?(center.method_name)
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/multiple_comparison.rb:38]: I think we'll definitely have to explain here, why those set operations matter at all.

**Comment by bbatsov** [comment]
@koic Don't forget about this PR. Basically right now I'm not quite sure why we need any sort of handling for set operators, so some more explanations would be useful. Is this PR adding support for them just for the sake of Arel's DSL? Shouldn't we make this some configuration in this case - after all if you're not using Arel, treating them as logical operators doesn't make sense.

**Comment by koic** [comment]
I'm sorry I was late to come back to this PR. I rethinked that Arel's specific issue handling can only be configured in RuboCop Rails. Also, it was not good option to mark as unsafe about non-working code `1 > 2 > 3` will work by auto-correction.
So, I have reverted the `SafeAutoCorrect` configuration change in the PR, and leaving only a fix to a false positive for `x> y & y> z` that should not be registered offense.

**Comment by bbatsov** [comment]
Thanks!
