### PR TITLE
[Fix #7397] Fix issue where Style/SafeNavigation adds extra comments

### LINKED ISSUE #7397: Style/SafeNavigation adding broken comments, no output to console regarding this.
## Expected behavior

I run `rubocop -a some/file.rb`, I expect some violations to be automatically corrected.

## Actual behavior

The violations are automatically corrected but it takes a multiline comment and replicates between the "ifs" and their conditions

## Steps to reproduce the problem
`some/file.rb` example:

Before

```
class SomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :authenticate_user!, :authenticate_role, except: [
    :check,
    :check_codes,
    :fetch_actionable]

  # returns guest.credits based on total and dates
  # decorates with balance and pretty_name
  # includes credits total
  def fetch_actionable
    current_daily_pricing = params[:dailyRates].values

    if current_daily_pricing.all? { |r| r != 'x' }
      guest = Guest.find_by(email: params[:email])
      @credits = Credit::Calculator.new(guest.credits).fetch_actionable(
        params[:check_in],
        params[:check_out],
        params[:dailyRates],
        params[:email],
        params[:subtotal]
      )

      if guest && guest.valid_token?(params[:access_token], params[:client]) && @credits
        @credits_total = 0
        @credits_total = @credits.inject(0) do |sum, credit|
          next unless credit[:balance]
          sum + credit[:balance]
        end

        render json: {
          updated_credits: @credits,
          credits_total:   @credits_total
        }
      end

    else
      render json: {
        error: 'no_availability'
      }
    end
  end
end
```

after: (Notice the duplicated comment between the "if" and it's condition
```
class SomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :authenticate_user!, :authenticate_role, except: %i[
    check
    check_codes
    fetch_actionable
  ]

  # returns guest.credits based on total and dates
  # decorates with balance and pretty_name
  # includes credits total
  def fetch_actionable
    current_daily_pricing = params[:dailyRates].values

    if current_daily_pricing.all? { |r| r != 'x' }
      guest = Guest.find_by(email: params[:email])
      @credits = Credit::Calculator.new(guest.credits).fetch_actionable(
        params[:check_in],
        params[:check_out],
        params[:dailyRates],
        params[:email],
        params[:subtotal]
      )

      if # returns guest.credits based on total and dates
# decorates with balance and pretty_name
# includes credits total
guest&.valid_token?(params[:access_token], params[:client]) && @credits
        @credits_total = 0
        @credits_total = @credits.inject(0) do |sum, credit|
          next unless credit[:balance]

          sum + credit[:balance]
        end

        render json: {
          updated_credits: @credits,
          credits_total: @credits_total
        }
      end

    else
      render json: {
        error: 'no_availability'
      }
    end
  end
end
```

## RuboCop version
0.75.0 (using Parser 2.6.5.0, running on ruby 2.6.5 x86_64-darwin16)
(Also tried with 0.69)

## .rubocop.yml

```
Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
```

If I add

```
Style/SafeNavigation
  Enabled: false
```

The problem disappears

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #7397 

When moving comments around, the original implementation failed to limit the comments to the section of code being analyzed. It was pulling the comments for the entire file.

### CODE REVIEW

File: spec/rubocop/cop/style/safe_navigation_spec.rb [hunk 1]
```diff
@@ -950,6 +950,26 @@
...
+                #{variable}.bar
+              end
+            end
+          RUBY
+
+          expect(new_source).to eq(<<~RUBY)
+            # comment one
+            def foobar
+              # comment 2
+            #{variable}&.bar
```
Comment (rrosenblum) [inline spec/rubocop/cop/style/safe_navigation_spec.rb]: This indentation seems a little weird because I think this is only place where it appears off. `Layout/IndentationWidth` will take care of this though.

Comment (rrosenblum) [reply spec/rubocop/cop/style/safe_navigation_spec.rb]: I think this would have happened before my change as well.

**Comment by koic** [comment]
Thanks!
