### PR TITLE
[Fix #6067] Prevent auto-correct error for `Performance/InefficientHashSearch`

### LINKED ISSUE #6067: Performance/InefficientHashSearch auto-correct fails with undefined method `loc' for nil:NilClass
Rubcop fails to auto-correct Performance/InefficientHashSearch, _probably_ it happens when array has name `keys`.

--------

## Expected behavior

rubocop auto-fixes code

## Actual behavior

rubocop crashes

## Steps to reproduce the problem

```
$ cat rubocop_example.rb 

def keys
  []
end

def my_include?(key)
  keys.include?(key)
end
```

```
$ rubocop --debug --auto-correct rubocop_example.rb --only Performance/InefficientHashSearch 

For /Users/bayandin: configuration from /usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/config/default.yml
Inheriting configuration from /usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/config/enabled.yml
Inheriting configuration from /usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/config/disabled.yml
Inspecting 1 file
Scanning /Users/bayandin/rubocop_example.rb


0 files inspected, no offenses detected
undefined method `loc' for nil:NilClass
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/performance/inefficient_hash_search.rb:90:in `autocorrect_hash_expression'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/performance/inefficient_hash_search.rb:54:in `block in autocorrect'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:61:in `block (2 levels) in rewrite'
/usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/source/tree_rewriter.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:60:in `block in rewrite'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:58:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:58:in `rewrite'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:70:in `autocorrect'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:98:in `block in offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:115:in `investigate'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:94:in `offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:44:in `inspect_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:265:in `inspect_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:237:in `loop'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:208:in `do_inspection_loop'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:111:in `block in file_offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:129:in `file_offense_cache'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:109:in `file_offenses'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:100:in `process_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `reduce'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `each_inspected_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:67:in `inspect_files'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:39:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:160:in `execute_runner'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:88:in `execute_runners'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/exe/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.57.2/exe/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
Finished in 0.3469570000306703 seconds
```

## RuboCop version

```
$ rubocop -V
0.57.2 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6067.

This PR prevents an auto-correct error for `Performance/InefficientHashSearch` when a method defined by itself and `include?` method are method chaining.

Essentially, static analysis targeted by RuboCop does not know the type determined at run-time.

So, this implementation may be false negative if it defines method itself.

```ruby
def keys
  # When delegation instead of an array,
  # it does not know the type until run-time.
  []
end

def my_include?(key)
  keys.include?(key)
end
```

If the above `keys` method defined by itself will return a Hash, it will be false negative, so there is room for improvement in the future.

The aim of this change is to make it more valuable to prevent auto-correct error than false negative.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/performance/inefficient_hash_search.rb [hunk 1]
```diff
@@ -42,7 +42,10 @@ class InefficientHashSearch < Cop
         PATTERN
 
         def on_send(node)
-          add_offense(node, message: msg(node)) if inefficient_include?(node)
+          return unless inefficient_include?(node)
+          return if node.children[0].receiver.nil?
```
Comment (bbatsov) [inline lib/rubocop/cop/performance/inefficient_hash_search.rb]: I'd use node destructuring here to highlight what `node.children[0]` stands for.

File: spec/rubocop/cop/performance/inefficient_hash_search_spec.rb [hunk 2]
```diff
@@ -47,6 +47,15 @@
       RUBY
     end
 
+    it 'does not register an offense when `keys` method defined by itself ' \
+       'and `include?` method are method chaining' do
```
Comment (bbatsov) [inline spec/rubocop/cop/performance/inefficient_hash_search_spec.rb]: You'll have to update this in the new project as well, to keep in sync with this one.

File: lib/rubocop/cop/performance/inefficient_hash_search.rb (hunk 1 above)
Comment (Drenmi) [reply lib/rubocop/cop/performance/inefficient_hash_search.rb]: Or node extensions. 😬

File: lib/rubocop/cop/performance/inefficient_hash_search.rb [hunk 3]
```diff
@@ -87,7 +90,7 @@ def autocorrect_argument(node)
         end
 
         def autocorrect_hash_expression(node)
-          node.children[0].children[0].loc.expression.source
+          node.children[0].receiver.loc.expression.source
```
Comment (Drenmi) [inline lib/rubocop/cop/performance/inefficient_hash_search.rb]: You can probably use just `Node#source`, which is an alias for `loc.expression.source`. (Internal investigation incoming. 😉)

File: lib/rubocop/cop/performance/inefficient_hash_search.rb (hunk 1 above)
Comment (Drenmi) [reply lib/rubocop/cop/performance/inefficient_hash_search.rb]: You can actually make this part of the node pattern:

```ruby
def_node_matcher :inefficient_include?, <<-PATTERN
  (send $(send !nil? ${:keys :values}) :include? $_)
PATTERN
```

In all other places, `children[0]` can be replaces with `receiver`, because we're dealing with `send` nodes throughout.

File: lib/rubocop/cop/performance/inefficient_hash_search.rb [hunk 4]
```diff
@@ -42,7 +42,10 @@ class InefficientHashSearch < Cop
         PATTERN
 
         def on_send(node)
-          add_offense(node, message: msg(node)) if inefficient_include?(node)
+          return unless inefficient_include?(node)
+          return if node.children[0].receiver.nil?
+
+          add_offense(node, message: msg(node))
```
Comment (Drenmi) [inline lib/rubocop/cop/performance/inefficient_hash_search.rb]: Perhaps you could also rename `#msg` -> `#message` and remove the argument from the call to `add_offense`? 🙂

File: spec/rubocop/cop/performance/inefficient_hash_search_spec.rb (hunk 2 above)
Comment (koic) [reply spec/rubocop/cop/performance/inefficient_hash_search_spec.rb]: Sure. I plan to port to rubocop-performance repo.

File: lib/rubocop/cop/performance/inefficient_hash_search.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/performance/inefficient_hash_search.rb]: Thanks for review. And I noticed some unnecessary capture, so I removed them.

**Comment by koic** [comment]
I updated this PR. Thanks for the review.

File: spec/rubocop/cop/performance/inefficient_hash_search_spec.rb (hunk 2 above)
Comment (composerinteralia) [reply spec/rubocop/cop/performance/inefficient_hash_search_spec.rb]: I am already doing some work on rubocop-performance today, so I added the spec in https://github.com/rubocop-hq/rubocop-performance/pull/12. I haven't imported the cops yet, but will make sure I get the latest version when I do.
