### PR TITLE
[Fix #6858] Fix an incorrect auto-correct for `Lint/ToJSON`

### LINKED ISSUE #6858: Lint/ToJSON suggest wrong code
## Expected behavior

With following suggestion at `Lint/ToJSON`, not raise error.
https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/to_json.rb#L17

```
@example
  # bad
  def to_json
  end

  # good
  def to_json(_opts)
  end
```

## Actual behavior

Because I get `Lint/ToJSON`, I changed my code like below

```rb
# Before
class Ex
  def to_json
    {a: 1}.to_json
  end
end

# After
class Ex
  def to_json(_opts)
    {a: 1}.to_json
  end
end
```

Then, `Ex.new.to_json` start raising error saying `ArgumentError: wrong number of arguments (given 0, expected 1)`

As talked https://github.com/rubocop-hq/rubocop/pull/6379#discussion_r236021167, document should suggest the argument to be optional

## RuboCop version

```
$ bundle exec rubocop -V
0.66.0 (using Parser 2.6.0.0, running on ruby 2.4.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6858.

I think it was a mistake of multiple arguments.

## Before

```ruby
def to_json(_opts)
end
```

## After

```ruby
def to_json(*args)
end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/to_json.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def on_def(node)
 
         def autocorrect(node)
           lambda do |corrector|
-            corrector.insert_after(node.loc.name, '(_opts)')
+            corrector.insert_after(node.loc.name, '(*args)')
```
Comment (pocke) [inline lib/rubocop/cop/lint/to_json.rb]: `def to_json(*args)` has an offense of `Lint/UnusedMethodArgument` cop if `args` is not used.
So I think it should be named `_args`.

Comment (koic) [reply lib/rubocop/cop/lint/to_json.rb]: Sure! I updated it and added a source code comment.
