### PR TITLE
[Fix #9050] Fix a false positive for `Style/NegatedIfElseCondition`

### LINKED ISSUE #9050: Style/NegatedIfElseCondition: False positive on `if !!`
Using `!!` isn't negation, it's conversion to Boolean. So this should be valid code:

```ruby
if !!my_method_or_variable
  "true condition"
else
  "false condition"
end

# Fails with:
Style/NegatedIfElseCondition: Invert the negated condition and swap the if-else branches.
  if !!my_method ...
  ^^^^^^^^^^^^^^
```

--------

## Expected behavior

Don't fail when `!!` is used in an if/else block. i.e. this should be valid:

```ruby
if !!my_method_or_variable
  "true condition"
else
  "false condition"
end
```

## Actual behavior

The Style/NegatedIfElseCondition cop fails with:
> Style/NegatedIfElseCondition: Invert the negated condition and swap the if-else branches

## Steps to reproduce the problem

Add an if/else such as the following to a ruby file and run the Style/NegatedIfElseCondition cop:

```ruby
if !!my_method
  "a"
else
  "b"
end
```

## RuboCop version

```
$ rubocop -V
1.3.0 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.6.6 x86_64-darwin19)
  - rubocop-performance 1.8.1
  - rubocop-rails 2.8.1
  - rubocop-rake 0.5.1
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #9050.

This PR fixes a false positive for `Style/NegatedIfElseCondition` when `if` with `!!` condition'.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/negated_if_else_condition.rb [hunk 1]
```diff
@@ -35,6 +35,8 @@ class NegatedIfElseCondition < Base
 
         NEGATED_EQUALITY_METHODS = %i[!= !~].freeze
 
+        def_node_matcher :double_negative?, '(send (send _ :!) :!)'
```
Comment (bbatsov) [inline lib/rubocop/cop/style/negated_if_else_condition.rb:38]: Let's name this `double_negation?` to be consistent with the terminology we've used so far.

Comment (koic) [reply lib/rubocop/cop/style/negated_if_else_condition.rb]: Sure! I updated it.
