### PR TITLE
[Fix #7434] Fix an incorrect autocorrect for `Style/MultilineWhenThen`

### LINKED ISSUE #7434: Style/MultilineWhenThen autocorrect generates invalid Ruby for certain case statements
The autocorrect for `Style/MultilineWhenThen` generates invalid ruby when correcting a case statement with the following format (`then` on the line after the `when`):

```
case foo
when :bar
  then :value
```

Definitely not a standard way to write a case statement but it is valid Ruby.

--------

## Full Example code:

```
def flavor(flave)
  case flave
  when 'chocolate'
    then %w[dark white milk].sample
  when 'fruit'
    then %w[apple banana orange].sample
  when 'null'
    then nil
  end
end
```

## Expected behavior

I would expect autocorrect to just remove the unnecessary `then` like so:

```
def flavor(flave)
  case flave
  when 'chocolate'
   %w[dark white milk].sample
  when 'fruit'
   %w[apple banana orange].sample
  when 'null'
   nil
  end
end
```

## Actual behavior

Instead, what we get is invalid ruby:

```
def flavor(flave)
  case flave
  when 'chocolate' %w[dark white milk].sample
  when 'fruit' %w[apple banana orange].sample
  when 'null' nil
  end
end
```

## Steps to reproduce the problem

The sample code provided above can reproduce the problem.

## RuboCop version

```
0.75.1 (using Parser 2.6.5.0, running on ruby 2.4.2 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7434.

This PR fixes an incorrect autocorrect for `Style/MultilineWhenThen` when the body of `when` branch starts with `then`.

The following is a reproduction procedure.

```console
% cat example.rb
# frozen_string_literal: true

case foo
when bar
  then do_something
end
```

```
% ruby -c example.rb
Syntax OK
```

## Before

```console
% rubocop example.rb
Inspecting 1 file
C

Offenses:

example.rb:5:3: C: Style/MultilineWhenThen: Do not use then for
multiline when statement.
  then do_something
  ^^^^
```

It is changed to the code with syntax error as follows.

```ruby
# frozen_string_literal: true

case foo
when bar do_something
end
```

```console
% ruby -c example.rb
example.rb:4: syntax error, unexpected tIDENTIFIER, expecting do or '{'
or '('
when bar do_something
```

## After

```console
% rubocop example.rb -a
Inspecting 1 file
C

Offenses:

example.rb:5:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 1)
spaces for indentation.
 do_something
^
example.rb:5:3: C: [Corrected] Style/MultilineWhenThen: Do not use then
for multiline when statement.
  then do_something
  ^^^^

1 file inspected, 2 offenses detected, 2 offenses corrected
```

It will be changed to valid Ruby code as follows.

```ruby
# frozen_string_literal: true

case foo
when bar
  do_something
end
```

There is a slight difference in indentation using only this cop. That indentation is corrected using `Layout/IndentationWidth` cop.

```diff
 case foo
 when bar
- do_something
+  do_something
 end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/multiline_when_then_spec.rb [hunk 1]
```diff
@@ -84,4 +84,21 @@
...
+      case foo
+      when bar
+        then do_something
+      end
+    RUBY
+
+    expect(new_source).to eq(<<~RUBY)
+      case foo
+      when bar
+       do_something
```
Comment (koic) [inline spec/rubocop/cop/style/multiline_when_then_spec.rb]: 📝 There is a slight difference in indentation using only this cop. That indentation is corrected using `Layout/IndentationWidth` cop.

**Comment by bbatsov** [comment]
🚀
