### PR TITLE
[Fix #6412] Fix an error when using Ruby 2.6.0-preview2

### LINKED ISSUE #6412: Ruby 2.6.0-preview2 does not support new Psych.safe_load interface.
:wave: Hey folks! I wanted to flag an issue I noticed with #6396. It implements a new interface for `Psych.safe_load` that's landed in Ruby trunk, checking that the active Ruby version is at least 2.6. Unfortunately, the last 2.6 preview passes the version check but does not include the new `Psych` code; running Rubocop under Ruby 2.6.0-preview2 yields an error like this:

```
/usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/2.6.0/psych.rb:313:in `safe_load': unknown keywords: whitelist_classes, whitelist_symbols, aliases, filename (ArgumentError)
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:185:in `yaml_safe_load'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:159:in `load_yaml_configuration'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/rubocop-rspec-1.30.0/lib/rubocop/rspec/inject.rb:8:in `defaults!'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/rubocop-rspec-1.30.0/lib/rubocop-rspec.rb:24:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	from /Users/daniel/Repos/Ignota/structur-api/config/application.rb:21:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /usr/local/rvm/gems/ruby-2.6.0-preview2@structur/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.0-preview2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

I've just installed `ruby-head` for the time being, so this is a pretty low-pressure complaint, but I imagine it's not uncommon for folks to be using the preview rather than a trunk build. Maybe the version check could be stricter?

Thanks for looking into it, and for all your work maintaining Rubocop!

--------

## Expected behavior
Rubocop should load successfully under Ruby 2.6.0-preview2.

## Actual behavior
Rubocop crashes with an error about the keyword arguments passed to `Psych.safe_load`.

## Steps to reproduce the problem
1. Install Ruby 2.6.0-preview2.
2. Attempt to run Rubocop with a custom config file.
3. :boom:

## RuboCop version
```
~ ❯❯❯ rubocop -V
0.60.0 (using Parser 2.5.1.2, running on ruby 2.6.0 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6412.

This PR fixes an `unknown keywords` error when using `Psych.safe_load` with Ruby 2.6.0-preview2.

```console
% ruby -v
ruby 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-darwin17]
% rubocop -V
0.60.0 (using Parser 2.5.1.2, running on ruby 2.6.0 x86_64-darwin17)
% rubocop
unknown keywords: whitelist_classes, whitelist_symbols, aliases, filename
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/2.6.0/psych.rb:313:in `safe_load'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:185:in `yaml_safe_load'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:159:in `load_yaml_configuration'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:40:in `load_file'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:82:in `configuration_from_file'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/config_store.rb:44:in `for'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/cli.rb:187:in `apply_default_formatter'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/lib/rubocop/cli.rb:40:in `run'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/exe/rubocop:13:in `block in <top (required)>'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/koic/.rbenv/versions/2.6.0-preview2/lib/ruby/gems/2.6.0/gems/rubocop-0.60.0/exe/rubocop:12:in `<top (required)>'
/Users/koic/.rbenv/versions/2.6.0-preview2/bin/rubocop:23:in `load'
/Users/koic/.rbenv/versions/2.6.0-preview2/bin/rubocop:23:in `<main>'
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config_loader.rb [hunk 1]
```diff
@@ -184,7 +184,8 @@ def yaml_safe_load(yaml_code, filename)
         if defined?(SafeYAML) && SafeYAML.respond_to?(:load)
           SafeYAML.load(yaml_code, filename,
                         whitelisted_tags: %w[!ruby/regexp])
-        elsif RUBY_VERSION >= '2.6'
+        # Ruby 2.6+
+        elsif Gem::Version.new(Psych::VERSION) >= Gem::Version.new('3.1.0.pre1')
```
Comment (bbatsov) [inline lib/rubocop/config_loader.rb]: Cool version comparison trick! I've never seen this before!

Comment (koic) [reply lib/rubocop/config_loader.rb]: I learned this comparison at https://github.com/rubygems/rubygems/pull/2439/files.
