### PR TITLE
[Fix #6882] Fix an error for `Rails/RedundantAllowNil`

### LINKED ISSUE #6882: Rails/RedundantAllowNil stumbles upon validation
## Actual behavior
Newly added `Rails/RedundantAllowNil` errors out after encountering `validates` keyword
```
5 errors occurred:
An error occurred while Rails/RedundantAllowNil cop was inspecting /home/app/models/user.rb:9:2.
An error occurred while Rails/RedundantAllowNil cop was inspecting /home/app/models/user.rb:10:2.
An error occurred while Rails/RedundantAllowNil cop was inspecting /home/app/models/user.rb:11:2.
An error occurred while Rails/RedundantAllowNil cop was inspecting /home/app/models/user.rb:12:2.
An error occurred while Rails/RedundantAllowNil cop was inspecting /home/app/models/user.rb:13:2.
```

## Steps to reproduce the problem

The file in question `app/models/user.rb`:
```
class User < ApplicationRecord
  belongs_to :account, optional: true

  before_save { self.email = email.downcase }

  has_secure_password
  has_secure_token :confirmation_token

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :email, length: { maximum: 256 }
  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8 }
end
```

## RuboCop version
```
$ [bundle exec] rubocop -V
0.67.0 (using Parser 2.6.2.0, running on ruby 2.6.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6882.

This PR fixes the following error for `Rails/RedundantAllowNil` when not using both `allow_nil` and `allow_blank`.

```ruby
% cat app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
end
```

```console
% rubocop app/models/user.rb --only Rails/RedundantAllowNil -d
For /private/tmp/6882: configuration from
/Users/koic/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rubocop-0.67.1/config/default.yml
Inspecting 1 file
Scanning /private/tmp/6882/app/models/user.rb
An error occurred while Rails/RedundantAllowNil cop was inspecting
/private/tmp/6882/app/models/user.rb:2:2.
undefined method `children' for nil:NilClass
/Users/koic/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rubocop-0.67.1/lib/rubocop/cop/rails/redundant_allow_nil.rb:42:in `on_send'

(snip)

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Rails/RedundantAllowNil cop was inspecting
/private/tmp/6882/app/models/user.rb:2:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.67.1 (using Parser 2.6.2.0, running on ruby 2.6.1 x86_64-darwin17)
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/redundant_allow_nil.rb [hunk 1]
```diff
@@ -39,14 +39,12 @@ def on_send(node)
...
+
           allow_nil_val = allow_nil.children.last
           allow_blank_val = allow_blank.children.last
 
-          if allow_nil_val.type == allow_blank_val.type
-            add_offense(allow_nil, message: MSG_SAME)
-          elsif allow_nil_val.false_type? && allow_blank_val.true_type?
-            add_offense(allow_nil, message: MSG_ALLOW_NIL_FALSE)
-          end
+          offense(allow_nil_val, allow_blank_val, allow_nil)
```
Comment (koic) [inline lib/rubocop/cop/rails/redundant_allow_nil.rb]: 📝 I extracted to the method because it was warned by `Metrics` cops.

**Comment by bbatsov** [comment]
Thanks!
