### PR TITLE
Fix #6022 Avoid MultilineHashBraceLayout auto-correct syntax error

### LINKED ISSUE #6022: Layout/MultilineHashBraceLayout auto-correct syntax error
Hi, I noticed that the auto-correct for `Layout/MultilineHashBraceLayout` sometimes causes syntax errors. This seems to happen when

- the closing `}` is on a new line
- the hash is inside a function call
- the last hash entry ends with a comment

--------

## Expected behavior

Don't introduce syntax errors.

## Actual behavior

Auto-correct for `Layout/MultilineHashBraceLayout` can introduce syntax errors when a line ends with a comment.

## Steps to reproduce the problem

Run ` rubocop --only Layout/MultilineHashBraceLayout --auto-correct test.rb` where `test.rb` is the following file:

```ruby
h = f({ x => 1, # foo
        y => 2, # bar
})
```

This is auto-corrected to the following

```ruby
h = f({ x => 1, # foo
        y => 2,} # bar)
```

Notice that the closing `)` of the function is now after the comment.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.57.1 (using Parser 2.5.1.0, running on ruby 2.4.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by bacchir**
See [#6022](https://github.com/rubocop-hq/rubocop/issues/6022)

The same issue happens with `Layout/MultilineArrayBraceLayout` and it's also fixed by this PR. My approach here is to not auto-correct in case there's a comment after the last element of the hash/array and the hash/array is inside a method call.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bacchir** [comment]
I'll spend some time now refactoring the multiline literal braces shared examples because they are starting to get messy IMO.

File: spec/support/multiline_literal_brace_layout_examples.rb [hunk 1]
```diff
@@ -330,6 +330,44 @@ def construct(*args)
       end
     end
 
+    if [
+      RuboCop::Cop::Layout::MultilineArrayBraceLayout,
```
Comment (bbatsov) [inline spec/support/multiline_literal_brace_layout_examples.rb]: This seems pretty odd. Probably we just need different contexts for both or something like this.

Comment (bacchir) [reply spec/support/multiline_literal_brace_layout_examples.rb]: You are right, I'm going to refactor these shared examples

Comment (bacchir) [reply spec/support/multiline_literal_brace_layout_examples.rb]: @bbatsov I just refactored the shared examples in order to avoid ifs. Please take a look and let me know if it's ok now.

**Comment by bacchir** [comment]
@bbatsov I've fixed up this PR and I believe it's now ready to get merged. Any comments?

File: spec/support/multiline_literal_brace_layout_examples.rb (hunk 1 above)
Comment (bbatsov) [reply spec/support/multiline_literal_brace_layout_examples.rb]: Hmm, I still see this `if` in the diff. :-)

Comment (bacchir) [reply spec/support/multiline_literal_brace_layout_examples.rb]: You are totally right, sorry. I'll fix it.

Comment (bacchir) [reply spec/support/multiline_literal_brace_layout_examples.rb]: Sorry man, now it's correct.

**Comment by bacchir** [comment]
Rebased master and fixed failing tests related to [this change](https://github.com/rubocop-hq/rubocop/commit/82a005d4f2244bf987e2bde8823b6986b29be53b)

**Comment by bbatsov** [comment]
👍
