### PR TITLE
[Fix #8718] Fix undefined methods of pseudo location

### LINKED ISSUE #8718: Lint/EmptyFile causes error when I run RuboCop with `--format=json`
The combination with `Lint/EmptyFile` and the `--format=json` option seems to cause error. Perhaps, this relates the `PseudoSourceRange` here, but I'm not sure how to fix the problem.

---

## Expected behavior

RuboCop finishes the analysis without error.

## Actual behavior

Error is thrown when processing `Lint/EmptyFile`.

```
{"metadata":{"rubocop_version":"0.91.0","ruby_engine":"ruby","ruby_version":"2.7.1","ruby_patchlevel":"83","ruby_platform":"x86_64-linux"},"files":[],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":0}}undefined method `last_line' for #<RuboCop::Cop::Offense::PseudoSourceRange:0x00005586068a29b0>
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cop/offense.rb:175:in `last_line'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/json_formatter.rb:70:in `hash_for_location'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/json_formatter.rb:61:in `hash_for_offense'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/json_formatter.rb:50:in `block in hash_for_file'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/json_formatter.rb:50:in `map'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/json_formatter.rb:50:in `hash_for_file'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/json_formatter.rb:28:in `file_finished'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/formatter_set.rb:49:in `block in file_finished'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/formatter_set.rb:49:in `each'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/formatter/formatter_set.rb:49:in `file_finished'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:214:in `file_finished'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:123:in `process_file'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:97:in `block in each_inspected_file'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:96:in `each'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:96:in `reduce'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:96:in `each_inspected_file'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:82:in `inspect_files'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/runner.rb:43:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli/command.rb:11:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli/environment.rb:18:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli.rb:65:in `run_command'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli.rb:72:in `execute_runners'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/lib/rubocop/cli.rb:41:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/exe/rubocop:13:in `block in <top (required)>'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rubocop-03e83a2b234f/exe/rubocop:12:in `<top (required)>'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/rubocop:23:in `load'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/rubocop:23:in `<top (required)>'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/kamei/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/home/kamei/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/home/kamei/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

## Steps to reproduce the problem

You can reproduce this problem with [this](https://github.com/yykamei/tmp-rubocop-json-formatter-issue) repository.

1. Clone [this](https://github.com/yykamei/tmp-rubocop-json-formatter-issue) repository and move on to the cloned directory
2. Run `bundle install` (Maybe, you should set up your Ruby with rbenv)
3. Run `bundle exec rubocop --cache=false --format=json a.rb`

## RuboCop version

Master: 03e83a2b234feaa025333345a0c115751cc4a35e

```
$ [bundle exec] rubocop -V
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.0, running on ruby 2.7.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by ybiquitous**
This change aims to fix the error due to undefined methods of `RuboCop::Cop::Offence::PseudoSourceRange`.

The `RuboCop::Cop::Offence::PseudoSourceRange` class emulates the `Parser::Source::Range` class in the `parser` gem.
(see <https://github.com/whitequark/parser/blob/v2.7.1.5/lib/parser/source/range.rb>)

The `RuboCop::Cop::Offence#location` attribute can have an instance of both these classes.
So, these classes need to have the same interface and semantics for the usage in RuboCop.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/offense.rb [hunk 1]
```diff
@@ -63,7 +63,20 @@ class Offense
...
+        alias_method :last_column, :column
+
+        def column_range
+          column...last_column
+        end
+
+        def size
+          end_pos - begin_pos
+        end
+        alias_method :length, :size
```
Comment (ybiquitous) [inline lib/rubocop/cop/offense.rb:78]: [note] This redefines `Struct#size` and `Struct#length`.

See https://ruby-doc.org/core-2.7.1/Struct.html#size-method

File: lib/rubocop/cop/offense.rb [hunk 2]
```diff
@@ -63,7 +63,20 @@ class Offense
...
       PseudoSourceRange = Struct.new(:line, :column, :source_line, :begin_pos,
-                                     :end_pos)
+                                     :end_pos) do
+        alias_method :first_line, :line
+        alias_method :last_line, :line
+        alias_method :last_column, :column
+
+        def column_range
+          column...last_column
+        end
```
Comment (ybiquitous) [inline lib/rubocop/cop/offense.rb:73]: [note] See https://github.com/whitequark/parser/blob/v2.7.1.5/lib/parser/source/range.rb#L114-L120

File: spec/rubocop/formatter/json_formatter_spec.rb [hunk 3]
```diff
@@ -157,5 +157,21 @@
...
+      it 'returns a valid hash' do
+        expect(hash).to eq({
+                             start_line: 1,
+                             start_column: 1,
+                             last_line: 1,
+                             last_column: 0,
+                             length: 1,
+                             line: 1,
+                             column: 1
+                           })
```
Comment (ybiquitous) [inline spec/rubocop/formatter/json_formatter_spec.rb:173]: [note] `start_column` is `1`, but `last_column` is `0`. Because this method uses `#real_column` and `#last_column` as follows.
But I feel a bit weird for the difference. Is there no problem?

https://github.com/rubocop-hq/rubocop/blob/751edc7bf3df93d7ec5d59f5ac5b501627a6b723/lib/rubocop/formatter/json_formatter.rb#L68-L76

https://github.com/rubocop-hq/rubocop/blob/751edc7bf3df93d7ec5d59f5ac5b501627a6b723/lib/rubocop/cop/offense.rb#L193-L195

File: lib/rubocop/cop/offense.rb (hunk 1 above)
Comment (marcandre) [reply lib/rubocop/cop/offense.rb:78]: I think that's ok.

File: spec/rubocop/cop/offense_spec.rb [hunk 4]
```diff
@@ -180,4 +180,49 @@ def Foo
       expect(offense.highlighted_area.source).to eq('Foo')
     end
   end
+
+  context 'when the location is pseudo' do
+    let(:location) { described_class::NO_LOCATION }
+
+    it 'returns a location with valid size and length' do
+      expect(offense.location.size).to eq 1
```
Comment (marcandre) [inline spec/rubocop/cop/offense_spec.rb:188]: I don't remember at all why `end_pos` is 1. Shouldn't it be 0 (and size too)?

Comment (ybiquitous) [reply spec/rubocop/cop/offense_spec.rb:188]: The following PR seems the origin of `end_pos=1`. I cannot find the reason. 😓 

https://github.com/rubocop-hq/rubocop/pull/2516/files#diff-4f6676361bec108acba5cfd5a6d979b3

image

Comment (marcandre) [reply spec/rubocop/cop/offense_spec.rb:188]: If you could try with 0, I think it would make more sense (especially on an empty file!)

Comment (ybiquitous) [reply spec/rubocop/cop/offense_spec.rb]: I try it via 7e3b3da.

**Comment by ybiquitous** [comment]
I will squash the commits to one commit finally.

File: spec/rubocop/formatter/json_formatter_spec.rb (hunk 3 above)
Comment (rrosenblum) [reply spec/rubocop/formatter/json_formatter_spec.rb:173]: This does seem a little odd, however the pseudo source range is also not exactly accurate compared to other offenses since it is used to identify offenses for a file rather than an actual source range. I think it is OK for there to be a bit of non perfect behavior at the moment. It does kind of seem like there might be reason to do a larger refactor to better handle offenses in a file vs offenses in source code.

Maybe the offense itself shouldn't be responsible for the column information, and this kind of info should be handled in the location. I'm not sure how large of a refactor this would take.

Similarly, does it make sense to be setting the line number of the offense to 1 for `NO_LOCATION`? I think it's possible to have a file offense for a file with no code in it. `NO_LOCATION = PseudoSourceRange.new(1, 0, '', 0, 0).freeze`

**Review by rrosenblum — APPROVED** [review]

**Comment by rrosenblum** [comment]
Thanks for implementing this fix

File: spec/rubocop/formatter/json_formatter_spec.rb (hunk 3 above)
Comment (ybiquitous) [reply spec/rubocop/formatter/json_formatter_spec.rb:173]: @rrosenblum I agree with your idea, thank you. Surely, in this PR, it seems good that we avoid the big change of the current behavior.

But for the benefit of others, here is an example of comparison:

Current (line=1, col=1):

```
empty_file.rb:1:1: W: Lint/EmptyFile: Empty file detected.
```

Maybe (line=0, col=0):

```
empty_file.rb:0:0: W: Lint/EmptyFile: Empty file detected.
```

I will follow the decision of the community.

**Comment by bbatsov** [comment]
Thanks!

**Comment by ybiquitous** [comment]
@bbatsov Thank you for merging it!
