### PR TITLE
[Fix #7670] Handle offenses inside heredocs for --disable-uncorrectable

### LINKED ISSUE #7670: infinite loop when using --disable-uncorrectable when offense in HEREDOC
## Expected behavior

Rubocop would add `# rubocop:todo Naming/VariableName` at top of HEREDOC and re-enable at end of HEREDOC. The same issue exists for %Q tags.

## Actual behavior

Excessive amount of `# rubocop:todo Naming/VariableName` are generated within the heredoc instead of on top of it and program crashes.

## Steps to reproduce the problem

Given the following ruby:

```ruby
# frozen_string_literal: true

def our_function
  ourVariable = "foo"
  script = <<~JS
    <script>
      window.stuff = "#{ourVariable}"
    </script>
  JS
  puts(script)
end
```

When running: `rubocop --disable-uncorrectable --safe-auto-correct`, you get an infinite loop detected error, and the following code is generated:

```ruby
# frozen_string_literal: true

def our_function
  ourVariable = 'foo' # rubocop:todo Naming/VariableName
  script = <<~JS
    <script>
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # etc, etc
      window.stuff = "#{ourVariable}"
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # etc
```

## RuboCop version

0.79.0

### PR DESCRIPTION
**Pull request by jonas054**
The `# rubocop:todo` and `# rubocop:enable` must be placed outside the heredoc. Otherwise they won't have any effect and we will just add more and more comments until we crash.

### CODE REVIEW

File: lib/rubocop/cop/autocorrect_logic.rb [hunk 1]
```diff
@@ -39,16 +39,36 @@ def autocorrect_enabled?
...
+            disable_offense_before_and_after(range_by_lines(range))
+          end
         end
       end
 
+      def surrounding_heredoc(offense_range)
+        # The empty offense range is an edge case that can be reached from the Lint/Syntax cop.
+        return nil if offense_range.empty?
+
+        @heredoc_ranges ||= begin
```
Comment (jonas054) [inline lib/rubocop/cop/autocorrect_logic.rb:60]: Maybe this is premature optimization. It caches the ranges based on the assumption that we come here many times for one cop's inspection of one file.

Comment (jonas054) [reply lib/rubocop/cop/autocorrect_logic.rb]: I pushed a second commit, which I will squash if the reviewer agrees that it's better without the caching.

**Comment by bbatsov** [comment]
The changes look solid to me. Thanks!
