### PR TITLE
[Fix #9257] Fix false positive for `Style/SymbolProc` when the block uses a variable from outside the block

### LINKED ISSUE #9257: Style/SymbolProc false positive with unused argument
Consider:

```ruby
cat = Cat.new
[1, 2, 3].map { |_i| cat.meow }
```

## Expected behavior

Should not register any offenses.

## Actual behavior

Rubocop registers Style/SymbolProc offense: `[Correctable] Style/SymbolProc: Pass &:meow as an argument to map instead of a block.`

With the `-A` option, it autocorrects to:

```ruby
cat = Cat.new
[1, 2, 3].map(&:meow)
```

## RuboCop version

NOTE: this appears to be a regression because version 1.4.2 doesn't exhibit this behavior. Likely related to: https://github.com/rubocop-hq/rubocop/pull/9232

```
1.6.1 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.4.5 x86_64-darwin19)
  - rubocop-minitest 0.10.1
  - rubocop-performance 1.9.1
  - rubocop-rails 2.9.1
```

### PR DESCRIPTION
**Pull request by dvandersluis**
The changes in #9127 to keep the node pattern DRY accidentally broke the check that the lvar matches the argument name.

Fixes #9257.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by dvandersluis** [comment]
The circle build passed but didn't update the PR for some reason.

**Comment by marcandre** [comment]
Looks good, thanks for this 👍

File: lib/rubocop/cop/style/symbol_proc.rb [hunk 1]
```diff
@@ -22,11 +22,12 @@ class SymbolProc < Base
...
         def_node_matcher :proc_node?, '(send (const {nil? cbase} :Proc) :new)'
+        def_node_matcher :symbol_proc_receiver?, '{(send ...) (super ...) zsuper}'
         def_node_matcher :symbol_proc?, <<~PATTERN
-          ({block numblock}
-            ${(send ...) (super ...) zsuper}
-            ${(args (arg _)) 1}
-            (send (lvar _var) $_))
+          {
+            (block $#symbol_proc_receiver? $(args (arg _var)) (send (lvar _var) $_))
+            (numblock $#symbol_proc_receiver? $1 (send (lvar :_1) $_))
```
Comment (marcandre) [inline lib/rubocop/cop/style/symbol_proc.rb:29]: I made a double take at `$1`! 😆

Comment (dvandersluis) [reply lib/rubocop/cop/style/symbol_proc.rb:29]: Yeah it’s needed to balance each option in the `{}` but not actually used for anything (the capture for `block` is though so it’s needed)

Comment (marcandre) [reply lib/rubocop/cop/style/symbol_proc.rb:29]: That's what I figured 😆
