### PR TITLE
[Fix #7825] Fix crash for `Layout/MultilineMethodCallIndentation`

### LINKED ISSUE #7825: Layout/MultilineMethodCallIndentation error when parsing Dry::Monads::Try expression
Rubocop crashes when valid syntax according to https://dry-rb.org/gems/dry-monads/1.0/try/ is spread over two lines

--------

## Expected behavior

To generate a rubocop offence

## Actual behavior

```
An error occurred while Layout/MultilineMethodCallIndentation cop was inspecting ...
undefined method `dot' for #<Parser::Source::Map::Collection:0x00007fcdc8232448>
```

## Steps to reproduce the problem

```
AllCops:
  TargetRubyVersion: 2.6.2
```

```
# frozen_string_literal: true

require 'dry/monads'

class ExceptionalLand
  include Dry::Monads[:try]

  def call
    Try[ZeroDivisionError] { 10 / 0 }
      .fmap { |x| x * 3 }
  end
end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.80.1 (using Parser 2.7.0.5, running on ruby 2.6.2 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
When block passed to class constant.

Closes #7825 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/multiline_method_call_indentation.rb [hunk 1]
```diff
@@ -193,7 +193,7 @@ def semantic_alignment_node(node)
           node = node.receiver while node.receiver
           # ascend to first call which has a dot
           node = node.parent
-          node = node.parent until node.loc.dot
+          node = node.parent until node.loc&.respond_to?(:dot) && node.loc&.dot
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: Safe navigations looks unnecessary.

```suggestion
          node = node.parent until node.loc.respond_to?(:dot) && node.loc.dot
```

File: spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb [hunk 2]
```diff
@@ -304,6 +304,15 @@ def foo
         RUBY
       end
 
+      context 'target_ruby_version >= 2.5', :ruby25 do
+        it 'accepts blocks passed to class constant' do
```
Comment (koic) [inline spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb]: This issue is with key access to hash rather than constant class. For example, the following can be reproduced.

```diff
-            Try[ZeroDivisionError] { 10 / 0 }
+            hash[key] { 10 / 0 }
               .fmap { |x| x * 3 }
```

Can you update the test description and changelog entry?

**Comment by koic** [comment]
Thanks!
