### PR TITLE
[Fix #7534] Fix an incorrect autocorrect for `Layout/SpaceBeforeBlockBraces`

### LINKED ISSUE #7534: Bug: curly brace converting to `do` WITHOUT SPACE breaks code block (changes `field_set_tag {` to `field_set_tagdo`)
When rubocop.yml is configured thusly:

```
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
```

then this bug happens

`field_set_tag {`

gets changed to

`field_set_tagdo`

image

This breaks the code

### PR DESCRIPTION
**Pull request by koic**
Fixes #7534.

Fix an incorrect autocorrect for `Style/BlockDelimiters` cop and `Layout/SpaceBeforeBlockBraces` cop with `EnforcedStyle: no_space` when using multiline braces.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cli/cli_autocorrect_spec.rb [hunk 1]
```diff
@@ -1653,6 +1653,30 @@ def self.some_method(foo, bar: 1)
...
+        bar
+      }
+    RUBY
+
+    create_file('.rubocop.yml', <<~YAML)
+      Layout/SpaceBeforeBlockBraces:
+        EnforcedStyle: no_space
+    YAML
+
+    expect(cli.run(%w[--auto-correct])).to eq(0)
```
Comment (buehmann) [inline spec/rubocop/cli/cli_autocorrect_spec.rb]: Please don't let this example depend on other cops than `--only Style/BlockDelimiters,Layout/SpaceBeforeBlockBraces`. This is to prevent unnecessary work in the future if any of the unrelated cops changes. I remember 8d071f0c9a32f594b696cb7a3b6a0e5adabad42b all to well …

Comment (koic) [reply spec/rubocop/cli/cli_autocorrect_spec.rb]: Thanks for the review. I updated it.

File: spec/rubocop/cli/cli_autocorrect_spec.rb [hunk 2]
```diff
@@ -1653,6 +1653,32 @@ def self.some_method(foo, bar: 1)
     RUBY
   end
 
+  it 'corrects Style/BlockDelimiters offenses when specifing' \
```
Comment (jeremymoritz) [inline spec/rubocop/cli/cli_autocorrect_spec.rb]: small typo here (if you care): "specifying" instead of "specifing"

Thanks so much for posting the bugfix in such a timely manner!  I am amazed at how quickly you did so!  You're awesome!

Comment (koic) [reply spec/rubocop/cli/cli_autocorrect_spec.rb]: This typo fixed by https://github.com/rubocop-hq/rubocop/commit/e97eb5ce74b3319c21de05f6c1fd78493bd55b47. Thanks!

File: lib/rubocop/cop/layout/space_before_block_braces.rb [hunk 3]
```diff
@@ -110,6 +118,15 @@ def style_for_empty_braces
           end
         end
 
+        def conflict_with_block_delimiters?
+          block_delimiters_style == 'line_count_based' &&
+            style == :no_space && node.multiline?
```
Comment (johnny-miyake) [inline lib/rubocop/cop/layout/space_before_block_braces.rb]: @koic 
With rubocop-0.78.0 I got the below error. Do you have any idea?
```ruby
An error occurred while Layout/SpaceBeforeBlockBraces cop was inspecting /webapp/spec/my_spec.rb:697:6.
undefined local variable or method `node' for #<RuboCop::Cop::Layout::SpaceBeforeBlockBraces:0x0000560a675e42d8>
/usr/local/bundle/gems/rubocop-0.78.0/lib/rubocop/cop/layout/space_before_block_braces.rb:123:in `conflict_with_block_delimiters?'
```

Comment (koic) [reply lib/rubocop/cop/layout/space_before_block_braces.rb]: @johnny-miyake Thanks for your feedback. Can you open the issue with the reproduction code?
https://github.com/rubocop-hq/rubocop/issues

Comment (johnny-miyake) [reply lib/rubocop/cop/layout/space_before_block_braces.rb]: @koic Sure. I opened the issue here: https://github.com/rubocop-hq/rubocop/issues/7590
