### PR TITLE
[Fix #7320] support Naming/MethodName for attr_reader / attr_writer / attr_accessor

### LINKED ISSUE #7320: Naming/MethodName doesn't flag attr_reader / attr_writer / attr_accessor
## Expected behavior

[Naming/MethodName](https://github.com/rubocop-hq/rubocop/blob/master/manual/cops_naming.md#namingmethodname) should flag `attr_reader`, `attr_writer`, and `attr_accessor` for incorrect case.

## Actual behavior

Only methods defined with explicit `def` statements are flagged.

## Steps to reproduce the problem

Given the following code:

```ruby
# Foo example
class Foo
  attr_accessor :fooBar
  attr_reader :barBaz
  attr_writer :bazQux

  def quxCorge
    'quxCorge'
  end

  def quxCorge=(_)
    raise 'not a thing'
  end
end
```

The `Naming/MethodName` cop should flag all five declarations -- `fooBar`, `barBaz`, `bazQux`, `quxCorge`, and `quxCorge=`

Instead, only the explicit `def quxCorge` and `def quxCorge=` are flagged:

```
Inspecting 1 file
C

Offenses:

/tmp/naming.rb:10:7: C: Naming/MethodName: Use snake_case for method names.
  def quxCorge
      ^^^^^^^^
/tmp/naming.rb:14:7: C: Naming/MethodName: Use snake_case for method names.
  def quxCorge=(_)
      ^^^^^^^^^

1 file inspected, 2 offenses detected
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.5.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by denys281**
Resolves #7320 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I still don't see any tests covering the use of `attr` directly. Apart from this the PR looks good to me.

File: lib/rubocop/cop/naming/method_name.rb [hunk 1]
```diff
@@ -31,9 +31,27 @@ module Naming
       class MethodName < Cop
         include ConfigurableNaming
         include IgnoredPattern
+        include RangeHelp
 
         MSG = 'Use %<style>s for method names.'
 
+        def_node_matcher :attr?, <<~PATTERN
```
Comment (bbatsov) [inline lib/rubocop/cop/naming/method_name.rb]: Btw, there's also `define_method` that should be considered. In general it might be a good idea be able to provide a list of method names that define methods via configuration so custom macros could be accounted as well.

**Comment by denys281** [comment]
@bbatsov added. But.... It works only when you pass symbols, but should it also support strings ?

**Comment by bbatsov** [comment]
I guess it should handle strings as well.

File: spec/rubocop/cop/naming/method_name_spec.rb [hunk 2]
```diff
@@ -118,9 +179,40 @@ def on_selection_cleared(arg)
     end
   end
 
+  shared_examples 'multiple attr methods' do |enforced_style|
+    it 'registers an offense for camel case methods names in attr.' do
+      expect_offense(<<~RUBY)
+        attr :my_method, :myMethod
+             ^^^^^^^^^^^^^^^^^^^^^ Use #{enforced_style} for method names.
```
Comment (bbatsov) [inline spec/rubocop/cop/naming/method_name_spec.rb]: Shouldn't we highlight just the second symbol here?

Comment (denys281) [reply spec/rubocop/cop/naming/method_name_spec.rb]: Will check it. Do you know maybe some cops that have similar behavior? 

So it should be something like that ? 

```
attr :my_method, :myMethod, my_snake_method, : myCamelMethod
	                           ^^^^^^^^^^^^                                   ^^^^^^^^^^^^^^^^^^^ Use #{enforced_style} for method names.
```

Comment (bbatsov) [reply spec/rubocop/cop/naming/method_name_spec.rb]: Yep. See https://github.com/rubocop-hq/rubocop/pull/7385
