### PR TITLE
[Fix #9174] Handle send nodes with unparenthesized arguments in `Style/SoleNestedConditional`

### LINKED ISSUE #9174: False autocorrection when merging "exclude?" in outer conditional
When running `rubocop -a` on the following code, it autocorrects it to something syntactically wrong.

```
if condition
     array << device if (deviceArray1 + deviceArray2 + deviceArray3).exclude? device
end
```

Result:
```
if condition && (deviceArray1 + deviceArray2 + deviceArray3).exclude? device
     array << device 
end
```

RuboCop even throws an error in Lint/Syntax on the newly corrected line, so it is obviously a wrong correction. The correction stems from Style/SoleNestedConditional

--------

## Expected behavior

Not to make my code syntactically wrong. Maybe add brackets?

## Actual behavior

A wrong autocorrection

## RuboCop version

```
1.5.2 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.6.1 x86_64-darwin19)
  - rubocop-faker 1.1.0
  - rubocop-performance 1.9.1
  - rubocop-rails 2.8.1
  - rubocop-rake 0.5.1
  - rubocop-rspec 2.0.1
```

### PR DESCRIPTION
**Pull request by dvandersluis**
If a condition is rewritten by `Style/SoleNestedConditional` that was an unparenthesized send node, it would be rewritten to a syntax error. This changes it to wrap the send node in parens.

Fixes #9174.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by dvandersluis** [comment]
FYI - the original correction, `if x && y z` _would_ be fixed by `Style/MethodCallWithArgsParentheses`, and this does work if you run rubocop with `--only Style/SoleNestedConditional, Style/MethodCallWithArgsParentheses`. However, when the set of cops is not limited like this, `Lint/Syntax` catches it first and `MethodCallWithArgsParentheses` is unable to correct the code.

It'd be ideal I think if there was a way to immediately queue up a follow up cop after a cop's autocorrection completes (so that logic doesn't have to be duplicated, but I couldn't find a way to do so.

File: spec/rubocop/cop/style/sole_nested_conditional_spec.rb [hunk 1]
```diff
@@ -266,6 +266,44 @@
...
+          end
+        RUBY
+
+        expect_correction(<<~RUBY)
+          if foo && (ok? bar)
+            do_something
+          end
+        RUBY
+      end
+    end
```
Comment (koic) [inline spec/rubocop/cop/style/sole_nested_conditional_spec.rb:285]: The following case already in parentheses seem to unneeded a new wrap. Can you add the following case?

From:

```ruby
         if foo
            do_something if ok?(bar)
                         ^^ Consider merging nested conditions into outer `if` conditions.
          end
```

To:

```ruby
          if foo && ok?(bar)
            do_something
          end
```

File: spec/rubocop/cop/style/sole_nested_conditional_spec.rb [hunk 2]
```diff
@@ -266,6 +266,44 @@
...
+        RUBY
+
+        expect_correction(<<~RUBY)
+          if foo && (ok? bar)
+              do_something
+            end
+        RUBY
+      end
+    end
+  end
```
Comment (koic) [inline spec/rubocop/cop/style/sole_nested_conditional_spec.rb:305]: Can you add a test for the case?

From:

```
          if foo
            if ok?(bar)
            ^^ Consider merging nested conditions into outer `if` conditions.
              do_something
            end
          end
```

To:

```ruby
          if foo && ok?(bar)
              do_something
            end
```

**Comment by dvandersluis** [comment]
@koic thanks will make those changes!

**Comment by dvandersluis** [comment]
@koic fixed now, thanks!

File: spec/rubocop/cop/style/sole_nested_conditional_spec.rb [hunk 3]
```diff
@@ -266,6 +266,82 @@
...
+      it 'registers an offense and corrects' do
+        expect_offense(<<~RUBY)
+          if foo
+            do_something if ok? bar
+                         ^^ Consider merging nested conditions into outer `if` conditions.
+          end
+        RUBY
+
+        expect_correction(<<~RUBY)
+          if foo && (ok? bar)
```
Comment (koic) [inline spec/rubocop/cop/style/sole_nested_conditional_spec.rb:280]: A little worrisome is that `foo && ok?(bar)` is (maybe) more natural code rather than `foo && (ok? bar)` for user 😅

Comment (dvandersluis) [reply spec/rubocop/cop/style/sole_nested_conditional_spec.rb:280]: Yeah, I agree, but I couldn't get it working otherwise. If I try to correct the `condition` node I get a clobbering error. Any suggestions?

Comment (koic) [reply spec/rubocop/cop/style/sole_nested_conditional_spec.rb:280]: Unfortunately I don't have an immediate idea 💦 , but I think it can be improved later. First, I'm going to merge this PR to prevent the syntax error. Thank you for your consideration and fixing!

Comment (dvandersluis) [reply spec/rubocop/cop/style/sole_nested_conditional_spec.rb:280]: Thanks @koic!
