### PR TITLE
Fix `Style/AccessorGrouping` to not register offense for accessor with comment

### LINKED ISSUE #8289: Style/AccessorGrouping cop autocorrect mess-up code with comments
## Steps to reproduce the problem

1. Create `test.rb` file with content:
```ruby
class Foo
  # [String] Some bar value return
  attr_reader :bar

  # @return [String] value of foo_bar
  attr_reader :foo_bar
end

```

2. run `rubocop -a` with enabled `Style/AccessorGrouping` cop

## Expected behavior

Do not mess up my comments and `yard` documentation

## Actual behavior

Result file is:
```ruby
class Foo
  # [String] Some bar value return
  attr_reader :bar, :foo_bar

  # @return [String] value of foo_bar
end

```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.87.1 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.7.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #8289 

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
@fatkodima Please, take a look as well.

File: lib/rubocop/cop/style/accessor_grouping.rb [hunk 1]
```diff
@@ -41,6 +41,8 @@ class AccessorGrouping < Cop
         ACCESSOR_METHODS = %i[attr_reader attr_writer attr_accessor attr].freeze
 
         def on_class(node)
+          return if grouped_style? && !accessors_without_comments(node)
```
Comment (fatkodima) [inline lib/rubocop/cop/style/accessor_grouping.rb:44]: This check seems not needed.

Comment (tejasbubane) [reply lib/rubocop/cop/style/accessor_grouping.rb]: Right. I was thinking it might be needed when there are multiple separate accessors and only one without comment. But that case also seems to be handled by `check`. Removed this.

**Comment by koic** [comment]
Thanks!
