### PR TITLE
[Fix #6100] Fix a false positive in `Naming/ConstantName` cop

### LINKED ISSUE #6100: Naming/ConstantName flags conditional assignments of classes to camel-cased constants
## Expected behavior

I expected this not to trigger the `Naming/ConstantName` cop:

```
class Foo; end
class Bar; end

Lol = if true then Foo else Bar end
```

The docs [say](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/ConstantName)

> To avoid false positives, it ignores cases in which we cannot know for certain the type of value that would be assigned to a constant.

The changelog [says](https://github.com/rubocop-hq/rubocop/blob/5ea73b3453a741b3ec05f781459741f39400c1a8/CHANGELOG.md#0540-2018-03-21)

> Fix false positive in `Naming/ConstantName` when using conditional assignment. (@drenmi)

## Actual behavior

That code triggered the `Naming/ConstantName` cop.

## Steps to reproduce the problem

```
~  ➜ cat foo.rb
class Foo; end
class Bar; end

Lol = if true then Foo else Bar end
~  ➜ rubocop --only Naming/ConstantName foo.rb
Inspecting 1 file
C

Offenses:

foo.rb:4:1: C: Naming/ConstantName: Use SCREAMING_SNAKE_CASE for constants.
Lol = if true then Foo else Bar end
^^^

1 file inspected, 1 offense detected
```

This isn't a problem without the conditional:

```
~  ➜ cat bar.rb
class Foo; end
Bar = Foo
~  ➜ rubocop --only Naming/ConstantName bar.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## RuboCop version

```
~  ➜ rubocop -V
0.58.1 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by tatsuyafw**
Fixes #6100.

This cop would register an offense when rhs is a conditional expression like the following code:

```ruby
# foo.rb
Lol = if true then Foo else Bar end
```

```sh
$ rubocop --only Naming/ConstantName foo.rb
Inspecting 1 file
C

Offenses:

foo.rb:1:1: C: Naming/ConstantName: Use SCREAMING_SNAKE_CASE for constants.
Lol = if true then Foo else Bar end
^^^

1 file inspected, 1 offense detected
$
```

But the docs [say](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/ConstantName)

> To avoid false positives, it ignores cases in which we cannot know for certain the type of value that would be assigned to a constant.

This PR fixes the false positive.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by robotdana** [comment]
I think this needs a deeper look: `Lol = if inital_condition then "string" else "other string"` should still be an offense

**Comment by Drenmi** [comment]
Nice! This is a great start!

@robotdana is correct. We should check the conditional branches to make sure they contain constants. Unfortunately there is no straightforward way of enumerating the branches right now. (Parser nests these in a less intuitive way.)

I actually looked at this two days ago, and am planning to add `IfNode#each_branch` and `IfNode#branches` soon. That might not be until next month though.

**Comment by tatsuyafw** [comment]
@robotdana @Drenmi 

Thanks for your feedbacks and sorry for my lack of consideration :bow:

> I actually looked at this two days ago, and am planning to add IfNode#each_branch and IfNode#branches soon. That might not be until next month though.

That sounds good 😃  I'd like to try to add that APIs to check conditional branches more deeply.

**Comment by tatsuyafw** [comment]
@Drenmi 

Hi, I've added `IfNode#branches` and `IfNode#each_branch` APIs, and using that APIs, made the cop check whether conditional branches contain a constant (f051d67).

```console
$ cat good.rb
Lol = if true then Foo else Bar end
$ bundle exec exe/rubocop --only Naming/ConstantName good.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
$


$ cat bad.rb
Lol = if true then 'foo' else 'bar' end
$ bundle exec exe/rubocop --only Naming/ConstantName bad.rb
Inspecting 1 file
C

Offenses:

bad.rb:1:1: C: Naming/ConstantName: Use SCREAMING_SNAKE_CASE for constants.
Lol = if true then 'foo' else 'bar' end
^^^

1 file inspected, 1 offense detected
$
```

I'd appreciate it if you could give me some feedback.

**Comment by tatsuyafw** [comment]
I rebased to resolve the CHANGELOG conflict.

File: lib/rubocop/ast/node/if_node.rb [hunk 1]
```diff
@@ -141,6 +141,35 @@ def node_parts
 
         [condition, true_branch, false_branch]
       end
+
+      # Returns an array of all the branches in the conditional statement.
+      #
+      # @return [Array<Node>] an array of branch nodes
+      def branches
```
Comment (Drenmi) [inline lib/rubocop/ast/node/if_node.rb]: Implementation looks good. I think there might be some small enhancements that can be made to readability. Example:

```ruby
branches = [if_branch]

return branches unless else_branch

other_branches = if elsif_conditional?
                   else_branch.branches
                 else
                   else_branch
                 end

branches.concat(other_branches)
```

WDYT?

**Comment by Drenmi** [comment]
> Hi, I've added IfNode#branches and IfNode#each_branch APIs, and using that APIs, made the cop check whether conditional branches contain a constant.

Hi, @tatsuyafw. Fantastic work! This looks great. 🙂

File: lib/rubocop/ast/node/if_node.rb (hunk 1 above)
Comment (tatsuyafw) [reply lib/rubocop/ast/node/if_node.rb]: @Drenmi 

Looks great! I've changed your example code a bit and replaced the code.

```ruby
branches = [if_branch]

return branches unless else_branch

other_branches = if elsif_conditional?
                   else_branch.branches
                 else
                   [else_branch] # changed here
                 end

branches.concat(other_branches)
```

**Comment by tatsuyafw** [comment]
Rebased.

**Comment by Drenmi** [comment]
Ping @bbatsov.

**Comment by tatsuyafw** [comment]
Rebased again.

**Comment by bbatsov** [comment]
Thanks!
