### PR TITLE
[Fix #4115] Don't check unary ops in MultilineOperationIndention

### LINKED ISSUE #4115: Infinite loop when autocorrecting unparanthesized indented method arguments with unary `!`
This snippet causes rubocop's autocorrection to enter an infinite loop and crash.
Rubocop detects errors but apparently different autocorrection rules keep rewriting each other.
IMO the code already looks correct.

The errors go away if parenthesis are added.

--------

## Expected behavior

rubocop accepts the correct code as is, and if not, it manages to autocorrect it to something it likes.

## Actual behavior

rubocop detects two violations, and when autocorrecting them it crashes.

## Steps to reproduce the problem

input file, `rubocop-bug.rb`:

```
call a,
     !b
```

rubocop configuration in `.rubocop.yml`
```
MultilineOperationIndentation:
  EnforcedStyle: indented
```

Checking:
```
bigmec:~ riffraff$ rubocop rubocop-bug.rb
Inspecting 1 file
C

Offenses:

rubocop-bug.rb:1:1: C: The name of this source file (rubocop-bug.rb) should use snake_case.
call a,
^
rubocop-bug.rb:2:6: C: Use 2 (not 5) spaces for indenting an expression spanning multiple lines.
     !b
     ^

1 file inspected, 2 offenses detected
```

Correcting: 
```
bigmec:~ riffraff$ rubocop -a rubocop-bug.rb
Inspecting 1 file
C

Offenses:

rubocop-bug.rb:2:3: C: [Corrected] Align the parameters of a method call if they span more than one line.
  !b
  ^^
rubocop-bug.rb:2:6: C: [Corrected] Use 2 (not 5) spaces for indenting an expression spanning multiple lines.
     !b
     ^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /Users/riffraff/rubocop-bug.rb.
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:238:in `check_for_infinite_loop'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:221:in `block in iterate_until_no_changes'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:220:in `loop'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:220:in `iterate_until_no_changes'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:191:in `do_inspection_loop'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:101:in `block in file_offenses'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:111:in `file_offense_cache'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:99:in `file_offenses'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:90:in `process_file'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `each'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `reduce'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:65:in `each_inspected_file'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/runner.rb:36:in `run'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/lib/rubocop/cli.rb:27:in `run'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/bin/rubocop:13:in `block in <top (required)>'
/Users/riffraff/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/Users/riffraff/.rvm/gems/ruby-2.4.0/gems/rubocop-0.47.1/bin/rubocop:12:in `<top (required)>'
/Users/riffraff/.rvm/gems/ruby-2.4.0/bin/rubocop:22:in `load'
/Users/riffraff/.rvm/gems/ruby-2.4.0/bin/rubocop:22:in `<main>'
/Users/riffraff/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/riffraff/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

## RuboCop version

```
bigmec:~ riffraff$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by jonas054**
There was a false positive for expressions such as `!b` in multiline method calls in this cop.

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

### CODE REVIEW

File: spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb [hunk 1]
```diff
@@ -16,6 +16,13 @@
   let(:cop_indent) { nil } # use indentation width from Layout/IndentationWidth
 
   shared_examples 'common' do
+    it 'accepts unary oparations' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb]: operations

Comment (jonas054) [reply spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb]: Fixed now.

File: lib/rubocop/cop/layout/multiline_operation_indentation.rb [hunk 2]
```diff
@@ -61,6 +61,7 @@ def autocorrect(node)
         private
 
         def relevant_node?(node)
+          return false if node.unary_operation?
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/multiline_operation_indentation.rb]: Nice!
