### PR TITLE
Fix #4229 Unexpected Style/HashSyntax consistency offence

### LINKED ISSUE #4229: Unexpected Style/HashSyntax consistency offence
I don't know whether this is what it's supposed to be.

I got a **"Use hash rockets syntax."** wanrning from code
```ruby
scope :module => :users do
  resources :registrations, only: %i(create update destroy)
end
``` 
with `UseHashRocketsWithSymbolValues: true`. 

I think RuboCop checked the syntax consistency of `only: [:create, :update, :destroy]` and `scope :module => :users`, which is however not what I expected.

--------

## Expected behavior

No warning

## Actual behavior

Got a **"Use hash rockets syntax."** wanrning

## Steps to reproduce the problem

Have the following in rubocop.yml
```yml
Style/HashSyntax:
  EnforcedStyle: ruby19
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: false
```
Run rubocop against following:
```ruby
scope :module => :users do
  resources :registrations, only: %i(create update destroy)
end
```

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by timon**
Caching the value of `force_hash_rockets?` for autocorrect has a side-effect of flagging an offence every ruby19-style hash pair after the first encounter of hash with symbol value when UseHashRocketsWithSymbolValue is on, so the following code is incorrectly marked as offensive:

```ruby
  scope :module => :users do
    resources :registrations, only: %i(create update destroy)
  end
```
I have removed memoization from `force_hash_rockets?` method and added a test case to check that future optimizations for `autocorrect` won't break the checks.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/hash_syntax.rb [hunk 1]
```diff
@@ -87,7 +87,7 @@ def hash_rockets_check(pairs)
         end
 
         def ruby19_no_mixed_keys_check(pairs)
-          if force_hash_rockets?
+          if force_hash_rockets? pairs
```
Comment (bquorning) [inline lib/rubocop/cop/style/hash_syntax.rb]: I would add parentheses around `pairs` here.

Comment (timon) [reply lib/rubocop/cop/style/hash_syntax.rb]: Yes, I should have paid more attention to the surrounding code. 
Fixed that (plus merged current master)
