### PR TITLE
[Fix #6969] Fix a false positive in `Style/InverseMethods`

### LINKED ISSUE #6969: Style/InverseMethods not being safe in auto-correct
## Expected behavior
running Style/InverseMethods should consider return arguments of next statements

## Actual behavior

it did change it to a result that's not the same

## Steps to reproduce the problem

Simplified example:

```ruby
class TestClass
  def test_method
    [1, 2, 3, 4].select do |number|
      next(false) if number == 4

      !number.odd?
    end
  end
end

print TestClass.new.test_method
```

gets autocorrected to 
```ruby
class TestClass
  def test_method
    [1, 2, 3, 4].reject do |number|
      next(false) if number == 4

      number.odd?
    end
  end
end

print TestClass.new.test_method
```

Which is not the same result:

Console:
```
$ ruby test_class.rb      
[2]                                                                                                                                                                                     
$ rubocop -a test_class.rb
Inspecting 1 file
C

Offenses:

test_class.rb:3:5: C: [Corrected] Style/InverseMethods: Use reject instead of inverting select.
    [1, 2, 3, 4].select do |number| ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
$ ruby test_class.rb      
[2, 4]                                                                                                                                                                                  
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.4.5 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by dduugg**
`Style/InverseMethods` does not contemplate guard clauses or other jumps within block methods. This PR updates the cop to skip further evaluation in such cases.

It was sufficient to consider `next` nodes in testing this over a large codebase, but it also guards agains `break` and `return` nodes, out of an abundance of caution.

The `contains_jump?` implementation feels suboptimal, and I'd like to know if there's a better approach. I could neither find an existing helper to look for node types within an AST, nor find a valid `def_node_matcher` that would do the trick.

Resolves https://github.com/rubocop-hq/rubocop/issues/6969

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/inverse_methods.rb [hunk 1]
```diff
@@ -175,6 +178,15 @@ def camel_case_constant?(node)
         def dot_range(loc)
           range_between(loc.dot.begin_pos, loc.expression.end_pos)
         end
+
+        def contains_jump?(node)
+          return false unless node.is_a?(RuboCop::AST::Node)
```
Comment (Darhazer) [inline lib/rubocop/cop/style/inverse_methods.rb]: one-liner:
`node.each_node(:return, :break, :next).any?`
each_node starts from the receiver (`node`) and recursively visits child nodes, with optional filtering by types (which is what you are checking), and yields only nodes, so no need to check for the class.

Comment (dduugg) [reply lib/rubocop/cop/style/inverse_methods.rb]: ty, done!

File: CHANGELOG.md [hunk 2]
```diff
@@ -23,7 +24,7 @@
 * [#6992](https://github.com/rubocop-hq/rubocop/pull/6992): Fix unknown default configuration for `Layout/IndentFirstParameter` cop. ([@drenmi][])
 * [#6972](https://github.com/rubocop-hq/rubocop/issues/6972): Fix a false positive for `Style/MixinUsage` when using inside block and `if` condition is after `include`. ([@koic][])
 * [#6738](https://github.com/rubocop-hq/rubocop/issues/6738): Prevent auto-correct conflict of `Style/Next` and `Style/SafeNavigation`. ([@hoshinotsuyoshi][])
-* [#6847](https://github.com/rubocop-hq/rubocop/pull/6847): Fix `Style/BlockDelimiters` to properly check if the node is chaned when `braces_for_chaining` is set. ([@att14][])
+* [#6847](https://github.com/rubocop-hq/rubocop/pull/6847): Fix `Style/BlockDelimiters` to properly check if the node is chained when `braces_for_chaining` is set. ([@att14][])
```
Comment (dduugg) [inline CHANGELOG.md]: (unrelated typo fix)

**Comment by dduugg** [comment]
@Drenmi thanks for the suggestion. I've withdrawn skipping blocks with `return`/`break`. The only default block methods are `select`/`reject` (and their `!` counterparts), and i've convinced myself that this cop doesn't break when paired with these other jump methods.

File: lib/rubocop/cop/style/inverse_methods.rb [hunk 3]
```diff
@@ -76,6 +78,7 @@ def on_block(node)
           inverse_block?(node) do |_method_call, method, block|
             return unless inverse_blocks.key?(method)
             return if negated?(node) && negated?(node.parent)
+            return if node.each_node(:next).any?
```
Comment (rrosenblum) [inline lib/rubocop/cop/style/inverse_methods.rb]: > It was sufficient to consider `next` nodes in testing this over a large codebase, but it also guards agains `break` and `return` nodes, out of an abundance of caution.

I don't see any code in here that would fix this issue for `break` or `return`. I think this needs to look for those node types as well.

File: lib/rubocop/cop/style/inverse_methods.rb [hunk 4]
```diff
@@ -28,6 +28,8 @@ module Style
       #   foo == bar
       #   !!('foo' =~ /^\w+$/)
       #   !(foo.class < Numeric) # Checking class hierarchy is allowed
+      #   # Blocks with guard clauses are ignored:
+      #   foo.select { |f| next if f.zero?; f != 1 }
```
Comment (rrosenblum) [inline lib/rubocop/cop/style/inverse_methods.rb]: We do not recommend using semicolons within code, and we like to have our code examples follow as many best practices as possible. Please change this example to a multi-line block.

```ruby
#   foo.select do |f| 
#     next if f.zero?
#     f != 1
#   end
```

File: lib/rubocop/cop/style/inverse_methods.rb (hunk 3 above)
Comment (dduugg) [reply lib/rubocop/cop/style/inverse_methods.rb]: @rrosenblum it's been reverted after further discussion/consideration. could i trouble you for an example of an issue caused by `break` or `return`?

File: lib/rubocop/cop/style/inverse_methods.rb (hunk 4 above)
Comment (dduugg) [reply lib/rubocop/cop/style/inverse_methods.rb]: done!

File: lib/rubocop/cop/style/inverse_methods.rb (hunk 3 above)
Comment (rrosenblum) [reply lib/rubocop/cop/style/inverse_methods.rb]: I think I missed something from an earlier conversation. It sounds like you had accounted for this and then reverted it. The comment that I quoted made it seem like we needed to account for `break` and `return`. These are likely edge cases because `break` and `return` don't make much sense inside of methods that are designed to have a return.

File: manual/cops_style.md [hunk 5]
```diff
@@ -2658,6 +2658,8 @@ foo != bar
 foo == bar
 !!('foo' =~ /^\w+$/)
 !(foo.class < Numeric) # Checking class hierarchy is allowed
+# Blocks with guard clauses are ignored:
+foo.select { |f| next if f.zero?; f != 1 }
```
Comment (rrosenblum) [inline manual/cops_style.md]: You'll need to regenerate the documentation to update this.

Comment (dduugg) [reply manual/cops_style.md]: d'oh, done!

File: spec/rubocop/cop/style/inverse_methods_spec.rb [hunk 6]
```diff
@@ -50,6 +50,20 @@
     expect_no_offenses('!!foo.reject { |e| !e }')
   end
 
+  it 'allows an inverse method in a block with next' do
+    expect_no_offenses(<<-RUBY.strip_indent)
```
Comment (koic) [inline spec/rubocop/cop/style/inverse_methods_spec.rb]: Could you rebase using latest master branch and change it to the following code?

```diff
-expect_no_offenses(<<-RUBY.strip_indent)
+expect_no_offenses(<<~RUBY)
```

Comment (dduugg) [reply spec/rubocop/cop/style/inverse_methods_spec.rb]: done!

**Comment by koic** [comment]
Thank you!
