### PR TITLE
Fixed alignment source for Layout/RescueEnsureAlignment when using inline access modifiers

### LINKED ISSUE #6326: Layout/RescueEnsureAlignment broken in new releases 0.59.x
Hello. Old releases 0.58.x were fine, new 0.59.x looks broken.

## Steps to reproduce the problem

```
class A
  protected def a
    puts 1
  rescue StandardError
    puts 2
  end
end
```

## Expected behavior

Style is ok.

## Actual behavior

> rescue ... is not aligned with def a

## RuboCop version

0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-linux)
0.59.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-linux)

PS I am using

```
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
```

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #6326.

1. Fixed alignment source for `autocorrect` and `check` methods.
2. Implemented alignment node as a parent node + access modifier (if it exists).
3. I haven't added any fixed node types like `:send`. Code requires node only respond to `access_modifier?`. So it will be easy to add any other inline modifiers in future.
4. Cosmetics to fit with current project styles.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by andrew-aladev** [comment]
Closes #6313.

File: lib/rubocop/cop/layout/rescue_ensure_alignment.rb [hunk 1]
```diff
@@ -29,13 +29,25 @@ class RescueEnsureAlignment < Cop
               '%<begin_loc_line>d, %<begin_loc_column>d.'.freeze
         ANCESTOR_TYPES = %i[kwbegin def defs class module].freeze
         RUBY_2_5_ANCESTOR_TYPES = (ANCESTOR_TYPES + [:block]).freeze
+        ANCESTOR_TYPES_WITH_ACCESS_MODIFIERS = %i[def defs].freeze
 
         def on_resbody(node)
-          check(node) unless modifier?(node)
+          check node unless modifier? node
```
Comment (rrosenblum) [inline lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: There is a strong preference towards using parentheses in the project.

File: lib/rubocop/cop/layout/rescue_ensure_alignment.rb [hunk 2]
```diff
@@ -29,13 +29,25 @@ class RescueEnsureAlignment < Cop
...
         end
 
         def on_ensure(node)
-          check(node)
+          check node
+        end
+
+        def autocorrect(node)
+          whitespace = whitespace_range node
+          return false unless whitespace.source.strip.empty?
```
Comment (rrosenblum) [inline lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: It isn't immediately clear to me what code would cause `return false unless whitespace.source.strip.empty?` or `return false if alignment_node.nil?` to trigger. Is there a way for us to be able to handle auto-correcting in any of these scenarios?

File: lib/rubocop/cop/layout/rescue_ensure_alignment.rb (hunk 1 above)
Comment (Drenmi) [reply lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: We would automatically check this, but the cop that does that still has too many false positives to be enabled.

But yes, please don't remove the parens for regular method calls (non DSLs) in this project. 🙇

**Comment by andrew-aladev** [comment]
Sorry, I was very busy this week. I will update it today.

File: lib/rubocop/cop/layout/rescue_ensure_alignment.rb (hunk 1 above)
Comment (andrew-aladev) [reply lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: fixed

File: lib/rubocop/cop/layout/rescue_ensure_alignment.rb (hunk 2 above)
Comment (andrew-aladev) [reply lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: `alignment_node.nil?` We couldn't find a node for alignment. It has very low probability, but I couldn't add this check.

`whitespace.source.strip.empty?` is an old code. It looks strange. I've found that it means `whitespace.real_whitespace?`. You can reproduce that some whitespace could not be a real whitespace =)

```
new_source = autocorrect_source(<<-RUBY.strip_indent)
  def test
    'foo'; rescue StandardError;
  end
RUBY

expect(new_source).to eq(<<-RUBY.strip_indent)
  def test
    'foo'; rescue StandardError;
  end
RUBY
```

Comment (andrew-aladev) [reply lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: I will try to fix it and add some tests.

**Comment by andrew-aladev** [comment]
I've removed merge commits and squashed it in single commit again. Ok? Done.

**Comment by a14m** [comment]
Thanks a lot for the work, are we expecting this to soon be merged and released?
Thanks again for the awesome work 👍
