### PR TITLE
[Fix #7159] Fix an error for `Lint/DuplicatedKey`

### LINKED ISSUE #7159: Support endless range from Ruby 2.6
Latest version doesn't have support of added feature `endless ranges` in Ruby 2.6.

--------

## Expected behavior

In case of proper syntax for endless range, Rubocop should pass

## Actual behavior

It fails with error

```
Inspecting 1 file
An error occurred while Lint/DuplicatedKey cop was inspecting /Users/anton/code/rubocop-endless-range-issues/test.rb:3:7.
To see the complete backtrace run rubocop -d.
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Lint/DuplicatedKey cop was inspecting /Users/anton/code/rubocop-endless-range-issues/test.rb:3:7.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.71.0 (using Parser 2.6.3.0, running on ruby 2.6.1 x86_64-darwin18)
```

## Steps to reproduce the problem

I created repo with 2 test files (ruby files and rubocop config).
https://github.com/antonzaytsev/rubocop-endless-range-issue.
Literally any code with endless range will break rubocop.
For example
```ruby
hash = {
  1...20 => true,
  20... => false
}
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.71.0 (using Parser 2.6.3.0, running on ruby 2.6.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7159.

This PR fixes the following error for `Lint/DuplicatedKey` when using endless range in Ruby 2.6.

```console
% rubocop -V
0.71.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin17)
% cat example.rb
{
  42.. => false
}
% rubocop --only Lint/DuplicatedKey -d
For /private/tmp/7159: configuration from
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.71.0/config/default.yml
Inspecting 1 file
Scanning /private/tmp/7159/example.rb
An error occurred while Lint/DuplicatedKey cop was inspecting
/private/tmp/7159/example.rb:1:0.
undefined method `recursive_basic_literal?' for nil:NilClass
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.71.0/lib/rubocop/ast/node.rb:408:in
`all?'
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.71.0/lib/rubocop/ast/node.rb:408:in
`block (2 levels) in <class:Node>'
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.71.0/lib/rubocop/cop/lint/duplicated_key.rb:27:in
`select'
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.71.0/lib/rubocop/cop/lint/duplicated_key.rb:27:in
`on_hash'
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.71.0/lib/rubocop/cop/commissioner.rb:59:in
`block (2 levels) in trigger_re
sponding_cops'

(snip)
```

There are the following differences in the AST generated by Parser gem.

```console
% ruby-parse -e '(42..nil)'
(begin
  (irange
    (int 42)
    (nil)))

% ruby-parse -e '(42..)'
(begin
  (irange
    (int 42) nil))
```

This PR works with `nil` representing the endless range.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/ast/node.rb [hunk 1]
```diff
@@ -405,7 +405,9 @@ def immutable_literal?
               receiver.send(recursive_kind) &&
               arguments.all?(&recursive_kind)
           when :begin, :pair, *OPERATOR_KEYWORDS, *COMPOSITE_LITERALS
-            children.all?(&recursive_kind)
+            children.all? do |child|
+              child.nil? ? true : child.public_send(recursive_kind)
+            end
```
Comment (antonzaytsev) [inline lib/rubocop/ast/node.rb]: `children.compact.all?(&recursive_kind)` should read simpler

Comment (koic) [reply lib/rubocop/ast/node.rb]: Awesome! I updated it.

**Comment by bbatsov** [comment]
Thanks!
