### PR TITLE
[Fix #7099] Fix an error in `Layout/RescueEnsureAlignment` cop

### LINKED ISSUE #7099: An error occurred while Layout/RescueEnsureAlignment cop was inspecting in 0.71.0 against Ruby 2.6.1
Just got this bug after upgrading to 0.71.0, but a quick search through issues shows this is happening for a while now

--------

## Expected behavior

No bug when running rubocop against this code:

```ruby
# frozen_string_literal: true

module Test
  X = lambda do
    x = 1
      rescue StandardError # should be indented only two spaces
    x
  end
end
```

## Actual behavior

```
Inspecting 1 file
An error occurred while Layout/RescueEnsureAlignment cop was inspecting /Users/jakemoffatt/Code/rubocop-dupe-bug/csv.rb:6:3.
To see the complete backtrace run rubocop -d.
C

Offenses:

csv.rb:7:4: C: Layout/IndentationWidth: Use 2 (not 1) spaces for indentation.
    x
   ^

1 file inspected, 1 offense detected

1 error occurred:
An error occurred while Layout/RescueEnsureAlignment cop was inspecting /Users/jakemoffatt/Code/rubocop-dupe-bug/csv.rb:6:3.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.71.0 (using Parser 2.6.0.0, running on ruby 2.6.1 x86_64-darwin18)
```

## Steps to reproduce the problem

Run rubocop with the default configuration against the code sample above.

## RuboCop version

```
0.71.0 (using Parser 2.6.0.0, running on ruby 2.6.1 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by tatsuyafw**
Fixes #7099.

When running rubocop against the below code where the block was assigned to a variable, it was expected that `Layout/RescueEnsureAlignment` cop would register an offense, but an error occurred in the cop.

```
result = [1, 2, 3].map do |el|
  rescue StandardError => _exception
end
```

This change fixes that.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/rescue_ensure_alignment.rb [hunk 1]
```diff
@@ -101,8 +101,12 @@ def alignment_source(node, starting_loc)
             case node.type
             when :block, :kwbegin
               node.loc.begin
-            when :def, :defs, :class, :module
+            when :def, :defs, :class, :module, \
```
Comment (koic) [inline lib/rubocop/cop/layout/rescue_ensure_alignment.rb]: `\` looks unnecessary.

**Comment by tatsuyafw** [comment]
@koic 

Thank you for your review!
I've removed unnecessary `\`.

**Comment by tatsuyafw** [comment]
Rebased to resolve the conflict.

**Comment by koic** [comment]
Thanks!
