### PR TITLE
[Fix #7291] Add better message for layout/HashAlignment

### LINKED ISSUE #7291: Layout/AlignHash pops up on aligned hash
## Expected behavior

When I have keys and values of a Hash aligned I should not see this offense in Rubocop report.

## Actual behavior

Gist with larger example hash: https://gist.github.com/roolo/580b5061003355e07f631cffbe2fea9c

~~~ruby
user:         current_user,
subscription: FactoryBot.create(:subscription,
~~~

When I have hash like this, I am told I should _elements of a hash literal_

## Steps to reproduce the problem

1. Put call from gist into your code. Adding just the hash might also work
2. Run rubocop

## RuboCop version

```
 $ bundle exec rubocop -V 
0.74.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by jsartin513**
Fixes [#7291](https://github.com/rubocop-hq/rubocop/issues/7291)

Before this change, the Layout/HashAlignment cop always gave the same error message: "Align the elements of a hash literal if they span more than one line."
This was confusing in situations where a hash appeared to be aligned, but was not according to the configured alignment settings.

This PR changes the error message to reflect which part(s) of a hash must be aligned to pass the cop.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/hash_alignment.rb [hunk 1]
```diff
@@ -248,10 +248,17 @@ def check_pairs(node)
           add_offences
         end
 
+        def specific_message(format)
+          messages = { KeyAlignment => 'Align the keys of a hash literal if they span more than one line.',
+                       SeparatorAlignment => 'Align the separator of a hash literal if they span more than one line.',
```
Comment (buehmann) [inline lib/rubocop/cop/layout/hash_alignment.rb]: Shouldn't this read `separators`? (matching `they`)

File: lib/rubocop/cop/layout/hash_alignment.rb [hunk 2]
```diff
@@ -248,10 +248,17 @@ def check_pairs(node)
...
+                       TableAlignment => 'Align the keys and values of a hash literal if they span more than one line.'}
+          return messages[format]
+        end
+
         def add_offences
           _format, offences = offences_by.min_by { |_, v| v.length }
```
Comment (buehmann) [inline lib/rubocop/cop/layout/hash_alignment.rb]: Now that `_format` is no longer unused, better drop the underscore from its name.

**Comment by jsartin513** [comment]
@buehmann I've addressed your feedback, I would appreciate if you could take another look!

I'm also getting an `AppVeyor` check failure, I think this is because of merge conflicts in the changelog. I think it makes sense to fix that when I'm otherwise ready to merge.

File: lib/rubocop/cop/layout/hash_alignment.rb [hunk 3]
```diff
@@ -248,10 +248,20 @@ def check_pairs(node)
           add_offences
         end
 
+        def specific_message(format)
```
Comment (buehmann) [inline lib/rubocop/cop/layout/hash_alignment.rb]: The `MSG` constant near the top of the class can be removed then, can't it?

File: lib/rubocop/cop/layout/hash_alignment.rb [hunk 4]
```diff
@@ -248,10 +248,20 @@ def check_pairs(node)
...
+          messages = { KeyAlignment => 'Align the keys of a hash literal if '\
+                      'they span more than one line.',
+                       SeparatorAlignment => 'Align the separators of a hash '\
+                       'literal if they span more than one line.',
+                       TableAlignment => 'Align the keys and values of a hash '\
+                       'literal if they span more than one line.' }
```
Comment (buehmann) [inline lib/rubocop/cop/layout/hash_alignment.rb]: This is a constant. I think it would be better to treat it as such, that is, extract it as `MESSAGES` from the method.

And it would be great if you could add spaces in front of the backslashes and indent the second lines of the string literals. We do not have a cop for this yet, but see #6420. Something like this:

```ruby
        MESSAGES = {
          KeyAlignment => 'Align the keys of a hash literal ' \
            'if they span more than one line.',
```

**Comment by jsartin513** [comment]
Thanks @buehmann ! I've addressed your feedback, getting some test failures on CircleCI that seem unrelated (a local `rake default` looks fine, and these errors existed in some previous runs). Any suggestions on debugging that, or should I leave it alone for now?

**Comment by buehmann** [comment]
@jsartin513 Thanks! I believe those test failures will be fixed by https://github.com/rubocop-hq/rubocop/pull/7597

**Comment by jsartin513** [comment]
Great, thank you @buehmann . 

Is there anything else I should do to push this forwards, or do you take it from here?

**Comment by koic** [comment]
Yeah, #7597 has been merged.

**Comment by koic** [comment]
@jsartin513 Can you rebase with the latest master branch?

**Comment by jsartin513** [comment]
@koic Done and all checks are passing now!

File: CHANGELOG.md [hunk 5]
```diff
@@ -11,6 +11,7 @@
 * [#7193](https://github.com/rubocop-hq/rubocop/issues/7193): Prevent `Style/PercentLiteralDelimiters` from changing `%i` literals that contain escaped delimiters. ([@buehmann][])
 * [#7590](https://github.com/rubocop-hq/rubocop/issues/7590): Fix an error for `Layout/SpaceBeforeBlockBraces` when using with `EnforcedStyle: line_count_based` of `Style/BlockDelimiters` cop. ([@koic][])
 * [#7569](https://github.com/rubocop-hq/rubocop/issues/7569): Make `Style/YodaCondition` accept `__FILE__ == $0`. ([@koic][])
+* [#7291](https://github.com/rubocop-hq/rubocop/issues/7291): Fix misleading error messages in `Layout/AlignHash` cop to specify how to align the hash. ([@jsartin513][])
```
Comment (koic) [inline CHANGELOG.md]: I think changelog entry is unnecessary because this update does not change a behavior of the `Layout/HashAlignment` cop feature.

**Comment by bbatsov** [comment]
Thanks for tackling this!
