### PR TITLE
[Fix #6274] Don't cache corrected status

### LINKED ISSUE #6274: Rubocop caches "[Corrected]" in the message even when not correcting
If rubocop with auto-correct was used on a file and file is then restored, that running rubocop without auto-correct shows output as if it was auto correcting.

## Steps to reproduce the problem

Create file `test.rb` with following content:
```ruby
def hello
  {:foo => :bar}
end
```

Run `rubocop` and get output:
```
Inspecting 1 file
C

Offenses:

test.rb:2:3: C: Layout/SpaceInsideHashLiteralBraces: Space inside { missing. (https://github.com/rubocop-hq/ruby-style-guide#spaces-operators)
  {:foo => :bar}
  ^
test.rb:2:4: C: Style/HashSyntax: Use the new Ruby 1.9 hash syntax. (https://github.com/rubocop-hq/ruby-style-guide#hash-literals)
  {:foo => :bar}
   ^^^^^^^
test.rb:2:16: C: Layout/SpaceInsideHashLiteralBraces: Space inside } missing. (https://github.com/rubocop-hq/ruby-style-guide#spaces-operators)
  {:foo => :bar}
               ^

1 file inspected, 3 offenses detected
```

Run `rubocop --auto-correct` and get output:
```
Inspecting 1 file
C

Offenses:

test.rb:2:3: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside { missing. (https://github.com/rubocop-hq/ruby-style-guide#spaces-operators)
  {:foo => :bar}
  ^
test.rb:2:4: C: [Corrected] Style/HashSyntax: Use the new Ruby 1.9 hash syntax. (https://github.com/rubocop-hq/ruby-style-guide#hash-literals)
  {:foo => :bar}
   ^^^^^^^
test.rb:2:16: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside } missing. (https://github.com/rubocop-hq/ruby-style-guide#spaces-operators)
  {:foo => :bar}
               ^

1 file inspected, 3 offenses detected, 3 offenses corrected
```

File content is now:
```ruby
def hello
  { foo: :bar }
end
```

Restore the content of the file and run `rubocop` and get output as if `--auto-correct` was used:
```
Inspecting 1 file
C

Offenses:

test.rb:2:3: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside { missing. (https://github.com/rubocop-hq/ruby-style-guide#spaces-operators)
  {:foo => :bar}
  ^
test.rb:2:4: C: [Corrected] Style/HashSyntax: Use the new Ruby 1.9 hash syntax. (https://github.com/rubocop-hq/ruby-style-guide#hash-literals)
  {:foo => :bar}
   ^^^^^^^
test.rb:2:16: C: [Corrected] Layout/SpaceInsideHashLiteralBraces: Space inside } missing. (https://github.com/rubocop-hq/ruby-style-guide#spaces-operators)
  {:foo => :bar}
               ^

1 file inspected, 3 offenses detected, 3 offenses corrected
```

File doesn't change from original.

## RuboCop version

```
0.59.0 (using Parser 2.5.1.2, running on ruby 2.4.4 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by jekuta**
It seems to me that this issue was introduced with the addition of caching for auto-correct (#5857). When we auto-correct a file we also cache all the offenses that were found. However we cache these issues with the status `:corrected`. 
If someone now reverts the those changes and inspects the file again, the offenses will get pulled from the cache, but since the status is `:corrected` on those offenses, the user will also receive an output saying the offenses were corrected, as if they ran rubocop with auto-correct.

Since the cache is about saving the offenses of the original file, and when we run the auto-correct we are not using the cache for files that have offenses, it seems to me that the most obvious solution is to cache the offenses always with the flag `:uncorrected`.

Closes #6274

### CODE REVIEW

File: spec/rubocop/result_cache_spec.rb [hunk 1]
```diff
@@ -45,6 +45,28 @@ def abs(path)
       end
     end
 
+    context 'when offences are saved by autocorrect run' do
```
Comment (Drenmi) [inline spec/rubocop/result_cache_spec.rb]: Could you please include a link to the issue in a comment above this line, to indicate that this fixes a regression? 🙂

Comment (jonas054) [reply spec/rubocop/result_cache_spec.rb]: And change spelling to "offenses".

**Comment by jonas054** [comment]
:+1: Looks good!

**Comment by bbatsov** [comment]
Thanks!
