### PR TITLE
[Fix #7177] Do not insert spaces into string literals when aligning

### LINKED ISSUE #7177: Layout/IndentAssignment breaks some code
## Expected behavior

Do not modify contents in String.

## Actual behavior

Insert spaces into string literal.

## Steps to reproduce the problem

```console
% cat space.rb
# frozen_string_literal: true

def foo
  str =
'a
b
c'
end
p foo == "a\nb\nc"
% ruby space.rb
true
% rubocop -a space.rb
Inspecting 1 file
W

Offenses:

space.rb:4:3: W: Lint/UselessAssignment: Useless assignment to variable - str.
  str =
  ^^^
space.rb:5:1: C: [Corrected] Layout/IndentAssignment: Indent the first line of the right-hand-side of a multi-line assignment.
'a ...
^^

1 file inspected, 2 offenses detected, 1 offense corrected
% cat space.rb
# frozen_string_literal: true

def foo
  str =
    'a
    b
    c'
end
p foo == "a\nb\nc"
% ruby space.rb
false
```

## RuboCop version

```
0.72.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)
```

### LINKED ISSUE #7370: Layout/IndentationConsistency adds spaces to multi-line strings
--------

## Expected behavior

Ignore multi-line strings

## Steps to reproduce the problem

```
$ cat test.rb
  x = 'a'
y = 'b
c'
```

```
$ rubocop --auto-correct --only Layout/IndentationConsistency ./test.rb
Inspecting 1 file
C

Offenses:

test.rb:2:1: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
y = 'b ...
^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

```
$ cat test.rb
  x = 'a'
  y = 'b
  c'
```

```
"b\nc" == "b\n  c"
 => false
```

## RuboCop version

```
0.74.0 (using Parser 2.6.4.1, running on ruby 2.3.3 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by buehmann**
This fixes #7177 and fixes #7370.

There was a bug in the `AlignmentCorrector` used by many cops to shift pieces of code to the left or right: The corrector already knew not to touch the contents of some heredocs, but was not aware that the contents of other string literals must not be changed either. So it happily inserted or removed leading spaces inside string literals.

I started by writing some specs for the `AlignmentCorrector` because there were none and that class was only implicitly covered by specs in the cops that use the corrector.

While doing that I stumbled across a few bugs/shortcomings in the heredoc handling and fixed them straight away. Finally it felt safe enough to teach the corrector to recognize and avoid regular string literals.

In order to exercise the `AlignmentCorrector` in the specs in a concise way independent of actual cops, I added a little cop `Test/AlignmentDirective` that reacts to comments such as `# << 4` in the code and shifts the code into the indicated direction. I am not 100% convinced of this approach, but it is the best one I have come up with so far.

### CODE REVIEW

File: lib/rubocop/cop/correctors/alignment_corrector.rb [hunk 1]
```diff
@@ -39,27 +41,42 @@ def align_end(processed_source, node, align_to)
...
+          if node.heredoc?
+            node.loc.heredoc_body.join(node.loc.heredoc_end)
+          else
+            inside_regular_string_range(node)
+          end
+        end
+
+        def inside_regular_string_range(node)
+          loc = node.location
+          return unless loc.respond_to?(:begin) && loc.respond_to?(:end)
```
Comment (Drenmi) [inline lib/rubocop/cop/correctors/alignment_corrector.rb]: Would be cool to extract these two guard clause conditions into a named method. WDYT?

File: lib/rubocop/cop/correctors/alignment_corrector.rb [hunk 2]
```diff
@@ -39,27 +41,42 @@ def align_end(processed_source, node, align_to)
         private
 
         def autocorrect_line(corrector, line_begin_pos, expr, column_delta,
-                             heredoc_ranges)
+                             taboo_ranges)
```
Comment (Drenmi) [inline lib/rubocop/cop/correctors/alignment_corrector.rb]: Nice! I really like the choice of naming here. 👍

File: lib/rubocop/cop/correctors/alignment_corrector.rb (hunk 1 above)
Comment (buehmann) [reply lib/rubocop/cop/correctors/alignment_corrector.rb]: Sounds good. After extracting the guard clause, the remaining method begged me to be inlined. 😉 I also added some comments.

**Comment by bbatsov** [comment]
Looks great! Just squash that fixup commit.

**Comment by buehmann** [comment]
> Just squash that fixup commit.

Done.

**Comment by bbatsov** [comment]
Thanks!
