### PR TITLE
[Fix #9237] Add `IgnoredPatterns` configuration to `Lint/UnreachableLoop`

### LINKED ISSUE #9237: Lint/UnreachableLoop false positive with should_receive and raise in block
## Expected behavior

rubocop should not identify this as an unreachable loop.

## Actual behavior

rubocop identifies this as an unreachable loop.

## Steps to reproduce the problem

test_spec.rb:

```ruby
# frozen_string_literal: true

class SomeClass; end

describe 'test' do
  it 'test' do
    SomeClass.should_receive(:test).exactly(2).times { raise StandardError }
  end
end
```

```
For /private/tmp: Default configuration from /Users/me/.rvm/gems/ruby-2.4.2/gems/rubocop-1.6.1/config/default.yml
Inspecting 1 file
Scanning /private/tmp/test_spec.rb
Loading cache from /Users/me/.cache/rubocop_cache/0fe4423234f49f9a7a29f384c05d385bdc87c27f/6d7a3b621ca1730e04accd938619e4bdab66cfb1/cbd2ebc1b9a3baa10e15b9523bb86be7ea95cc25
W

Offenses:

test_spec.rb:7:5: W: Lint/UnreachableLoop: This loop will have at most one iteration.
    SomeClass.should_receive(:test).exactly(2).times { raise StandardError }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
Finished in 0.10298199998214841 seconds

```

## RuboCop version

```
$ rubocop -V
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.10-compliant syntax, but you are running 2.4.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
1.6.1 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.4.2 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
In #9237:

```
test_spec.rb:7:5: W: Lint/UnreachableLoop: This loop will have at most one iteration.
    SomeClass.should_receive(:test).exactly(2).times { raise StandardError }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`Lint/UnreachableLoop` is registering on `times` here because it is an [`enumerator_method`](https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/ast/node/mixin/method_identifier_predicates.rb#L10-L13). However, it is actually an RSpec method in this case.

Since we don't know what the receiver is, `IgnoredPatterns` can now be used to have the block receiver be allowed. For instance:

```yaml
Lint/UnreachableLoop:
  IgnoredPatterns:
    - !ruby/regexp /exactly\(\d+\)\.times/
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/unreachable_loop.rb [hunk 1]
```diff
@@ -70,7 +76,16 @@ module Lint
       #     raise NotFoundError
       #   end
       #
+      #   # bad
+      #   2.times { raise ArgumentError }
+      #
+      # @example IgnoredPatterns: [/exactly\(\d+\)\.times/]
```
Comment (koic) [inline lib/rubocop/cop/lint/unreachable_loop.rb:82]: I think this cop can ignore `exactly`, `at_least`, and `at_most` by default. I think it's much less likely that these will be false negatives in non-RSpec context than false positives in RSpec context.

```suggestion
      # @example IgnoredPatterns: [/(exactly|at_least|at_most)\(\d+\)\.times/] (default)
```

Comment (dvandersluis) [reply lib/rubocop/cop/lint/unreachable_loop.rb:82]: @koic sounds good! There's a whole bunch more methods that it picks up but this is a good start.

(Currently: `all?`, `any?`, `chain`, `chunk`, `chunk_while`, `collect`, `collect_concat`, `count`, `cycle`, `detect`, `downto`, `drop`, `drop_while`, `each`, `each_cons`, `each_entry`, `each_slice`, `each_with_index`, `each_with_object`, `entries`, `filter`, `find`, `find_all`, `find_index`, `first`, `flat_map`, `grep`, `grep_v`, `group_by`, `include?`, `inject`, `lazy`, `loop`, `map`, `map!`, `max`, `max_by`, `member?`, `min`, `min_by`, `minmax`, `minmax_by`, `none?`, `one?`, `partition`, `reduce`, `reject`, `reject!`, `reverse_each`, `select`, `select!`, `slice_after`, `slice_before`, `slice_when`, `sort`, `sort_by`, `sum`, `take`, `take_while`, `times`, `to_a`, `to_h`, `to_set`, `uniq`, `upto`, `zip`)

Comment (dvandersluis) [reply lib/rubocop/cop/lint/unreachable_loop.rb]: Updated!

**Review by koic — APPROVED** [review]
👍

File: config/default.yml [hunk 2]
```diff
@@ -2058,6 +2058,9 @@ Lint/UnreachableLoop:
   Description: 'This cop checks for loops that will have at most one iteration.'
   Enabled: true
   VersionAdded: '0.89'
+  VersionChanged: <<next>>
+  IgnoredPatterns:
```
Comment (bbatsov) [inline config/default.yml:2062]: I'd add a comment explaining what the default configuration targets, as it's not immediately obviously, especially if you're not using RSpec.

Comment (dvandersluis) [reply config/default.yml:2062]: Added a comment, let me know if you think it needs more info.

Comment (bbatsov) [reply config/default.yml:2062]: I think you may have forgotten to push.

Comment (dvandersluis) [reply config/default.yml:2062]: Oops! Sorry, pushed now.

Comment (dvandersluis) [reply config/default.yml:2062]: @bbatsov any changes necessary do you think?

Comment (bbatsov) [reply config/default.yml:2062]: Nope. I think we're good here.
