### PR TITLE
[Fix #9097] Fix a false positive for `Layout/EmptyLinesAroundArguments`

### LINKED ISSUE #9097: EmptyLinesAroundArguments: False positive
## Input

```ruby
# frozen_string_literal: true

def execute
  ::Redacted.
    redacted(@redacted).
    redacted2(@redacted2).
    redacted3(redacted).

    # redacted
    # redacted
    # blank lines help the reader understand that these comments pertain only to
    # the one following method call (`references`)
    # redacted
    # redacted
    references(:redacted, :redacted2, :redacted3, :redacted4, :redacted5).

    redacted4(redacted2).
    redacted5(@redacted3).
    redacted6(redacted: true)
end
```

## Expected behavior

No offenses expected

## Actual behavior

```
bin/rubocop input.rb
Inspecting 1 file
C

Offenses:

input.rb:16:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

## Steps to reproduce the problem

See input above.

## RuboCop version

```
bundle exec rubocop -V
1.4.2 (using Parser 2.7.2.0, rubocop-ast 1.2.0, running on ruby 2.6.6 x86_64-darwin19)
  - rubocop-rails 2.8.1
  - rubocop-rspec 2.0.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #9097.

This PR fixes a false positive for `Layout/EmptyLinesAroundArguments` when blank line is inserted between method with arguments and receiver.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/empty_lines_around_arguments.rb [hunk 1]
```diff
@@ -45,7 +45,8 @@ class EmptyLinesAroundArguments < Base
         MSG = 'Empty line detected around arguments.'
 
         def on_send(node)
-          return if node.single_line? || node.arguments.empty?
+          return if node.single_line? || node.arguments.empty? ||
+                    node.receiver && node.receiver.loc.last_line != node.loc.selector.line
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/empty_lines_around_arguments.rb:49]: I'd probably wrap this in a method, as it's a bit hard to understand as it is.

**Comment by bbatsov** [comment]
Btw, I'm wondering if that's actually a bug or a feature, as we don't have another cop checking for empty lines between the receiver and the method name, and in general it seems weird to me to have this whitespace.

**Comment by bbatsov** [comment]
Forget what I said, it's definitely a bug, but probably something should be checking about blank lines in method chains independently.

File: lib/rubocop/cop/layout/empty_lines_around_arguments.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/layout/empty_lines_around_arguments.rb]: Sure! I updated this PR.

**Comment by koic** [comment]
> probably something should be checking about blank lines in method chains independently.

Yep. I think it can be solved by another role (feature) :-)

**Comment by bbatsov** [comment]
Thanks!
