### PR TITLE
[Fix #8726] Fix a false positive for `Naming/VariableNumber`

### LINKED ISSUE #8726: Naming/VariableNumber False positive detection with non ascii chars
emparejó is not a variable number, and is in normalcase

```
módulos/triggers.rb:374:13: C: Naming/VariableNumber: Use normalcase for variable numbers.
            emparejó = true
            ^^^^^^^^

```

--------

## Expected behavior

Any detection

## Actual behavior

A false positive detection

## Steps to reproduce the problem

Create a variable 'emparejó'

## RuboCop version

```
$ [bundle exec] rubocop -V
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.0, running on ruby 2.6.6 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #8726.

Fix a false positive for `Naming/VariableNumber` when naming multibyte character variable name.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

File: spec/rubocop/cop/naming/variable_number_spec.rb [hunk 1]
```diff
@@ -98,6 +99,7 @@ def method(funnyArg1); end
     it_behaves_like 'accepts', 'normalcase', '_foo'
     it_behaves_like 'accepts', 'normalcase', '@foo'
     it_behaves_like 'accepts', 'normalcase', '@__foo__'
+    it_behaves_like 'accepts', 'snake_case', 'emparejó'
```
Comment (dvandersluis) [inline spec/rubocop/cop/naming/variable_number_spec.rb:102]: Should this have been `normalcase` instead of `snake_case`?

File: spec/rubocop/cop/naming/variable_number_spec.rb [hunk 2]
```diff
@@ -139,6 +141,7 @@ def method(funnyArg_1); end
     it_behaves_like 'accepts', 'non_integer', '_'
     it_behaves_like 'accepts', 'non_integer', '_foo'
     it_behaves_like 'accepts', 'non_integer', '@__foo__'
+    it_behaves_like 'accepts', 'snake_case', 'emparejó'
```
Comment (dvandersluis) [inline spec/rubocop/cop/naming/variable_number_spec.rb:144]: Same thing here.
