### PR TITLE
[Fix #5799] Check only top-level includes on class/module def

### LINKED ISSUE #5799: Style/MixinGrouping triggers inappropriately on RSpec "include" usage
*Be clear, concise and precise in your description of the problem.
Open an issue with a descriptive title and a summary in grammatically correct,
complete sentences.*

*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable RuboCop and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all text above the horizontal
rule with your own words.*

--------

## Expected behavior

No offenses detected.

## Actual behavior

```

spec/models/props/employees/basic_props_spec.rb:14:37: C: Style/MixinGrouping: Put include mixins in separate statements.
  it { expect(subject[:locales]).to include { { code: :en, label: 'English (US English)' } } }
                                    ^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

Create an RSpec file, put this code in it:

```
describe SomeClass do
  it { expect(subject[:locales]).to include { { code: :en, label: 'English (US English)' } } }
end
```

Run `rubocop` over this file. It should report the offense.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.4.2 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by Darhazer**
* Replaced the test case 'when include call is an argument to another method' with the minimum reproducible example of the bug
* Changed the cop to look for class and module definition, instead of inspecting each send node

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/mixin_grouping.rb [hunk 1]
```diff
@@ -36,12 +36,17 @@ class MixinGrouping < Cop
         MIXIN_METHODS = %i[extend include prepend].freeze
         MSG = 'Put `%<mixin>s` mixins in %<suffix>s.'.freeze
 
-        def on_send(node)
-          return unless node.macro? && MIXIN_METHODS.include?(node.method_name)
+        def on_class(node)
+          begin_node = node.child_nodes.find(&:begin_type?) || node
+          begin_node.each_child_node(:send).select(&:macro?).each do |macro|
```
Comment (rrosenblum) [inline lib/rubocop/cop/style/mixin_grouping.rb]: It would be more performant to write this as

```ruby
begin_node.each_child_node(:send) do |child_node|
  next unless child_node.macro?
  ...
end
```

This would likely have minimal real world impact so don't feel obligated to make the change.

File: CHANGELOG.md [hunk 2]
```diff
@@ -11,6 +11,7 @@
 * [#5908](https://github.com/bbatsov/rubocop/pull/5908): Fix `Style/BracesAroundHashParameters` auto-correct going past the end of the file when the closing curly brace is on the last line of a file. ([@EiNSTeiN-][])
 * Fix a bug where `Style/FrozenStringLiteralComment` would be added to the second line if the first line is empty. ([@rrosenblum][])
 * [#5914](https://github.com/bbatsov/rubocop/issues/5914): Make `Layout/SpaceInsideReferenceBrackets` aware of `no_space` when using nested reference brackets. ([@koic][])
+* [#5799](https://github.com/bbatsov/rubocop/issues/5799): Fix false positive in `Style/MixinGrouping`. ([@Darhazer][])
```
Comment (rrosenblum) [inline CHANGELOG.md]: Can you provide more content on the condition that lead to the false positive?

File: lib/rubocop/cop/style/mixin_grouping.rb (hunk 1 above)
Comment (bbatsov) [reply lib/rubocop/cop/style/mixin_grouping.rb]: I'm fine with the current code, as it reads better and I don't think it will impact performance much.

**Comment by bbatsov** [comment]
Apart from the remark about the changelog entry - the code looks good to me.

**Comment by Darhazer** [comment]
Updated changelog entry.

**Comment by bbatsov** [comment]
👍
