### PR TITLE
[Fix #8035] Fix a false positive for `Lint/DeprecatedOpenSSLConstant`

### LINKED ISSUE #8035: Lint/DeprecatedOpenSSLConstant suggestion with double quoted string
```
a.rb:2:3: W: Lint/DeprecatedOpenSSLConstant: Use OpenSSL::Cipher.new('AES-256-cbc') instead of OpenSSL::Cipher::AES256.new('cbc').
  OpenSSL::Cipher::AES256.new('cbc')
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
a.rb:5:3: W: Lint/DeprecatedOpenSSLConstant: Use OpenSSL::Cipher.new('AES-256-"cbc"') instead of OpenSSL::Cipher::AES256.new("cbc").
  OpenSSL::Cipher::AES256.new("cbc")
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The suggestion is valid with single quoted strings, but broken with double quoted ones.

## Expected behavior

Suggestion should be `OpenSSL::Cipher::AES256.new("AES-256-cbc")` (preserving double quotes) at least, or one of the `OpenSSL::Cipher.ciphers` entries if we really want consistent casing.

## Actual behavior

`OpenSSL::Cipher.new('AES-256-"cbc"')` does not exist.

## Steps to reproduce the problem

```ruby
do_something do
  OpenSSL::Cipher::AES256.new("cbc")
end
```

and 
```sh
$ rubocop --only Lint/DeprecatedOpenSSLConstant
```

## RuboCop version

```
$ rubocop -V
0.84.0 (using Parser 2.7.1.2, rubocop-ast 0.0.3, running on ruby 2.6.3 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #8035.

This PR fixes a false positive for `Lint/DeprecatedOpenSSLConstant` when argument is a variable, method, or constant.

```console
% cat example.rb
MODE = 'cbc'
OpenSSL::Cipher::AES256.new(MODE)

% bundle exec rubocop --only Lint/DeprecatedOpenSSLConstant -a
(snip)

Offenses:

example.rb:2:1: W: [Corrected] Lint/DeprecatedOpenSSLConstant: Use
OpenSSL::Cipher.new('AES-256-MODE') instead of OpenSSL::Cipher::AES256.new(MODE).
OpenSSL::Cipher::AES256.new(MODE)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected

% cat example.rb
MODE = 'cbc'
OpenSSL::Cipher.new('AES-256-MODE')
```

RuboCop does not have a tracing feature a value of variable, (method,) and constant yet.
This PR accepts cases where these values are used to prevent auto-correction mistakes.

On the other hand, this change produces false negatives for the deprecated APIs.
If it is difficult to accept false negatives, I will update this PR to warn against these cases and auto-correction will not performed.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb [hunk 1]
```diff
@@ -66,6 +66,25 @@
...
+    RUBY
+  end
+
+  it 'does not register an offense with cipher constant and send argument is a method' do
+    expect_no_offenses(<<~RUBY)
+      OpenSSL::Cipher::AES128.new(do_something)
+    RUBY
+  end
+
+  it 'does not register an offense with cipher constant and argument is a consntant' do
```
Comment (valscion) [inline spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb:82]: Found a typo — I hope that this kind of drive-by review comment is OK to do and feels OK to you, @koic :heart:

```suggestion
  it 'does not register an offense with cipher constant and argument is a constant' do
```

Comment (koic) [reply spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb]: Oops! Thank you for your review :-)

**Comment by bbatsov** [comment]
Thanks!
