### PR TITLE
[Fix #6914] Fix an error for `Rails/RedundantAllowNil` when with interpolations

### LINKED ISSUE #6914: Rails/RedundantAllowNil crashes with interpolations
This seems to be related to #6882. RuboCop stumbles on dynamic validations, in this case with string interpolations

## Expected behavior

RuboCop finishes without errors

## Actual behavior

```
1 error occurred:
An error occurred while Rails/RedundantAllowNil cop was inspecting /path/to/my/class.rb:4:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
0.67.2 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-linux-gnu)
```

## Steps to reproduce the problem

This minimal class should reproduce the problem.
```
class Foo < ActiveRecord::Base
  validates :details, "path_to_dynamic_validation/#{with_interpolation}": true
end
```

## RuboCop version

```
0.67.2 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-linux-gnu)
```

### PR DESCRIPTION
**Pull request by Blue-Pix**
Fixes #6914.

This PR fixes the following error for Rails/RedundantAllowNil when with interpolations.

```ruby
class Foo < ActiveRecord::Base
  BAR = "sample"
  validates :name, "#{self::BAR}": true
end
```

```ruby
class SampleValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if value.size > 3
      record.errors.add(attribute, 'too long')
    end
  end
end
```

This is stacktrace.
```bash
$ rubocop app/models/foo.rb --only Rails/RedundantAllowNil -d
An error occurred while Rails/RedundantAllowNil cop was inspecting /myapp/app/models/foo.rb:3:2.
undefined method `value' for "s(:dsym,\n  s(:begin,\n    s(:const,\n      s(:self), :BAR)))":RuboCop::AST::Node
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/rails/redundant_allow_nil.rb [hunk 1]
```diff
@@ -79,7 +79,7 @@ def find_allow_nil_and_allow_blank(node)
           node.each_descendant do |descendant|
             next unless descendant.pair_type?
 
-            key = descendant.children.first.value
+            key = node_key(descendant.children.first)
```
Comment (koic) [inline lib/rubocop/cop/rails/redundant_allow_nil.rb]: The solution is to use `Node#source`.

```diff
diff --git a/lib/rubocop/cop/rails/redundant_allow_nil.rb b/lib/rubocop/cop/rails/redundant_allow_nil.rb
index be75c1592..2f5934b56 100644
--- a/lib/rubocop/cop/rails/redundant_allow_nil.rb
+++ b/lib/rubocop/cop/rails/redundant_allow_nil.rb
@@ -79,10 +79,10 @@ module RuboCop
           node.each_descendant do |descendant|
             next unless descendant.pair_type?

-            key = descendant.children.first.value
+            key = descendant.children.first.source

-            allow_nil = descendant if key == :allow_nil
-            allow_blank = descendant if key == :allow_blank
+            allow_nil = descendant if key == 'allow_nil'
+            allow_blank = descendant if key == 'allow_blank'

             break if allow_nil && allow_blank
           end
```

**Comment by koic** [comment]
Please add a test case to reproduce.

```diff
diff --git a/spec/rubocop/cop/rails/redundant_allow_nil_spec.rb b/spec/rubocop/cop/rails/redundant_allow_nil_spec.rb
index 0ce9ffd5a..760661d4a 100644
--- a/spec/rubocop/cop/rails/redundant_allow_nil_spec.rb
+++ b/spec/rubocop/cop/rails/redundant_allow_nil_spec.rb
@@ -73,4 +73,12 @@ RSpec.describe RuboCop::Cop::Rails::RedundantAllowNil do
       RUBY
     end
   end
+
+  context 'when using string interpolation' do
+    it 'registers no offense' do
+      expect_no_offenses(<<-'RUBY'.strip_indent)
+        validates :details, "path_to_dynamic_validation/#{with_interpolation}": true
+      RUBY
+    end
+  end
 end
```

File: lib/rubocop/cop/rails/redundant_allow_nil.rb (hunk 1 above)
Comment (Blue-Pix) [reply lib/rubocop/cop/rails/redundant_allow_nil.rb]: Thanks for a review!

**Comment by koic** [comment]
Looks good to me.
Can you squash your commits into one?

**Comment by bbatsov** [comment]
Thanks!
