### PR TITLE
[Fix #7363] Fix an incorrect autocorrect when multiline empty braces

### LINKED ISSUE #7363: Style/BlockDelimiters and Layout/SpaceInsideBlockBraces auto-corrections don't play well together
```
{
}
```

gets converted into 

`doend`

--------

## Expected behavior

`{}`

## Steps to reproduce the problem

```
$ cat test.rb
format.json {
}
```

```

$ rubocop --auto-correct --only Style/BlockDelimiters,Layout/SpaceInsideBlockBraces ./test.rb
Inspecting 1 file
C

Offenses:

test.rb:1:13: C: [Corrected] Style/BlockDelimiters: Avoid using {...} for multi-line blocks.
format.json {
            ^
test.rb:1:14: C: [Corrected] Layout/SpaceInsideBlockBraces: Space inside empty braces detected.
format.json { ...


1 file inspected, 2 offenses detected, 2 offenses corrected
```

```
$ cat test.rb
format.json doend
```

Error reported by rspec:

```
     Failure/Error: format.json doend

     NameError:
       undefined local variable or method `doend'
```

## RuboCop version

```
rubocop -V
0.74.0 (using Parser 2.6.4.0, running on ruby 2.3.3 x86_64-darwin18)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7363.

This PR fixes an incorrect autocorrect for `Layout/SpaceInsideBlockBraces` and `Style/BlockDelimiters` when using multiline empty braces.

As a result of applying the two auto-corrections, the code is converted to have the following syntax error code:

```console
% cat example.rb
do_something {
}

% rubocop --auto-correct --only Style/BlockDelimiters,Layout/SpaceInsideBlockBraces

% cat example.rb
do_something doend
```

`doend` is because `Layout/SpaceInsideBlockBraces` cop auto-corrects to single-line empty braces:

```console
% rubocop --auto-correct --only Layout/SpaceInsideBlockBraces

% cat example.rb
do_something {}
```

and `Style/BlockDelimiters` auto-corrects to `do` ... `end`.

```console
% rubocop --auto-correct --only Style/BlockDelimiters

% cat example.rb
do_something do
end
```

This PR prevents auto-correction to syntax error code by keeping multiline empty braces.

```console
% rubocop --auto-correct --only Layout/SpaceInsideBlockBraces
Inspecting 1 file
.

1 file inspected, no offenses detected

% cat example.rb
do_something {
}
```

This is the same intent as not converting multiline empty `do` ... `end` to single line empty `do` ... `end`.

As a result, it is auto-corrected to the following valid syntax code.

```console
% rubocop --auto-correct --only Style/BlockDelimiters,Layout/SpaceInsideBlockBraces

% cat example.rb
do_something do
end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/space_inside_block_braces.rb [hunk 1]
```diff
@@ -82,7 +82,7 @@ class SpaceInsideBlockBraces < Cop
         include RangeHelp
 
         def on_block(node)
-          return if node.keywords?
+          return if node.keywords? || node.body.nil? && node.multiline?
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/space_inside_block_braces.rb]: I'd put this in a separate `return` and a remark why this branch exists.

Comment (koic) [reply lib/rubocop/cop/layout/space_inside_block_braces.rb]: Yeah, I updated it!

**Comment by bbatsov** [comment]
Thanks!
