### PR TITLE
[Fix #8708] Fix bad regexp recognition in `Lint/OutOfRangeRegexpRef` when there are multiple regexps

### LINKED ISSUE #8708: Lint/OutOfRangeRegexpRef picks wrong regex
## Actual behavior

`Lint/OutOfRangeRegexpRef` seems confused when multiple regular expressions are present on a single line, and picks the _wrong_ Regex, leading to false positives _and_ true negatives.

## Steps to reproduce the problem

In the following example `Lint/OutOfRangeRegexpRef` seems to pick the first Regex, in the `gsub` call (`/\s+/`), instead of the final Regex that is populating `$1` (`/foo(bar)/`):

```ruby
if "foo bar".gsub(/\s+/, "") =~ /foo(bar)/
  p $1
end
```
```
x.rb:2:5: W: Lint/OutOfRangeRegexpRef: Do not use out of range reference for the Regexp.
  p $1
    ^^
```

Rubocop won't complain anymore when the Regex in the `gsub` call is modified to capture, but still won't complain when changing the second regex to not capture:

```ruby
if "foo bar".gsub(/(\s+)/, "") =~ /foobar/
  p $1 # always nil
end
```

## RuboCop version

```
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.4.0, running on ruby 2.6.6 x86_64-linux-musl)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
`Lint/OutOfRangeRegexpRef` was using the wrong regexp to determine how many capturing groups there are, in a few cases, that are now fixed. I also updated the error message to be a bit more straightforward because I found it hard to understand, but please let me know if you'd like me to reword or revert.

Also I have no idea what the plural of `regexp` should be. 😅 

Fixes #8708.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by marcandre** [comment]
Update: I started reviewing, love the message changes 👍
It would be quite nice to have a `after_send` callback of some kind, instead of messing around with `ignore` things... I'm checking a few things on the `Commissionner` side.

**Comment by dvandersluis** [comment]
@marcandre thanks! Let me know if you want me to change something.

**Comment by marcandre** [comment]
Could you check if it also has this issue? #8708

**Comment by dvandersluis** [comment]
I'm not sure what you mean? This PR is for that issue haha 😅

**Comment by dvandersluis** [comment]
Oh I assume you meant #8862 / #8863 ? That's a different cop so there shouldn't be a conflict.

**Comment by dvandersluis** [comment]
Updated to fix the changelog now that 0.93 is out.

**Review by marcandre — COMMENTED** [review]
> Oh I assume you meant #8862 / #8863 ? That's a different cop so there shouldn't be a conflict.

Ooops, yes, my double mistake 🤦‍♂️, need coffee apparently

File: lib/rubocop/cop/lint/out_of_range_regexp_ref.rb [hunk 1]
```diff
@@ -58,7 +58,8 @@ def on_nth_ref(node)
           backref, = *node
           return if @valid_ref.nil?
 
-          add_offense(node) if backref > @valid_ref
+          message = format(MSG, backref: backref, count: @valid_ref == 0 ? 'no' : @valid_ref)
```
[the remark this answers is not in the document]
Comment (dvandersluis) [reply lib/rubocop/cop/lint/out_of_range_regexp_ref.rb]: @marcandre absolutely! I've made this change now.

**Comment by marcandre** [comment]
So I checked about adding `on_after_xxx` and it's sadly in a hotspot, it would cost a 5% slowdown which is pretty sad 😿
I could add it only just for `send`, wouldn't be so bad, or I could introduce some API to add a callback on the fly, but that feels a bit ugly...
So I'm tempted to just leave this as is (after the conflict is resolved...) even though the logic is quite convoluted just because we don't currently have a way do processing after a particular node's children are processed...

**Comment by dvandersluis** [comment]
@marcandre fixed the conflict, happy to make other changes if you want, just let me know!

**Comment by marcandre** [comment]
Update: I opened #8889; I'm waiting a day or two to see if the latest bug fix release is stable and I'll merge that, which would give you the `on_after_send` that would simplify the processing I believe.

**Comment by marcandre** [comment]
`after_send` is now available...

**Comment by dvandersluis** [comment]
@marcandre cool thanks, I’ll probably Be able to update this tomorrow!

**Comment by marcandre** [comment]
I believe this or can be simplified without using an ignore list...

**Comment by dvandersluis** [comment]
@marcandre updated to use `after_send`, thanks that really simplified it!

File: lib/rubocop/cop/lint/out_of_range_regexp_ref.rb [hunk 2]
```diff
@@ -19,7 +19,7 @@ module Lint
       #   puts $1 # => foo
       #
       class OutOfRangeRegexpRef < Base
-        MSG = 'Do not use out of range reference for the Regexp.'
+        MSG = '$%<backref>s is out of range (%<count>s Regexp capture groups detected).'
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/out_of_range_regexp_ref.rb:22]: I'd use `regexp` here without the capital letter. No idea why it was there in the first place.

File: spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb [hunk 3]
```diff
@@ -8,39 +8,39 @@
...
+           ^^ $3 is out of range (2 Regexp capture groups detected).
     RUBY
   end
 
   it 'registers an offense when out of range references are used for mix of numbered and named captures' do
     expect_offense(<<~RUBY)
       /(?<foo>FOO)(BAR)/ =~ "FOOBAR"
       puts $2
-           ^^ Do not use out of range reference for the Regexp.
+           ^^ $2 is out of range (1 Regexp capture groups detected).
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb:35]: It'd be a bit better to say "1 group", but it's not a big deal.

File: CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,9 @@
 
 ## master (unreleased)
 
+### Bug fixes
```
Comment (bbatsov) [inline CHANGELOG.md:5]: Please, add a blank line after the heading.

File: spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb (hunk 3 above)
Comment (dvandersluis) [reply spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb:35]: I agree but I'm not sure how to easily achieve this?

Comment (dvandersluis) [reply spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb:35]: Never mind I just implemented it directly, should be ok.

**Comment by dvandersluis** [comment]
@bbatsov made all the requested changes, thanks!

**Comment by bbatsov** [comment]
Can you also address the changelog conflict?

**Comment by marcandre** [comment]
> Can you also address the changelog conflict?

You can use `rake changelog:fix` and al. in the future 😄

**Comment by dvandersluis** [comment]
@bbatsov @marcandre added the changelog item in `changelog/`

**Comment by marcandre** [comment]
Outstanding work @dvandersluis 👍 
Thanks!
