### PR TITLE
[Fix #7899] Fix an infinite loop error for `Layout/SpaceAroundOperators`

### LINKED ISSUE #7899: Infinite loop detected (rubocop failed with code=2)
I have the following code

```
test123456                = nil 
test1234                   = nil
test12345678910            = nil
test1_test2_test3_test4_12 = nil
```
--------

## Expected behavior
Align `=`
```
test123456                 = nil 
test1234                   = nil
test12345678910            = nil
test1_test2_test3_test4_12 = nil
```
Describe here how you expected RuboCop to behave in this particular situation.

## Actual behavior
```
# > rubocop rubocop_error.rb -a
# Inspecting 1 file
# C
#
# Offenses:
#
# rubocop_error.rb:1:27: C: [Corrected] Layout/SpaceAroundOperators: Operator = should be surrounded by a single space.
# test123456                = nil 
#                           ^
# rubocop_error.rb:1:28: C: [Corrected] Layout/SpaceAroundOperators: Operator = should be surrounded by a single space.
# test123456                 = nil
#                            ^
# rubocop_error.rb:2:10: C: [Corrected] Layout/ExtraSpacing: = is not aligned with the preceding assignment.
# test1234 = nil
#          ^
# rubocop_error.rb:2:28: C: [Corrected] Layout/ExtraSpacing: = is not aligned with the preceding assignment.
# test1234                   = nil
#                            ^
# rubocop_error.rb:2:28: C: [Corrected] Layout/SpaceAroundOperators: Operator = should be surrounded by a single space.
# test1234                   = nil
#                            ^
# rubocop_error.rb:3:17: C: [Corrected] Layout/ExtraSpacing: = is not aligned with the preceding assignment.
# test12345678910 = nil
#                 ^
# rubocop_error.rb:3:28: C: [Corrected] Layout/ExtraSpacing: = is not aligned with the preceding assignment.
# test12345678910            = nil
#                            ^
# rubocop_error.rb:3:28: C: [Corrected] Layout/SpaceAroundOperators: Operator = should be surrounded by a single space.
# test12345678910            = nil
#                            ^
# rubocop_error.rb:4:28: C: [Corrected] Layout/ExtraSpacing: = is not aligned with the preceding assignment.
# test1_test2_test3_test4_12 = nil
#                            ^
#
# 0 files inspected, 9 offenses detected, 9 offenses corrected
# Infinite loop detected in rubocop_error.rb.
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:287:in `check_for_infinite_loop'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:270:in `block in iterate_until_no_changes'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `loop'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:240:in `do_inspection_loop'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:143:in `file_offense_cache'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:117:in `file_offenses'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:108:in `process_file'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `reduce'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:73:in `inspect_files'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/runner.rb:39:in `run'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli/command.rb:10:in `run'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli/environment.rb:17:in `run'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:65:in `run_command'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:72:in `execute_runners'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/lib/rubocop/cli.rb:41:in `run'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/exe/rubocop:13:in `block in <top (required)>'
# .rbenv/versions/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
# .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.82.0/exe/rubocop:12:in `<top (required)>'
# .rbenv/versions/2.6.5/bin/rubocop:23:in `load'
# .rbenv/versions/2.6.5/bin/rubocop:23:in `<main>'
```
## Steps to reproduce the problem

Save the first snippet as `rubocop_error.rb` and execute
```
> rubocop rubocop_error.rb -a
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.82.0 (using Parser 2.7.1.1, running on ruby 2.6.5 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #7899.

This PR fixes the following infinite loop error for `Layout/SpaceAroundOperators` with `Layout/ExtraSpacing` when using `ForceEqualSignAlignment: true`.

```console
% bundle exec rubocop -V
0.82.0 (using Parser 2.7.1.1, running on ruby 2.7.0 x86_64-darwin17)

% cat .rubocop.yml
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

% cat example.rb
test123456                = nil
test1234                   = nil
test1_test2_test3_test4_12 =nil

% bundle exec rubocop -a --only Layout/ExtraSpacing,Layout/SpaceAroundOperators
(snip)

Infinite loop detected in /Users/koic/src/github.com/koic/rubocop-issues/7899/example.rb.
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:287:in `check_for_infinite_loop'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:270:in `block in iterate_until_no_changes'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:269:in `loop'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/space_around_operators.rb [hunk 1]
```diff
@@ -170,6 +170,19 @@ def offense(type, operator, with_space, right_operand)
           yield msg if msg
         end
 
+        def enclose_operator_in_space(corrector, range)
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/space_around_operators.rb:173]: I think it's `enclose_with`, not `enclose_in`.

Comment (koic) [reply lib/rubocop/cop/layout/space_around_operators.rb]: I updated this method name. Thank you!
