### PR TITLE
[Fix #5406] Add new `Layout/ClosingHeredocIndentation` cop.

### LINKED ISSUE #5406: Closing Heredoc Indentation
When autocorrecting heredoc indentation, the heredoc close is ignored. I think I would expect it to be realigned with the heredoc open.

The following examples use
```ruby
class Foo
  <<-SQL.strip_indent
    foo
SQL
end
```
as starting code.

--------

## Expected behavior

When running rubocop, I'd expect to see a violation for `SQL` needing to be indented two spaces and for the autocorrect to result in
```ruby
class Foo
  <<-SQL.strip_indent
    foo
  SQL
end
```

## Actual behavior

Instead, there are no violations.

## Steps to reproduce the problem

See above.

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.3.1 x86_64-linux)
```

## Further Discussion

I'm not sure whether this would fall on the IndentHeredoc rule (which currently only handles the innards of the heredoc), the IndentationWidth rule (which handles the opening), a new ClosingHeredocIndentation rule, or somewhere else. I'd be happy to work on this if given some indication of a preferred location.

### PR DESCRIPTION
**Pull request by siegfault**
## Summary

This cop checks the indentation of here document closings.

### Bad Case

```ruby
class Foo
  def bar
    <<~SQL
      'Hi'
  SQL
  end
end
```

### Good Case

```ruby
class Foo
  def bar
    <<~SQL
      'Hi'
    SQL
  end
end
```
-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by siggymcfried** [comment]
There are a few autocorrections in here that seem potentially questionable, so I'd love someone to weigh in!

File: lib/rubocop/cop/layout/closing_heredoc_indentation.rb [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+
+        def heredoc_opening(node)
+          node.loc.expression.source_line
+        end
+
+        def heredoc_closing(node)
+          node.loc.heredoc_end.source_line
+        end
+
+        def indent_level(str)
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: Can change `str` to something meaningful, e.g. `source_line`. 🙂

File: lib/rubocop/cop/layout/closing_heredoc_indentation.rb [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+          str[/\A */].size
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: I tend to prefer using `#length` for strings, as it makes more sense, conceptually. 🙂

File: lib/rubocop/cop/layout/closing_heredoc_indentation.rb [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+      #     end
+      #   end
+      #
+      class ClosingHeredocIndentation < Cop
+        include Heredoc
+
+        MSG = '`%<closing>s` is not aligned with `%<opening>s`.'.freeze
+
+        def on_heredoc(node)
+          return if opening_indentation(node) == closing_indentation(node)
```
Comment (Drenmi) [inline lib/rubocop/cop/layout/closing_heredoc_indentation.rb]: Crisp! This is very easy to understand. 👍

File: spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+  end
+
+  it 'registers an offence for bad indentation of a closing heredoc' do
+    expect_offense(<<-RUBY.strip_indent)
+      class Test
+        def foo
+          <<-SQL
+            bar
+        SQL
+      ^^^^^ `SQL` is not aligned with `<<-SQL`.
```
Comment (Drenmi) [inline spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb]: Can we get rid of the overshooting highlight?

**Comment by Drenmi** [comment]
Great start! Definitely some cases in there that might need discussing.

File: spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb (hunk 4 above)
Comment (siggymcfried) [reply spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb]: I'd love to! Might need a pointer though. I _think_ the root is that https://github.com/bbatsov/rubocop/blob/ef1daf7e97e2362ceaac2a933b243a753d1bd3a9/lib/rubocop/cop/offense.rb#L147-L149 is returning `0...5`, potentially related to https://github.com/bbatsov/rubocop/blob/ef1daf7e97e2362ceaac2a933b243a753d1bd3a9/lib/rubocop/cop/offense.rb#L113-L115 returning 0.

I think it's related to
```ruby
irb(main):009:0> Parser::CurrentRuby.parse("     <<-SQL\nfoo\n    SQL").loc
=> #<Parser::Source::Map::Heredoc:0x0000555e4ccccf68 @heredoc_body=#<Parser::Source::Range (string) 12...16>, @heredoc_end=#<Parser::Source::Range (string) 16...23>, @expression=#<Parser::Source::Range (string) 5...11>, @node=s(:str, "foo\n")>
```
Would we expect `heredoc_end` to range from `20...23`?

**Comment by siggymcfried** [comment]
Thanks for the pointers @Drenmi! One question I'm not really sure about, but addressed the rest

File: spec/rubocop/cop/performance/regexp_match_spec.rb [hunk 5]
```diff
@@ -85,13 +85,13 @@ def foo
...
       end
-    RUBY
+                     RUBY
       def foo
         if #{correction}
           do_something
         end
       end
-    RUBY2
+                     RUBY2
```
Comment (koic) [inline spec/rubocop/cop/performance/regexp_match_spec.rb]: I think that this cop is useful 👍, but It may be strange to indent more than a strings written in a heredoc.

Comment (siggymcfried) [reply spec/rubocop/cop/performance/regexp_match_spec.rb]: I agree! I'd love advice about what this block should look like. I'd sort of expected the autocorrector to correct the opening heredocs to move them to the left
```ruby
include_examples :offense, "#{name} in method definition",
  <<-RUBY
    def foo
    end
  RUBY
```
or to move the code inside the heredoc to the right with the closing heredoc
```ruby
include_examples :offense, "#{name} in method definition",
                 <<-RUBY
                   def foo
                   end
                 RUBY
```
. What do we think should happen in this case?

**Comment by siggymcfried** [comment]
Any thoughts here?

File: spec/rubocop/cli/cli_autocorrect_spec.rb [hunk 6]
```diff
@@ -517,7 +517,7 @@ def func
             baz
           end
         end
-      RUBY
+    RUBY
```
Comment (Drenmi) [inline spec/rubocop/cli/cli_autocorrect_spec.rb]: Hm. This looks like the indentation was correct before. It's a continuation from L508, and should be indented one level deeper than that line. Correct?

File: spec/rubocop/cop/performance/regexp_match_spec.rb (hunk 5 above)
Comment (Drenmi) [reply spec/rubocop/cop/performance/regexp_match_spec.rb]: I'm not sure, but currently is a bit weird. As a general rule, I don't think the delimiter should ever be indented further than the content. Would you agree?

File: spec/rubocop/cli/cli_autocorrect_spec.rb (hunk 6 above)
Comment (siggymcfried) [reply spec/rubocop/cli/cli_autocorrect_spec.rb]: To be honest, I'm not sure. The corrected block aligns the closing heredoc with the equivalent of line 508 which I'd assumed was correct. Is this spec meant to test autocorrection of `InitialIndentation` violations as well as `ClosingHeredocIndentation`?

Comment (bbatsov) [reply spec/rubocop/cli/cli_autocorrect_spec.rb]: The indentation updates seems reasonable to me. I see we now always align the closing marker with the beginning of the line where the heredoc started.

**Comment by siegfault** [comment]
I'm not too sure where to go from here (ignoring resolving conflicts).

There are corrections that are arguably, but not obviously correct. Is there work to be done for those? 

Does the issue I noted about the overshooting highlight seem like a bug in parser or am I missing something nearer?

Thanks all for the feedback 😄

**Comment by bbatsov** [comment]
I'm overwhelmed with work these days, so I'll leave to @koic @pocke and @Drenmi to sort this out with you. :-)

**Comment by Drenmi** [comment]
Will have a look as soon as I can @siegfault. I'm attending a conference though, so it's unclear when that will be. Check-ins happen sporadically. Please be patient. 🙂

**Comment by siegfault** [comment]
No problem @Drenmi! I'm at a conference the latter half of this week as well 😄

File: spec/rubocop/cop/performance/regexp_match_spec.rb (hunk 5 above)
Comment (koic) [reply spec/rubocop/cop/performance/regexp_match_spec.rb]: Hm, I worried this change and I opened a PR #5943 😃
