### PR TITLE
[Fix #6052] Fix a false positive for `Style/SymbolProc`

### LINKED ISSUE #6052: Style/SymbolProc correction produces errors when the block has multiple arguments
Given the following:

```ruby
require 'pp'

class I
  attr_reader :ref

  def initialize ref
    @ref = ref
  end

  def hash
    @ref.hash
  end

  def eql? other
    @ref == other.ref
  end
end

i1 = I.new '1'
i2 = I.new '2'

h = {
  i2 => %w[two],
  i1 => %w[one],
}

sorted = h.sort_by { |i,| i.ref }

pp sorted
```

For the line `sorted = h.sort_by { |i,| i.ref }` rubocop says I must "Pass &:ref as an argument to sort_by instead of a block" but this change causes NoMethodError because #ref is called on an Array rather than the `I` object as specified.

## Expected behavior

Rubocop does not suggest any correction for this line under Style/SymbolProc.

## Actual behavior

```
$ rubocop --only Style/SymbolProc t.rb
Inspecting 1 file
C

Offenses:

t.rb:28:20: C: Style/SymbolProc: Pass &:ref as an argument to sort_by instead of a block.
sorted = h.sort_by { |i,| i.ref }
                   ^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

1. Write the above file to `t.rb`
1. Run `ruby t.rb`, note that it returns a sorted Array of Arrays
1. Run `rubocop --only Style/SymbolProc t.rb`
1. See "Pass &:ref as an argument to sort_by instead of a block."
1. Replace that line with `sorted = h.sort_by(&:ref)`
1. `ruby t.rb`, note that it fails with NoMethodError:

```
$ ruby t.rb
Traceback (most recent call last):
        2: from t.rb:27:in `<main>'
        1: from t.rb:27:in `sort_by'
t.rb:27:in `each': undefined method `ref' for [#<I:0x00007fe59592dad8 @ref="2">, ["two"]]:Array (NoMethodError)
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -v
0.57.2
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #6052.

This PR fixes a false positive for `Style/SymbolProc` when using block with adding a comma after the sole argument.

The following ASTs are the same.

```console
% bin/console
[1] pry(RuboCop)> RuboCop::ProcessedSource.new('h.sort_by { |i,| i.foo }', RUBY_VERSION.to_f).ast
=> s(:block,
  s(:send,
    s(:send, nil, :h), :sort_by),
  s(:args,
    s(:arg, :i)),
  s(:send,
    s(:lvar, :i), :foo))
[2] pry(RuboCop)> RuboCop::ProcessedSource.new('h.sort_by { |i| i.foo }', RUBY_VERSION.to_f).ast
=> s(:block,
  s(:send,
    s(:send, nil, :h), :sort_by),
  s(:args,
    s(:arg, :i)),
  s(:send,
    s(:lvar, :i), :foo))
```

So this implementation of PR uses `source` to decide whether to separate arguments with a comma.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/symbol_proc.rb [hunk 1]
```diff
@@ -40,6 +40,7 @@ def on_block(node)
             return if proc_node?(send_or_super)
             return if %i[lambda proc].include?(block_method_name)
             return if ignored_method?(block_method_name)
+            return if block_arg.source.include?(',')
```
Comment (bbatsov) [inline lib/rubocop/cop/style/symbol_proc.rb]: What if one of the args is "dfdome, dfdf"? Doesn't seem like a very reliable check to me.

Comment (koic) [reply lib/rubocop/cop/style/symbol_proc.rb]: Thanks for the review.
When multiple block arguments are given, I thought that it works well because this cop does not register offenses. However, it was not good that the condition was ambiguous.

I changed this condition as follows.

```diff
diff --git a/lib/rubocop/cop/style/symbol_proc.rb b/lib/rubocop/cop/style/symbol_proc.rb
index 243e160f4..4bc3c62b0 100644
--- a/lib/rubocop/cop/style/symbol_proc.rb
+++ b/lib/rubocop/cop/style/symbol_proc.rb
@@ -31,7 +31,7 @@ module RuboCop
         end

         def on_block(node)
-          symbol_proc?(node) do |send_or_super, block_arg, method|
+          symbol_proc?(node) do |send_or_super, block_args, method|
             block_method_name = resolve_block_method_name(send_or_super)

             # TODO: Rails-specific handling that we should probably make
@@ -40,7 +40,8 @@ module RuboCop
             return if proc_node?(send_or_super)
             return if %i[lambda proc].include?(block_method_name)
             return if ignored_method?(block_method_name)
-            return if block_arg.source.include?(',')
+            return if block_args.children.size == 1 &&
+                      block_args.source.include?(',')

             offense(node, method, block_method_name)
           end
```

Is there a case to worry about?

**Comment by bbatsov** [comment]
👍
