### PR TITLE
[Fix #6861] Fix a false positive for `Layout/IndentationWidth`

### LINKED ISSUE #6861: Layout/IndentationWidth conflicts with Layout/AccessModifierIndentation EnforcedStyle: outdent
Setting `EnforcedStyle: outdent` for `Layout/AccessModifierIndentation` causes conflict with `Layout/IndentationWidth` starting with rubocop 0.66.0.

## Expected behavior

No error as there is no new cops relevant to the example file.
Running same commands using previous rubocop version `rubocop _0.65.0_` and `rubocop _0.65.0_ --auto-correct` finishes successfully and without any corrections.

## Actual behavior

Running `rubocop` reports an error, running `rubocop --auto-correct` reports two corrected errors then fails with message about infinite loop + backtrace.

## Steps to reproduce the problem

Create file `test.rb`:
```rb
# frozen_string_literal: true

# Test Layout/IndentationWidth problem
class Test
private

  def test
    :test
  end
end
```

Create file `.rubocop.yml`:
```yml
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
```

Run `rubocop`:
```
Inspecting 1 file
C

Offenses:

test.rb:5:1: C: Layout/IndentationWidth: Use 2 (not 0) spaces for indentation. (https://github.com/rubocop-hq/ruby-style-guide#spaces-indentation)
private


1 file inspected, 1 offense detected
```

Run `rubocop --auto-correct`:
```
Inspecting 1 file
C

Offenses:

test.rb:5:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 0) spaces for indentation. (https://github.com/rubocop-hq/ruby-style-guide#spaces-indentation)
private

test.rb:5:3: C: [Corrected] Layout/AccessModifierIndentation: Outdent access modifiers like private. (https://github.com/rubocop-hq/ruby-style-guide#indent-public-private-protected)
  private
  ^^^^^^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in …/test.rb.
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:263:in `check_for_infinite_loop'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:246:in `block in iterate_until_no_changes'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:245:in `loop'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:245:in `iterate_until_no_changes'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:216:in `do_inspection_loop'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:137:in `file_offense_cache'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:117:in `file_offenses'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:105:in `process_file'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:82:in `block in each_inspected_file'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:81:in `each'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:81:in `reduce'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:81:in `each_inspected_file'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:73:in `inspect_files'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/runner.rb:39:in `run'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/cli.rb:174:in `execute_runner'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/cli.rb:75:in `execute_runners'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/lib/rubocop/cli.rb:47:in `run'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/exe/rubocop:13:in `block in <top (required)>'
…/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
…/lib/ruby/gems/2.5.0/gems/rubocop-0.66.0/exe/rubocop:12:in `<top (required)>'
…/bin/rubocop:23:in `load'
…/bin/rubocop:23:in `<main>'
…/bin/ruby_executable_hooks:15:in `eval'
…/bin/ruby_executable_hooks:15:in `<main>'
```

## RuboCop version

`0.66.0 (using Parser 2.6.2.0, running on ruby 2.5.3 x86_64-darwin18)`

### PR DESCRIPTION
**Pull request by koic**
Fixes #6861.

This is a regression by https://github.com/rubocop-hq/rubocop/pull/6792.

This PR fixes infinite loop for `Layout/IndentationWidth` cop and `Layout/AccessModifierIndentation` cop.

```ruby
# exmaple.rb
class Foo
private

  def do_something
  end
end
```

```yaml
# .rubocop.yml
% cat .rubocop.yml
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
```

First, auto-corrected by `Layout/IndentationWidth`.

```console
% rubocop -v
0.66.0
% rubocop -a --only Layout/IndentationWidth
Inspecting 1 file
C

Offenses:

example.rb:2:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 0)
spaces for indentation.
private

1 file inspected, 1 offense detected, 1 offense corrected
```

```diff
% git diff example.rb
diff --git a/example.rb b/example.rb
index 063e6a5..081b80a 100644
--- a/example.rb
+++ b/example.rb
@@ -1,5 +1,5 @@
 class Foo
-private
+  private

   def do_something
   end
```

Next, auto-corrected by `Layout/Layout/AccessModifierIndentation` (`EnforcedStyle: outdent`).

```console
% rubocop -a --only Layout/AccessModifierIndentation
Inspecting 1 file
C

Offenses:

example.rb:2:3: C: [Corrected] Layout/AccessModifierIndentation: Outdent
access modifiers like private.
  private
  ^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

This will return to the original code.

```diff
% git diff
diff --git a/example.rb b/example.rb
index 081b80a..063e6a5 100644
--- a/example.rb
+++ b/example.rb
@@ -1,5 +1,5 @@
 class Foo
-  private
+private

   def do_something
   end
```

That caused the infinite loop in `Layout/IndentationWidth` and `Layout/AccessModifierIndentation` (`EnforcedStyle: outdent`).

With this PR, `Layout/indentationWidth` cop makes aware of `Layout/AccessModifierIndentation` cop.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/indentation_width.rb [hunk 1]
```diff
@@ -165,18 +165,16 @@ def autocorrect(node)
...
 
           if indentation_consistency_style == 'rails'
             check_members_for_rails_style(members)
           else
-            members.first.children.each do |member|
-              next if member.send_type? && member.access_modifier?
-
-              check_indentation(base, member)
-            end
+            check_members_for_non_rails_style(base, members)
```
Comment (koic) [inline lib/rubocop/cop/layout/indentation_width.rb]: 📝I extracted to the method because it was warned by `Metrics` cops.

**Comment by jonas054** [comment]
Hi @koic,
Great description of the problem and solution. I found one remaining problem. If I start with `EnforcedStyle: outdent` for `Layout/AccessModifierIndentation` and
```ruby
# example.rb
class Foo
                 private

  def do_something
    # something
  end
end
```
Auto-correction changes it to
```ruby
# example.rb
class Foo
private

                 def do_something
                   # something
                 end
end
```

**Comment by koic** [comment]
@jonas054 Sure! I was not aware of this problem 💦 I'll look it up. Thanks for your checking.

**Comment by deivid-rodriguez** [comment]
Hello @koic! Thanks for working on this, do you still plan to wrap this up?

**Comment by mvastola** [comment]
Wanted to second merging this PR once the remaining issues are fixed. If it helps, this only seems to be a problem if the access modifier is the first line of code in the class/module. So maybe the issue with autocorrect could be fixed by limiting changes to the first line of code in this case?

**Comment by bbatsov** [comment]
@koic What's the state here?

**Comment by koic** [comment]
Sorry I'm late.  I updated this PR and added the following mentioned issue as a test.
https://github.com/rubocop-hq/rubocop/pull/6866#issuecomment-478321279

**Comment by deivid-rodriguez** [comment]
Thanks for fixing this @koic!! :heart:
