### PR TITLE
[Fix #6526] Fix a wrong line highlight in `Lint/ShadowedException` cop

### LINKED ISSUE #6526: Wrong line highlighted by Lint/ShadowedException
When a rescue group contains a higher level exception on the same line as a lower level exception, and a lower level exception is on one of the preceding lines in the same group, the wrong line is highlighted by `Lint/ShadowedException`.

--------

## Expected behavior

Highlight the line containing `NoMethodError` in the examples below.

## Actual behavior

Highlights the line containing `ZeroDivisionError` in the examples below.

## Steps to reproduce the problem

```rb
begin
  something
rescue ZeroDivisionError
  handle_exception
rescue NoMethodError, StandardError
  handle_standard_error
end
```
or
```rb
begin
  something
rescue ZeroDivisionError
  handle_exception
rescue StandardError
  handle_standard_error
rescue NoMethodError
  handle_no_method_error
end
```
## RuboCop version

```
$ [bundle exec] rubocop -V
0.60.0 (using Parser 2.5.1.2, running on ruby 2.5.3 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by tatsuyafw**
Fixes #6526.

As reported in #6526, `Lint/ShadowedException` cop highlighted a wrong line as below.

```
begin
  something
rescue ZeroDivisionError
^^^^^^^^^^^^^^^^^^^^^^^^
  handle_exception
rescue NoMethodError, StandardError
  handle_standard_error
end
```

or

```
begin
  something
rescue ZeroDivisionError
^^^^^^^^^^^^^^^^^^^^^^^^
  handle_exception
rescue StandardError
  handle_standard_error
rescue NoMethodError
  handle_standard_error
end
```

This change fixes the above incorrect behavior.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by tatsuyafw** [comment]
Rebased to resolve conflicts.

File: lib/rubocop/cop/lint/shadowed_exception.rb [hunk 1]
```diff
@@ -72,17 +68,17 @@ def on_rescue(node)
...
-                    end
-
-          range_between(first_rescue.loc.expression.begin_pos, end_pos)
+          shadowing_rescue = find_shadowing_rescue(rescues)
+          expression = shadowing_rescue.loc.expression
+          range_between(expression.begin_pos, expression.end_pos)
+        end
+
+        def rescued_groups_for(rescues)
+          rescues.each_with_object([]) do |group, exceptions|
```
Comment (rrosenblum) [inline lib/rubocop/cop/lint/shadowed_exception.rb]: Since the code is changing anyways, I think this can use `map` instead of `each_with_object`.

```ruby
rescues.map do |group|
  rescue_group, = *group
  evaluate_exceptions(rescue_group)
end
```

**Comment by tatsuyafw** [comment]
@rrosenblum 

Thank you for your review 😄 
I've fixed the code (use `map` instead of `each_with_object`) and rebased again.

**Comment by koic** [comment]
Thanks!
