### PR TITLE
[Fix #6175] BracesAroundHashParameters syntax error with trailing comma

### LINKED ISSUE #6175: Auto-correction of BracesAroundHashParameters with trailing commas breaks code
Hi,
I found a case that the auto-correction of the `Style/BracesAroundHashParameters` cop results in a syntax error.

`.rubocop.yml`:

```yaml
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/BracesAroundHashParameters:
  Enabled: true
```

`a.rb`:

```ruby
hello(
  :bob,
  {
    a: 1,
    b: 2,
  },
)
```

--------

## Expected behavior

RuboCop auto-corrects `a.rb` like this:

```ruby
hello(
  :bob,
  a: 1,
  b: 2,
)
```

## Actual behavior

RuboCop auto-crrects `a.rb` like this:

```ruby
hello(
  :bob,
    a: 1,
    b: 2,
  ,
)
```

The result is obviously an syntax error 😱 

```shell
$ ruby -c a.rb
a.rb:5: syntax error, unexpected ',', expecting ')'
```

## Steps to reproduce the problem

```shell
bundle exec rubocop -a a.rb
```

## RuboCop version

```
$ bundle exec rubocop -V
0.58.2 (using Parser 2.5.1.2, running on ruby 2.4.1 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by bacchir**
See [#6175](https://github.com/rubocop-hq/rubocop/issues/6175)

Fixes `Style/BracesAroundHashParameters` auto-correct syntax error when there's a trailing comma after the hash. My approach to solve this is detecting the trailing comma before correcting and removing it together with the right curly brace (the same way it does with trailing spaces).

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/braces_around_hash_parameters_spec.rb [hunk 1]
```diff
@@ -71,7 +71,7 @@
     it 'registers an offense for one hash parameter with braces and ' \
        'whitespace' do
       expect_offense(<<-RUBY.strip_indent)
-        where(  
+        where(
```
Comment (bquorning) [inline spec/rubocop/cop/style/braces_around_hash_parameters_spec.rb]: I believe there is supposed to be trailing whitespace here. It was added in aab0516dd34247aed2588254690b5639524684ca

Comment (bacchir) [reply spec/rubocop/cop/style/braces_around_hash_parameters_spec.rb]: Fixed 😊
