### PR TITLE
[Fix #5963] Allow Performance/ReverseEach to add offense regardless of receiver

### LINKED ISSUE #5963: Performance/ReverseEach only captures array literals
`Performance/ReverseEach` only catches offenses if the receiver of `reverse.each` is an array literal. If the receiver is a variable or a method call, it does not match the node and does not register an offense.

I would be happy to contribute a PR to fix this, but I'm not sure how to detect what receivers this should apply to. If it's okay to apply this cop to any receiver, I have a fix ready to go, but I'm not sure how to detect that the receiver is an Enumerable (if that's even possible).

--------

## Expected behavior

Neither of these examples are picked up by the cop:

```ruby
arr = [1, 2, 3]
arr.reverse.each
```

```ruby
def arr
  [1, 2, 3]
end

arr.reverse.each
```

## Actual behavior

Neither of the above examples register offenses.

## Steps to reproduce the problem

Both of the above examples reproduce the problem.

## RuboCop version

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.4.3 x86_64-darwin16)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
This attempts to fix #5963 by having the node matcher ignore the receiver instead of being hardcoded to an array.

The caveat here is that it's possible that a class could implement `reverse.each` without implementing `reverse_each` would would cause a false positive.

I'm not sure if there's any way to verify that the receiver responds to `reverse_each` or is an enumerable in the matcher, but if there is please let me know so I can update the PR!

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config_loader_resolver.rb [hunk 1]
```diff
@@ -42,7 +42,7 @@ def resolve_inheritance_from_gems(hash, gems)
         end
 
         hash['inherit_from'] = Array(hash['inherit_from'])
-        Array(config_path).reverse.each do |path|
+        Array(config_path).reverse_each do |path|
```
Comment (dvandersluis) [inline lib/rubocop/config_loader_resolver.rb]: With the change, this popped up as an offense.
