### PR TITLE
[Fix #9290] Fix a false positive for `Layout/SpaceBeforeBrackets`

### LINKED ISSUE #9290: Layout/SpaceBeforeBrackets: a space is incorrectly added to `strip_whitespace % w[name email]`
## Expected behavior

Does noting to `before_validation { to_downcase %w[email] }` 

## Actual behavior

Layout/SpaceBeforeBrackets: a space is incorrectly added to `before_validation { to_downcase %w[email] }` => `before_validation { to_downcase % w[email] }`

## Steps to reproduce the problem

Add `before_validation { to_downcase %w[email] }`to model file

## RuboCop version

```
$ [bundle exec] rubocop -V
1.7.0 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.7.2 x86_64-linux)
  - rubocop-performance 1.9.1
  - rubocop-rails 2.9.1
  - rubocop-rspec 2.1.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #9290.

This PR fixes a false positive for `Layout/SpaceBeforeBrackets` when using array literal argument for method call.

If receiver is a method call, it is difficult to prevent false positives.
Therefore, This PR change behaviour to detect only when receiver is a variable.

As a result, safe detection is possible.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/space_before_brackets_spec.rb [hunk 1]
```diff
@@ -4,26 +4,52 @@
...
       RUBY
 
       expect_correction(<<~RUBY)
+        collection = do_something
         collection[index_or_key]
       RUBY
     end
 
-    it 'does not register an offense when not using space between receiver and left brackets' do
+    it 'registers an offense and corrects when using space between ivar receiver and left brackets' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/space_before_brackets_spec.rb:20]: Seems to me this should cover `gvars` and `cvars` as well.

Comment (koic) [reply spec/rubocop/cop/layout/space_before_brackets_spec.rb:20]: I added these tests.

**Comment by bbatsov** [comment]
Thanks!
